### ISSUE TITLE
qadics coercion problem

### ISSUE THREAD

**Issue by fieker** [Nemocas/Nemo.jl#1000]
```julia
julia> Q = QadicField(13, 3, 10);
julia> _, t = PolynomialRing(ZZ, "t");
julia> Q(t^3)
(13^0 + O(13^10))*a^3

julia> Q(t^4)
0

julia> Q(t)^3
(11*13^0 + 12*13^1 + 12*13^2 + 12*13^3 + 12*13^4 + 12*13^5 + 12*13^6 + 12*13^7 + 12*13^8 + 12*13^9 + O(13^10))*a + 2*13^0 + 12*13^1 + 12*13^2 + 12*13^3 + 12*13^4 + 12*13^5 + 12*13^6 + 12*13^7 + 12*13^8 + 12*13^9 + O(13^10)

julia> Q(t)^4
(11*13^0 + 12*13^1 + 12*13^2 + 12*13^3 + 12*13^4 + 12*13^5 + 12*13^6 + 12*13^7 + 12*13^8 + 12*13^9 + O(13^10))*a^2 + (2*13^0 + 12*13^1 + 12*13^2 + 12*13^3 + 12*13^4 + 12*13^5 + 12*13^6 + 12*13^7 + 12*13^8 + 12*13^9 + O(13^10))*a
```
it is supposed to do  a divrem somewhere...

Possibly the problem is with 
qadic_set_fmpz_poly -> qadic_reduce

**Comment by wbhart** [comment]
I don't really understand this example. Where does the "a" come from?

Shouldn't I be able to set the generator of the extension somehow? If I just type "a" it doesn't know what it is and there doesn't seem to be a constructor to set it.

I think there is something I am misunderstanding about qadics.

Also, why does Q(t^4) return 0. It's not even printed the same way as one for example. I thought the defining polynomials were Conway polynomials. But instead I get:

```
julia> Q, a = FiniteField(13, 3, "a")
(Finite field of degree 3 over F_13, a)

julia> a^4
11*a^2 + 2*a
```

**Comment by wbhart** [comment]
Also, are we really doing the right thing allowing coercions from polynomial rings into fields? I hope this doesn't get us into trouble later on when we start introducing more complex coercions. The way I see it there is no canonical coercion here. It probably should be called something else.

**Comment by wbhart** [comment]
And which is the unexpected output here?

**Comment by thofma** [comment]
I guess @fieker forgot the line `a = gen(Q)`.

**Comment by thofma** [comment]
I guess @fieker forgot the line `a = gen(Q)`.

**Comment by thofma** [comment]
I guess @fieker forgot the line `a = gen(Q)`.

**Comment by wbhart** [comment]
I would really be happier if this behaved the same as the other parent object constructors and returned the generator.

**Comment by fieker** [comment]
The example is complete. I agree, the generator should be returned, but
this is what it is.
I assume, since that would make sense, that qadics are poly over padics mod
the Conway poly. The coercion if fmpz poly is expected to do a divrem....
However, it is not, and docu in the library is thin....

**Comment by fieker** [comment]
The a is coming straight from Nemo or flint.
My understanding is Q(t) should be a, the generator.

**Comment by thofma** [comment]
Your example is incomplete because `a` is not defined, as in, `a` is not assigned.

**Comment by fieker** [comment]
A is only output, as in printing..m

**Comment by thofma** [comment]
Ah sorry, I get it. My bad.

**Comment by wbhart** [comment]
I have to leave this one to you @thofma 

I don't see what is going on here. I don't see why Q(t^4) is zero. And as for divrem, well the outputs are both degree less than 3 in a, so....
