### ISSUE TITLE
AnticCyclotomicField and AnticMaximalRealSubfield don't exist

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#1001]
Reading https://nemocas.github.io/Nemo.jl/latest/numberfield.html#Constructors-1 makes me think that the first three functions exists, while only `AnticNumberField` does.

While on the subject, could it be better to link it to the existing docstring for `CyclotomicField` and `MaximalRealSubfield`?

**Comment by wbhart** [comment]
Yeah those are definitely incorrect. We should probably just remove them or move the other constructors into the right place.

**Comment by wbhart** [comment]
I will wait until @thofma comments on this before fixing it, in case there is some interaction with Hecke.

**Comment by thofma** [comment]
Yes, thanks. Looks fine to me. On a related note, I would be in favor of removing the `MaximalRealSubfield` function. Or rename it to `RealSubfieldCyclotomic` or `CyclotomicRealSubfield`. There are many other maximal real subfields of other number fields, so this name is a bit unfortunate. What do you think @wbart?

**Comment by wbhart** [comment]
One can only have a maximal real subfield of a totally real field. But yes, there should be more of those, so I'm ok removing or renaming it.

**Comment by thofma** [comment]
The function computes the maximal real subfield `Q(\zeta_n + \zeta_n^-1)` of the totally complex field `Q(\zeta_n)`.

Any CM-field has a maximal real subfield. It seems a bit arbitrary to make `MaximalRealSubfield` have something to do with cyclotomic fields.

**Comment by wbhart** [comment]
Sorry, that's what I meant of course. And yes, I agree.
