### ISSUE TITLE
Calling fmp[z,q]_poly

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#1003]
With the current build I get
```
julia> fmpz_poly(2)
Error showing value of type fmpz_poly:
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getproperty at ./Base.jl:33 [inlined]
 [2] parent at /home/albin/jlpkg/Nemo.jl/src/flint/fmpz_poly.jl:22 [inlined]
...
```
while
```
julia> fmpz_poly(2);
```
works. I get something similair for `fmpq_poly`.

I'm pretty sure it complain over not having a parent. Should I be able to call this by myself?

If I should be able to call these by myself, then maybe it should be tested as well (it is not at the moment)?

**Comment by wbhart** [comment]
You can't call these yourself because there is no parent information. The design is that the parent information should be added later. I don't recall why we did this, but there was a reason once upon a time.

**Comment by thofma** [comment]
Yes, they are internal and using them directly is not part of the interface.
