### ISSUE TITLE
 Bump version to v20.0

### ISSUE THREAD

**Issue by abagciphys** [Nemocas/Nemo.jl#1004]
I must say from my point of view  "Bump version to v20.0" was a bad idea since too much change and modifications going on Nemo in which most of them not compatible with earlier versions...We had a discussion about previously anyway I stocked on v0.18.4 since it was just fine to me. Recently I felt necessity of re-installation however "my version" :) not anymore available and replacing ":libarb" to "Nemo.libarb" solves some but not all the problems about compatibility.
So I decided to publish my program as a package even it is written by a person who have average skill on computing, for your consideration... Me and some other have got use Mathematica notation, accordingly a math.jl file written for this purpose. Most of deps except Nemo are for tests of our formulae for quantum mechanical angular momentum coefficients such as Clebsch-Gordan and Gaunt etc... 
These are used for solution some integrals arise quantum-chem. The main goal in fact the codes for molecular auxiliary functions integrals...anyway you will see there I hope my issue...And I left here my mail abagci.phys@gmail.com for required personnel communication.  I need both Julia and Nemo... 
I can say I am ok after all with an installation link to v0.18.4 :))
Thank you

**Comment by wbhart** [comment]
I am glad everything is ok with v0.18.4, but I hope you will be able to update your code to work with the new changes in Nemo. If you have any specific problems, let us know.

Did you mean to leave a link to your package? I don't see it in your post.

**Comment by abagciphys** [comment]
The package name JRAF and it is on my profile... It works after installation but the tests only passes for v0.18.4
I will do my best this case however I am afraid that after such performance to feel necessity of updating again in future ;)
https://github.com/abagciphys/JRAF.jl.git
Thank you again...

**Comment by thofma** [comment]
With the following change the tests of your package pass for me with Nemo 0.20.0.
```julia
function NO(x::acb)
    return NO(real(x)) + im * NO(imag(x))
end
```

**Comment by thofma** [comment]
P.S.: You need to tell your users to install `Legendre` by hand.

**Comment by thofma** [comment]
P.S.: You need to tell your users to install `Legendre` by hand.

**Comment by abagciphys** [comment]
Dear @thofma Such simple modification works fine with latest version...Thank you for investigation the code and that correction...

**Comment by thofma** [comment]
Glad to hear that it works.

**Comment by abagciphys** [comment]
Thank you again for this great project Nemo...I would like to express humblely, it is great project and hope that in future Nemo be comprehensive as Sage in terms of applied mathematics so we have accurate and as fast as C program that avoid us looking for some alternatives for long time. We were struggling between simplicity, accuracy and CPU time for a decades. Julia finally intended to solve that problem but this has been possible with only Nemo contribution.

**Comment by thofma** [comment]
P.S.: We changed `prec` to `precision`. If you run the tests, you see the warning.
