### ISSUE TITLE
mulhigh_n, divexact_low issues

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#1022]
In Misc we have mulhigh_n. The code comment says:

> computes the top n coeffs of the product only

However, it is easy to see from both the sum description and the code itself that if n = 0 then one coefficient is computed, not zero. Therefore I think this should say:

> computes the top n + 1 coeffs of the product only

But then the name of the function seems to be incorrect.

How do you want me to resolve this issue?

I guess mulhigh is not used for the name because it is not computing the coeffs that mullow does not compute, as would be normal for mulhigh.

Do you want me to change this to actually compute the top n terms of the product? Or do you want me to adjust the description? How is this actually being used?

@fieker @thofma

**Comment by fieker** [comment]
On Tue, Mar 16, 2021 at 01:27:24AM -0700, wbhart wrote:
> In Misc we have mulhigh_n. The code comment says:
> 
> > computes the top n coeffs of the product only
> 
> However, it is easy to see from both the sum description and the code itself that if n = 0 then one coefficient is computed, not zero. Therefore I think this should say:
> 
> > computes the top n + 1 coeffs of the product only
> 
> But then the name of the function seems to be incorrect.
> 
> How do you want me to resolve this issue?
> 
> I guess mulhigh is not used for the name because it is not computing the coeffs that mullow does not compute, as would be normal for mulhigh.
> 
> Do you want me to change this to actually compute the top n terms of the product? Or do you want me to adjust the description? How is this actually being used?
> 
I thoght I copied it exactly from flint. It is used in the same way as
in flint, namely in the van-Hoeij factorisation to compute the cld's...

if it works otherwise, I'd just bann n==0, but I'd like to compare it to
the flint code and see where the difference is. Could be a < vs. <=?

**Comment by wbhart** [comment]
There's nothing special about n = 0. It always computes n+1 terms regardless of what n is.

**Comment by fieker** [comment]
On Tue, Mar 16, 2021 at 01:42:16AM -0700, wbhart wrote:
> There's nothing special about n = 0. It always computes n+1 terms regardless of what n is.

THen it is a change of documentation only? As I said, it is copied from
flint (or was intended to be copied from flint) 
OK: aparently obviously not, as I don't have (or use) Karatsuba...

So I don't know where it came from...

**Comment by wbhart** [comment]
Flint has a classical mulhigh which computes all *but* the first n terms. This is used in mulhigh_n to compute all but the first n - 1 terms (assuming both inputs were length n), resulting in computation of the top n terms.

**Comment by wbhart** [comment]
Ok I will change the documentation to say something else. But this is going to conflict with the Flint function if we ever wrap it.

**Comment by wbhart** [comment]
divexact_low is also implemented incorrectly. It will raise division by zero if the trailing coeffs are zero.

**Comment by wbhart** [comment]
My mistake, trail does not return the constant coefficients.

**Comment by wbhart** [comment]
Actually, no, it's incorrect:

```
julia> c = 3*x^6 + 5*x^5 + 3*x^4 + 6*x^3 + 4*x^2 + x + 2
3*x^6 + 5*x^5 + 3*x^4 + 6*x^3 + 4*x^2 + x + 2

julia> a = 3x^3 + 2x^2 + x + 2
3*x^3 + 2*x^2 + x + 2

julia> divexact(c, a)
x^3 + x^2 + 1

julia> divexact_low(c, a, 3)
ERROR: ArgumentError: not an exact division
Stacktrace:
 [1] divexact at /home/wbhart/.julia/dev/AbstractAlgebra/src/julia/Integer.jl:119 [inlined]
 [2] divexact_low(::AbstractAlgebra.Generic.Poly{BigInt}, ::AbstractAlgebra.Generic.Poly{BigInt}, ::Int64) at /home/wbhart/.julia/dev/AbstractAlgebra/src/generic/Misc/Poly.jl:114
 [3] top-level scope at REPL[91]:1
```

**Comment by wbhart** [comment]
However, this means valence is not needed, as apparently this is what trail does now.
