### ISSUE TITLE
Transpose of array with Nemo types

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#103]
Since julia 0.5.0, we have the following behaviour
```julia
julia> M = [ fmpz() fmpz() fmpz(); fmpz() fmpz() fmpz()]
2×3 Array{Nemo.fmpz,2}:
 0  0  0
 0  0  0

julia> transpose(M)
WARNING: the no-op `transpose` fallback is deprecated, and no more specific `transpose` method for Nemo.fmpz exists. Consider `permutedims(x, [2, 1])` or w
riting a specific `transpose(x::Nemo.fmpz)` method if appropriate.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in transpose(::Nemo.fmpz) at ./deprecated.jl:770
 in transpose_f!(::Base.#transpose, ::Array{Nemo.fmpz,2}, ::Array{Nemo.fmpz,2}) at ./arraymath.jl:369
 in transpose(::Array{Nemo.fmpz,2}) at ./arraymath.jl:407
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
while loading no file, in expression starting on line 0
3×2 Array{Nemo.fmpz,2}:
 0  0
 0  0
 0  0
```
The builtin transpose function will now "transpose" every entry in the array (think of matrices of matrices, but you want to treat it as one big matrix), and the generic `transpose(x) = x` will eventually be removed. Since we surely want to support transposing arrays of Nemo types, we have to do something. The example above would be fixed by defining
```julia
Base.transpose(x::fmpz) = deepcopy(x)
```
Because matrices are also subtypes of `RingElem` we cannot just do
```julia
Base.transpose{T <: RingElem}(x::T) = deepcopy(x)
```
This is really annoying. So far I have fixed the problems in the Nemo source using `permutedims(M, [1,2])`, but I think we all agree that compared to a simple `transpose(M)` or `M'` this is not a real solution.

**Comment by wbhart** [comment]
I don't like the direction Julia has taken here, but we have to roll with
it I think. It seems like transpose isn't the name they want us to use for
transposing a matrix. Instead they want us to use permutedims. I think this
is pretty stupid, but we have to live with it.

The alternative is to implement a generic trans function which does what we
think transpose should do and just tell our users transpose doesn't do what
they think it does and that the correct function to call is trans.

Bill.

**Comment by wbhart** [comment]
Or, maybe we can just add transpose{T <: RingElem}(a::T) = a to Rings.jl
and be done with it.

Bill.

**Comment by thofma** [comment]
You mean we use
```julia
transpose{T <: RingElem}(a::T) = deepcopy(a)
transpose{T <: MatElem}(a::T) = do some real transposing
```
Right? Will this work with the dispatch? Looks like the same problem we had before.

**Comment by wbhart** [comment]
Ah yes, same problem as before. And same solution, I guess.

Anyway, it's just a suggestion. I'm happy with it if you are.

**Comment by thofma** [comment]
I'll prepare a PR and add a comment.
