### ISSUE TITLE
similar/zero can still generate matrices of the wrong type

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#1045]
```
julia> using Nemo

julia> M = matrix(QQ, [1 2; 3 4])
[1   2]
[3   4]

julia> typeof(M)
fmpq_mat

julia> N = similar(M, ZZ)
[0 0]
[0 0]

julia> typeof(N)
AbstractAlgebra.Generic.MatSpaceElem{fmpz}
```

I think the Nemo version of similar has to do the coercion into the new ring itself, rather than rely on AbstractAlgebra to do it, as the latter will always generate a generic matrix.

**Comment by wbhart** [comment]
Or better yet it should ignore the ring of the first argument and look at the type of the Ring argument instead.

**Comment by wbhart** [comment]
You guys don't define custom polynomial types that don't use generic polynomials in Hecke do you?

**Comment by thofma** [comment]
No.

**Comment by thofma** [comment]
(And I agree with your conclusion.)

**Comment by wbhart** [comment]
Apparently we decided in https://github.com/Nemocas/Nemo.jl/issues/651 that this was desired behaviour, so as to not break deepcopy and related things.

In fact, the regression test breaks if I make the change that I think makes sense. So I'm going to leave this one alone.
