### ISSUE TITLE
Access violation in flint-2.7.1/fmpz

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#1053]
Unfortunately the same problem reappears every few versions: 
I suggest to read first this issue from 2019 for inspiration, https://github.com/Nemocas/Nemo.jl/issues/585
It disappeared in the meantime, it now is back with almost identical symptoms:

The current error message looks like this:

Please submit a bug report with steps to reproduce this fault, and any error messages tty). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1ede6ba4 -- .text at C:\Users\User\AppData\Lin\libgmp-10.dll (unknown line)
in expression starting at c:\Users\User\GitHub2021\IntegerTriangles.jl\src\TrianglesTra
.text at C:\Users\User\AppData\Local\Programs\Julia-1.6.1\bin\libgmp-10.dll (unknown li
fmpz_get_str at /workspace/srcdir/flint-2.7.1/fmpz\get_str.c:34
base at C:\Users\User\.julia\packages\Nemo\xNg6C\src\flint\fmpz.jl:1751
dec at C:\Users\User\.julia\packages\Nemo\xNg6C\src\flint\fmpz.jl:1735 [inlined]
string at C:\Users\User\.julia\packages\Nemo\xNg6C\src\flint\fmpz.jl:269 [inlined]
show at C:\Users\User\.julia\packages\Nemo\xNg6C\src\flint\fmpz.jl:271 [inlined]
print at .\strings\io.jl:35
Println at c:\Users\User\GitHub2021\IntegerTriangles.jl\src\TrianglesBase.jl:849
Println at c:\Users\User\GitHub2021\IntegerTriangles.jl\src\TrianglesBase.jl:846
unknown function (ip: 0000000060fa5282)
Println at c:\Users\User\GitHub2021\IntegerTriangles.jl\src\TrianglesBase.jl:859
_broadcast_getindex_evalf at .\broadcast.jl:648 [inlined]
_broadcast_getindex at .\broadcast.jl:621 [inlined]
getindex at .\broadcast.jl:575 [inlined]
macro expansion at .\broadcast.jl:984 [inlined]
macro expansion at .\simdloop.jl:77 [inlined]
copyto! at .\broadcast.jl:983 [inlined]
copyto! at .\broadcast.jl:936 [inlined]
copy at .\broadcast.jl:908 [inlined]
materialize at .\broadcast.jl:883 [inlined]
xTraitCard at c:\Users\User\GitHub2021\IntegerTriangles.jl\src\TrianglesTraitCard.jl:30
unknown function (ip: 0000000060fd3eae)
#9 at c:\Users\User\GitHub2021\IntegerTriangles.jl\src\TrianglesTraitCard.jl:321
#open#317 at .\io.jl:330
open at .\io.jl:328 [inlined]
AllTraitCards at c:\Users\User\GitHub2021\IntegerTriangles.jl\src\TrianglesTraitCard.jl
unknown function (ip: 0000000060fc472e)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
do_call at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:115
eval_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:204
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:877
jl_toplevel_eval at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:886 [inlined]
jl_toplevel_eval_in at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:929
eval at .\boot.jl:360 [inlined]
eval at .\client.jl:446
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
do_call at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:115
eval_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:204
eval_stmt_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:155 [inlined]
eval_body at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:576
jl_interpret_toplevel_thunk at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:670
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:877
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:825
jl_toplevel_eval at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:886 [inlined]
jl_toplevel_eval_in at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:929
eval at .\boot.jl:360 [inlined]
exec_options at .\client.jl:261
_start at .\client.jl:485
jfptr__start_22922.clone_1 at C:\Users\User\AppData\Local\Programs\Julia-1.6.1\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
true_main at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.c:560
repl_entrypoint at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.c:702
mainCRTStartup at /cygdrive/c/buildbot/worker/package_win64/build/cli\loader_exe.c:51
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 14084525 (Pool: 14081344; Big: 3181); GC: 16

**Comment by thofma** [comment]
What are the steps to reproduce this?

**Comment by PeterLuschny** [comment]
It is like the last time, again: I do not manage to isolate the 
error. It depends on the overall process whether it appears or not.

To illustrate this, an example: the two lines below show the error 
in context: it first announces itself in the first line by 
making the wrong values '0', before in the second line the 
exception occurs.

[1, 16777191, 282010106381, 274419271461131, 52652460630984375, 3332058336247871041, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3332058336247871041, 52652460630984375, 274419271461131, 282010106381, 16777191, 1, 0]
[1, 33554406, 846416194536, 1103881308184906, 269025107855605626, 
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1ee36ba4 -- .text at C:\Users\User\AppData\Local\Programs\Julia-1.6.0\bin\libgmp-10.dll (unknown line)

The same call, this time computed in isolation, works fine:

[1, 16777191, 282010106381, 274419271461131, 52652460630984375, 3332058336247871041, 90359270750971846371, 1220805072813932520741, 9022467342263743368906, 38735478389273100343750, 100396047731185055904546, 160755658074834738495566, 160755658074834738495566, 100396047731185055904546, 38735478389273100343750, 9022467342263743368906, 1220805072813932520741, 90359270750971846371, 3332058336247871041, 52652460630984375, 274419271461131, 282010106381, 16777191, 1, 0]
[1, 33554406, 846416194536, 1103881308184906, 269025107855605626, 21045399230106913746, 695824003645512474376, 11392907456028953400606, 101955892318210543172751, 531714261368950897339996, 1685388700882132120106256, 3334612565134607644610436, 4179647109945703200884716, 3334612565134607644610436, 1685388700882132120106256, 531714261368950897339996, 101955892318210543172751, 11392907456028953400606, 695824003645512474376, 21045399230106913746, 269025107855605626, 1103881308184906, 846416194536, 33554406, 1, 0]

**Comment by thofma** [comment]
Can you post the steps that (sometimes) lead to the segfault?

**Comment by wbhart** [comment]
Just to clarify: an access violation is a very general kind of error. It is the rough equivalent of a certain kind of segfault on Linux and can occur for a myriad of reasons, usually due to (our) poorly written code. With millions of lines of code in our projects so far, it is not too much of a stretch to imagine numerous such issues.

Therefore, I think it unlikely this is a problem that keeps reappearing every few years. It is more likely that you are hitting a bug that we are not aware of. This is why steps to narrow down what is causing it might be helpful.

Very likely the gc running at random times is occasionally causing a faulty finalizer to run or is cleaning up an object still in use which needs to be protected from such cleanup, or there is a segfault in Flint itself (or perish the thought, in GMP). This is likely localised to a certain object that is created and not managed properly (by us), or to a certain function in which the bug occurs.

That is why steps that do occasionally (even if rarely) lead to this error will be useful in localising the issue.

**Comment by PeterLuschny** [comment]
Thanks for the comments!

>  or there is a segfault in Flint itself (or perish the thought, in GMP).
>
Dieu m’en préserve ! *but **the latest news is ...*

gmp: overflow in mpz type
signal (22): SIGABRT
in expression starting at
C:\Users\User\GitHub2021\IntegerTriangles.jl\src\TrianglesExplorer.jl:224
crt_sig_handler at
/cygdrive/c/buildbot/worker/package_win64/build/src\signals-win.c:93
raise at C:\WINDOWS\System32\msvcrt.dll (unknown line)
abort at C:\WINDOWS\System32\msvcrt.dll (unknown line)
__gmp_default_alloc_overflow at
C:\Users\User\AppData\Local\Programs\Julia-1.6.1\bin\libgmp-10.dll (unknown
line)
.text at C:\Users\User\AppData\Local\Programs\Julia-1.6.1\bin\libgmp-10.dll
(unknown line)
.text at C:\Users\User\AppData\Local\Programs\Julia-1.6.1\bin\libgmp-10.dll
(unknown line)
flint_mpz_mul_si at /workspace/srcdir/flint-2.7.1\gmpcompat.h:147 [inlined]
fmpz_mul_si at /workspace/srcdir/flint-2.7.1/fmpz\mul_si.c:43
Allocations: 40706184 (Pool: 40693577; Big: 12607); GC: 56

**Comment by thofma** [comment]
@PeterLuschny has sent me an example. I will try to reproduce.

**Comment by thofma** [comment]
We tracked down the bug. It is the same as `https://github.com/Nemocas/Nemo.jl/issues/810` with the same solution. We should write this in the Misc section of the manual.
