### ISSUE TITLE
Is it officially impossible to remove the Nemo banner when used as part of another module?

### ISSUE THREAD

**Issue by Krastanov** [Nemocas/Nemo.jl#1054]
Hello! This has been discussed a bit in issues and on discourse, but I was hoping to get an official answer **concerning the use of Nemo inside of other libraries**. This is explicitly **not** about interactive use of Nemo, with all the potential caveats about interactivity and the GPL.

I want to use flint functionality implemented in Nemo from my package QuantumClifford.jl. However, the `ENV["NEMO_PRINT_BANNER"] = false` trick does not work when used from inside of another module. This leads to having the banner be printed out after invoking `using QuantumClifford`.

Is this the intended behavior **when Nemo is used non-interactively from other packages**?

**Comment by thofma** [comment]
Thanks for raising this issue about the non-interactive question. We are thinking about an easy way to suppress the banner in this case.

**Comment by Krastanov** [comment]
That line is not the issue. The issue is that you can not set ENV before Nemo executes its init function, because your module's init function is always called after the init functions of imported modules. You can get around that by creating a third module that is to be imported before Nemo like this one https://github.com/Krastanov/NoBannerNemo

**Comment by thchr** [comment]
> That line is not the issue.

Ahh, my mistake: thanks for clarifying.

**Comment by thofma** [comment]
This should be fixed by #1055. There will be a new release soonish.
