### ISSUE TITLE
Base ring of nf_elem is currently Union{}

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#1056]
I'm currently developing an absolute FunctionField module where it is convenient to have the base_ring of the function field be the rational function field that the function field is an algebraic extension of.

In analogy, it would seem to make sense to have the base_ring of a number field be FlintQQ.

Does anyone have any objections to this?

The rationale for making it Union{} originally was that a number field doesn't depend (in a parametric sense) on any base ring. It's not a general type of construction over an arbitrary ring, like a polynomial ring over a base ring. But I think this is just another way of saying that it wasn't a useful concept for number fields at the time.

This change may have implications for Hecke (or even Nemo for that matter), I don't know. I will run tests and see if anything breaks.

**Comment by thofma** [comment]
We have rolled out `base_field` exactly for this purpose, which gives `FlintQQ` for `AnticNumberField`. We would have liked to use `base_ring`, but there was some resistance because this is not what `base_ring` means.

**Comment by wbhart** [comment]
Ah, ok, I can rename my field/getter to base_field in my FunctionField implementation. Thanks.

**Comment by wbhart** [comment]
In fact, it may make more sense for me to leave it as base_ring, since FunctionField really is a generic construction over a RationalFunctionField and just add the base_field(K) getter function to mirror what happens with the number field implementation.

That is unless you have an objection to the RationalFunctionField being referred to as a base_ring at all?

**Comment by thofma** [comment]
No, I think it is fine if you want to define it as `base_ring`.

P.S.: Maybe we need to revisit our definition/methods for `base_ring` at some later point. But this is not urgent.
