### ISSUE TITLE
No way to get defining polynomial for number field

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#1058]
Currently there is no way to get the defining polynomial out of a number field after it is created.

As it happens, the Flint nf struct stores it as an fmpq_poly on the C side, without the additional information we have on the Julia side such as the variable symbol, parent, etc.

We could add a function modulus(R::AnticNumberField) which returns the defining polynomial.

The main problem is figuring out what ring to return the defining polynomial in. There are a few options:

1) Store the Julia defining polynomial in the AnticNumberField struct when the number field is created. This has the advantage of the defining polynomial remaining in the ring it was originally defined in by the user.

2) Return it as an unreduced polynomial in terms of the number field generator. Unfortunately this is not possible for the linear number fields which only have space for one coefficient, even though the defining polynomial has two terms. I'm not sure this is possible, as attractive as it sounds.

3) Define the function modulus(R::AnticNumberField, var::String="x"; cached::Bool=true) which returns it in terms of a new polynomial ring with variable name x which as usual is cached for the user, but when used internally should set cached=false.

Do the Hecke people have any opinions on this? Have you already some mechanism for handling this?

Obviously whatever we do has to also work for function fields, though I think all three options are possible there.

I guess a fourth option is to have no such function and rely on the user keeping track of it themselves. However, we do allow the modulus for other residue rings/fields to be returned.

I think I might actually prefer option 1, not sure. I think it is the most compatible with the existing modulus functions in other residue rings/fields.

@fieker @thofma

**Comment by thofma** [comment]
We have
```julia
defining_polynomial(K::AnticNumberField) = K.pol
```
Is there a problem with this?

**Comment by wbhart** [comment]
Oh I see, we actually already store it in there. I had overlooked this. Thanks.

Would you have any problem with me defining modulus to also return the same thing? I think that is what we have for other residue rings/fields.

```
julia> R, x = PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rational Field, x)

julia> S = ResidueRing(R, x^3 + 3x + 1)
Residue ring of Univariate Polynomial Ring in x over Rational Field modulo x^3 + 3*x + 1

julia> modulus(S)
x^3 + 3*x + 1
```

I'm of course completely happy to have defining_polynomial for FunctionFields as well, and we can move the Hecke definition for defining_polynomial over to Nemo.

**Comment by thofma** [comment]
I think it makes sense to have both `defining_polynomial` and `modulus`. I will move `defining_polynomial` from Hecke to Nemo before making the new release.

**Comment by wbhart** [comment]
Great, thanks!

**Comment by thofma** [comment]
Cosed by #1059.
