### ISSUE TITLE
Document `roots` for non-complex polynomials

### ISSUE THREAD

**Issue by ssiccha** [Nemocas/Nemo.jl#1068]
When I type `?roots` into the Julia REPL it shows me a method for `acb_poly`s. However, when I call `roots` on a polynomial over `GF(p)` it computes all roots/zeros. I suggest to document that method too.

`using AbstractAlgebra` also gives me no additional documentation.

**Comment by ssiccha** [comment]
Ah, wait a second. I guess `roots` shouldn't be called like that. Because I get:
```
julia> p = 3
3

julia> GFx, x = PolynomialRing(GF(p), "x")
(Univariate Polynomial Ring in x over Galois field with characteristic 3, x)

julia> roots(x^2 + x)
2-element Vector{Nemo.gfp_elem}:
 2
 2
```
Then of course either an error or a method which can actually compute the zeros would be nice. Or is the above just a bug in `roots`?

**Comment by wbhart** [comment]
Looks like a bug to me. One of the roots should surely be 0.

**Comment by ssiccha** [comment]
Did you also add documentation somewhere?

**Comment by thofma** [comment]
Not yet.

**Comment by ssiccha** [comment]
Ah, thanks. I thought I simply missed it. :)

**Comment by thofma** [comment]
Closed by https://github.com/Nemocas/AbstractAlgebra.jl/pull/880.
