### ISSUE TITLE
Some types don't define check_parent

### ISSUE THREAD

**Issue by fredrik-johansson** [Nemocas/Nemo.jl#1080]
julia> check_parent(fmpz(2), fmpz(3))
    ERROR: MethodError: no method matching check_parent(::fmpz, ::fmpz)
    Stacktrace:
     [1] top-level scope at REPL[7]:1

I noticed this because it was missing for qqbar, which breaks generic algorithms:

    julia> R, x = PolynomialRing(QQBar, "x");

    julia> gcd(x^2 - 1, x + 1)
    ERROR: MethodError: no method matching check_parent(::qqbar, ::qqbar)
    Stacktrace:
     [1] gcd(::qqbar, ::qqbar) at /home/fredrik/.julia/dev/AbstractAlgebra/src/Fields.jl:22
     [2] content(::AbstractAlgebra.Generic.Poly{qqbar}) at /home/fredrik/.julia/dev/AbstractAlgebra/src/generic/Poly.jl:2033
     [3] gcd(::AbstractAlgebra.Generic.Poly{qqbar}, ::AbstractAlgebra.Generic.Poly{qqbar}) at /home/fredrik/.julia/dev/AbstractAlgebra/src/generic/Poly.jl:2003
     [4] top-level scope at REPL[11]:1

I guess we're not running into this with fmpz because polynomials will use fmpz_poly instead of generic code, but perhaps other generic code could be affected too?

Should there be a fallback implementation that checks parent(a) == parent(b) for any elements, or should we reimplement this for every type in Nemo?

**Comment by wbhart** [comment]
check_parent is not part of the official ring interface, so I am pretty sure it is a bug in the generic code.

**Comment by thofma** [comment]
https://github.com/Nemocas/AbstractAlgebra.jl/blob/97d5e3e92ffd371c4d07c120c49701d17819dc11/src/Fields.jl#L21-L24

Since these are fallback methods, I think they should check the parent. Not sure there is any other option.

**Comment by wbhart** [comment]
They could just check parent(a) == parent(b) which would impose the least additional burden on the generic interface.

**Comment by thofma** [comment]
If I remember correctly there a types which do not construct parents by default, for which this would be quite expensive. Thinking of matrices here. Not sure how common this is though.

**Comment by wbhart** [comment]
Ok. I prefer fallbacks for check_parent to making it an additional burden on the required ring interface, so let's do that.
