### ISSUE TITLE
delete some of the parent object (ring) printing code

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/Nemo.jl#1082]
In connection with https://github.com/Nemocas/AbstractAlgebra.jl/pull/887, it would be nice not to have, for example, the following pointless duplication
https://github.com/Nemocas/Nemo.jl/blob/d530e05417be934630f0ef9cda2ffc021c63f052/src/flint/fmpz_mpoly.jl#L283-L300
There is minimal required interface to get this working generically.

**Comment by wbhart** [comment]
I'm afraid I have no idea what you mean, or how it is related to 887.

I will do MPoly last, but I am not putting any major effort into it at this time. I would like to make an abstract interface for MPolys, but it's not something I'm doing for that PR.

**Comment by tthsqe12** [comment]
What I mean is: once `symbols` and `coefficient_ring` are implemented, the printing can be implemented generically in terms of this required interface. There is no need for all of this code duplication.

**Comment by fingolfin** [comment]
This one has been resolved quite some time ago in PR #1438
