### ISSUE TITLE
problem with `elem_length` for `nf_elem`

### ISSUE THREAD

**Issue by ThomasBreuer** [Nemocas/Nemo.jl#1084]
I get the following with Julia 1.5.3.
```julia
julia> using Nemo

Welcome to Nemo version 0.23.0

Nemo comes with absolutely no warranty whatsoever


julia> F, z = Nemo.CyclotomicField(2)
(Cyclotomic field of order 2, -1)

julia> x = rand(F, 0:5); (x, x.elem_length)  # now repeat this input line
(3, 13)

[...]

julia> x = rand(F, 0:5); (x, x.elem_length)
(4//5, 139749230232048)

```
Several code pieces for `nf_elem` objects `x` run over the range `1:x.elem_length`, thus I think something is wrong here.

**Comment by thofma** [comment]
Looks like a bug to me. One usually should not access `x.elem_length` directly, but I guess you have some code that does it?

**Comment by thofma** [comment]
Oh, no, sorry. It is not a bug. Don't use `x.elem_length` unless you know what you are doing. It is not safe to use it if the number field has degree `1` or `2`. If you show us where it is used we can try to find safe solution.

**Comment by ThomasBreuer** [comment]
@thofma Thanks. `Hecke.force_coerce_cyclo` uses `elem_length`. Here is an example.
```julia
julia> F, z = Nemo.CyclotomicField(2); z.elem_length  # perhaps try several times until a huge number is returned
140142465974288
julia> Hecke.force_coerce_cyclo( F, z )
(and then wait ...)
```

**Comment by thofma** [comment]
Thanks, I will have a look.

**Comment by thofma** [comment]
https://github.com/thofma/Hecke.jl/pull/305
