### ISSUE TITLE
inverse in polynomial ring over `ZZ`

### ISSUE THREAD

**Issue by 8d1h** [Nemocas/Nemo.jl#1090]
Inverting a non-invertible element, say 2, in a polynomial ring over `ZZ` yields different results depending on whether the ring is univariate or multivariate (which in my opinion should always raise an error; in `AbstractAlgebra` this is indeed the case).
```julia
julia> inv(PolynomialRing(ZZ, "x")[1](2))
0

julia> inv(PolynomialRing(ZZ, ["x"])[1](2))
ERROR: Division is not exact in divexact
Stacktrace:
 [1] divexact
   @ ~/.julia/packages/Nemo/ZPSws/src/flint/fmpz_mpoly.jl:641 [inlined]
 [2] inv(x::fmpz_mpoly)
   @ AbstractAlgebra ~/.julia/dev/AbstractAlgebra/src/Rings.jl:99
 [3] top-level scope
   @ REPL[3]:1
```
And here is what happens if we consider a ring of integers in `Hecke`.
```julia
julia> OO = maximal_order(quadratic_field(-1)[1])
Maximal order of Imaginary quadratic field by x^2 + 1
with basis nf_elem[1, sqrt(-1)]

julia> inv(PolynomialRing(OO, "x")[1](2))
ERROR: Quotient not an element of the order
Stacktrace:
 [1] divexact
   @ ~/.julia/packages/Hecke/dyUKa/src/NfOrd/Elem.jl:490 [inlined]
 [2] divexact
   @ ~/.julia/packages/Hecke/dyUKa/src/NfOrd/Elem.jl:486 [inlined]
 [3] divexact(f::AbstractAlgebra.Generic.Poly{NfOrdElem}, g::AbstractAlgebra.Generic.Poly{NfOrdElem})
   @ AbstractAlgebra ~/.julia/dev/AbstractAlgebra/src/Poly.jl:1336
 [4] inv(x::AbstractAlgebra.Generic.Poly{NfOrdElem})
   @ AbstractAlgebra ~/.julia/dev/AbstractAlgebra/src/Rings.jl:99
 [5] top-level scope
   @ REPL[5]:1

julia> inv(PolynomialRing(OO, ["x"])[1](2))
0
```

**Comment by wbhart** [comment]
That first example looks like a definite bug.

**Comment by wbhart** [comment]
Ah yeah, this is left over from the days where divexact assumed the division was exact. We don't use that definition any more, and this code has just never been changed.

We call the flint fmpz_poly_div function. Nowadays we have an fmpz_poly_divides function which should be used instead.

We can make a patch to fix this.

**Comment by wbhart** [comment]
This should automatically be fixed by https://github.com/Nemocas/AbstractAlgebra.jl/pull/945

**Comment by wbhart** [comment]
Seems to be fixed now.

**Comment by 8d1h** [comment]
Thanks!

**Comment by 8d1h** [comment]
Er...
```julia
julia> using Nemo

Welcome to Nemo version 0.26.1-dev

Nemo comes with absolutely no warranty whatsoever


julia> inv(PolynomialRing(ZZ, "x")[1](2))
0
```
It still returns 0.

**Comment by wbhart** [comment]
My mistake. I tried this in AbstractAlgebra, not Nemo. It is still broken.
