### ISSUE TITLE
Error during change base ring

### ISSUE THREAD

**Issue by iliailmer** [Nemocas/Nemo.jl#1094]
I have a polynomial over rationals and I am trying to change the base ring via `>change_base_ring(GaloisF, poly)` command. However, I get the following error:
```julia
>change_base_ring(GaloisF, poly)
ERROR: MethodError: no method matching (::Nemo.GaloisField)(::fmpq)
```
How can this be resolved?

**Comment by wbhart** [comment]
It looks like the missing method hasn't been implemented. Presumably no one thought to add it yet.

Of course you can use map_coefficients instead:

```
map_coefficients(x->K(numerator(x, false))//K(denominator(x, false)), fmpq(2)*x^2 + fmpq(3)*x + fmpq(1))
```

where K is your Galois field.

**Comment by tthsqe12** [comment]
Note: this is in oscar in the wrong place, so it will have to be moved.
https://github.com/oscar-system/Oscar.jl/blob/master/experimental/ModStd/ModStdQ.jl#L21

**Comment by thofma** [comment]
This is not the same one (but should be moved anyway).
