### ISSUE TITLE
Can we make ComplexField(QQ) ?

### ISSUE THREAD

**Issue by zhaoli-IHEP** [Nemocas/Nemo.jl#1110]
Is it possible to have the rational complex field instead of the float number complex field? 
Meanwhile maybe fit into LaurentSeriesField(ComplexField(QQ), 5, "ep")?

**Comment by thofma** [comment]
It is already there, but maybe not under the name that you would have in mind.
```julia
julia> Qx, x = QQ["x"]
(Univariate Polynomial Ring in x over Rational Field, x)

julia> CC, i = NumberField(x^2 + 1, "i")
(Number field over Rational Field with defining polynomial x^2 + 1, i)

julia> i^2
-1
```
(https://en.wikipedia.org/wiki/Gaussian_rational)

Do you have a suggestion for an alias? Would you suggest `ComplexField(QQ)`?

**Comment by zhaoli-IHEP** [comment]
> It is already there, but maybe not under the name that you would have in mind.
> 
> ```julia
> julia> Qx, x = QQ["x"]
> (Univariate Polynomial Ring in x over Rational Field, x)
> 
> julia> CC, i = NumberField(x^2 + 1, "i")
> (Number field over Rational Field with defining polynomial x^2 + 1, i)
> 
> julia> i^2
> -1
> ```
> 
> (https://en.wikipedia.org/wiki/Gaussian_rational)
> 
> Do you have a suggestion for an alias? Would you suggest `ComplexField(QQ)`?

So great! Thank you. 
I think ComplexField(QQ) would be nice.

**Comment by thofma** [comment]
Let's hear what the others think. @wbhart @tthsqe12

**Comment by wbhart** [comment]
I don't have any objections. It would be nice if it also worked for Nemo.

**Comment by thofma** [comment]
This is a about Nemo.

**Comment by tthsqe12** [comment]
I have a reservation about ComplexField(QQ): it suggests that we can do ComplexField(F) for a multitude of fields F, ie extent F by a nonreal something. What is ComplexField(GF(5)) or ComplexField(GF(7))?
If you share my reservations, name them GaussianRationals() and GaussianIntegers(). Otherwise, call it whatever you want. Just make sure all instances hash equal!

On a related note, Complex{fmpq} doesn't work :(

**Comment by thofma** [comment]
After sleeping one night over this, I also don't like it too much anymore. It does not really play nice with `im` and should it return both the field and the imaginary unit? It is also awkward because one needs to use `i = gen(K)` to get the imaginary unit.

**Comment by fingolfin** [comment]
We won't add `ComplexField(QQ)` (or `complex_field(QQ)`) but indeed `QQi` exists in Nemo, and `quadratic_field` in Hecke / Oscar
