### ISSUE TITLE
//(::fmpq, ::fmpz) is ambiguous

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/Nemo.jl#1120]
surprising, isn't it?

**Comment by wbhart** [comment]
Not really. There was a recent rearrangement of the promotion system and there are sure to be some issue still.

**Comment by tthsqe12** [comment]
I tried this on a 163-day-old nemo, and it was the same.

**Comment by wbhart** [comment]
Oh well, I guess it is broken then. I guess someone didn't define all the necessary ad hoc operators.
