### ISSUE TITLE
Enable root tests (will require flint-2.9)

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#1125]
In fmpz-test.jl there are some tests in the fmpz.roots section which will fail until flint-2.9 comes out. These should be reenabled then.

The actual check=true flag is also currently ignored in the root function in fmpz.jl. This also has to be reenabled when flint-2.9 comes out.

Also see #741

**Comment by wbhart** [comment]
Note that there are similar disabled tests in fmpq-test.jl once #1279 is merged

**Comment by lgoettgens** [comment]
Resolved by #1395.
