### ISSUE TITLE
Implement ispower and ispower_with_root for fmpz (will require flint-2.9)

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#1126]
These are still not implemented as per https://github.com/Nemocas/Nemo.jl/issues/862 though all the other functions in the table there are now implemented for integer types.

**Comment by wbhart** [comment]
These can be implemented in terms of Flint's fmpz_root function which returns an int if the root is exact.

**Comment by fingolfin** [comment]
We have `is_power`, `is_prime_power`, `is_prime_power_with_data`, `is_perfect_power`, `is_perfect_power_with_data` all native for `ZZRingElem`. I believe that resolve the issue.
