### ISSUE TITLE
Does "NEMO_THREADED" work now?

### ISSUE THREAD

**Issue by zhaoli-IHEP** [Nemocas/Nemo.jl#1130]
Recently we are trying to improve the code efficiency via parallelization. And we saw the option "NEMO_THREADED" in Nemo. For a simple test, we make the following script.
```
using Nemo
using BenchmarkTools

const precision_digits = 256
const precision_bits =  round(Int64, precision_digits*log(10)/log(2) )

const RR = RealField(precision_bits)

const ms_arb = Generic.MatSpace{arb}
const mse_arb = Generic.MatSpaceElem{arb}

function init_mat( x::Int64 )::mse_arb

  nn = 100
  mat = zero( ms_arb( RR, nn, nn ) )
  for rr in 1:nn, cc in 1:nn
    mat[rr,cc] = x*rand(RR,randtype=:null_exact)+rand(RR)*1e-100
  end # for rr, cc

  return mat

end # function init_mat


function mul_mat( mat1::mse_arb, mat2::mse_arb )::mse_arb
  return mat1*mat2
end # function mul_mat

mat1 = init_mat(3)
mat2 = init_mat(6)

@btime mul_mat( mat1, mat2 )

```

But we do not see any improvement with or without "NEMO_THREADED=1" in front of the script running.
So did we do something wrong or else?

**Comment by wbhart** [comment]
I don't believe it is used for Arb matrices, however @fredrik-johansson may be able to comment on this.

**Comment by fredrik-johansson** [comment]
Have you checked with Flint matrices? With large enough matrices, matrix multiplication in Arb will be threaded only if it is threaded in Flint.

There is an arb_mat_mul_threaded that can be called explicitly, but it may be slower than the single-threaded code.

**Comment by wbhart** [comment]
Also, did you set the number of threads? You have to call `flint_set_num_threads`

**Comment by wbhart** [comment]
Also, you need to set NEMO_THREADED *before* starting Julia.

**Comment by zhaoli-IHEP** [comment]
> Have you checked with Flint matrices? With large enough matrices, matrix multiplication in Arb will be threaded only if it is threaded in Flint.
> 
> There is an arb_mat_mul_threaded that can be called explicitly, but it may be slower than the single-threaded code.

Do you mean we can use flint matrix associated with Arb element? 
How can we use it explicitly?

**Comment by zhaoli-IHEP** [comment]
> Also, you need to set NEMO_THREADED _before_ starting Julia.

Yes, now we add the `flint_set_num_threads(16)` in the script. And the script was run via 
```
NEMO_THREADED=1 julia test.jl 
```
And we do not see any improvement.

**Comment by wbhart** [comment]
Ok, that's a shame, but presumably your problem size is not large enough to benefit from parallelisation. We tuned it as carefully as we could.

**Comment by fredrik-johansson** [comment]
I believe the problem is large enough to benefit. It takes nearly one second. For one reason or another Arb or Flint just isn't using parallel code here.

**Comment by wbhart** [comment]
Oh, I think the issue is that Nemo might still be using flint-2.7. I thought @thofma had already updated it to flint-2.8, but at least in master the Project.toml file suggests it hasn't happened yet.

**Comment by thofma** [comment]
No, it is not updated. We want to rebuild all the other binaries first.

**Comment by wbhart** [comment]
If I am not mistaken, the latest version of Nemo now uses flint-2.8? Perhaps @thofma can confirm?
