### ISSUE TITLE
to_mpfr not defined

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#1145]
Please consider:

    CC = ComplexField(80)  
    integrate(CC, exp, 0, 1; rel_tol = 1.0e-6)

ERROR: LoadError: UndefVarError: to_mpfr not defined

Stacktrace:
 [1] getproperty
   @ .\Base.jl:26 [inlined]

 [2] integrate(C::Nemo.AcbField, F::typeof(exp), a::Int64, b::Int64; rel_tol::Float64, abs_tol::Float64,
     deg_limit::Int64, eval_limit::Int64, depth_limit::Int64, use_heap::Int64, verbose::Int64)
   @ Nemo C:\Users\User\.julia\packages\Nemo\EXnlj\src\arb\acb_calc.jl:38

Nemo version 0.26.1
Windows 64

**Comment by tthsqe12** [comment]
Hmm, I guess this never worked? Or worked on very old julia version? I guess we should be using `MPFRRoundDown'
```
julia> Base.MPFR.
BigFloat              _prettify_bigfloat     had_nan
DEFAULT_PRECISION     _string                had_overflow
MPFRRoundDown         _unchecked_cast        had_range_exception
MPFRRoundFaithful     big_ln2                had_underflow
MPFRRoundFromZero     check_exponent_err     include
MPFRRoundNearest      clear_flags            nextfloat!
MPFRRoundToZero       eval                   patches
MPFRRoundUp           get_emax               prevfloat!
MPFRRoundingMode      get_emax_max           set_emax!
ROUNDING_MODE         get_emax_min           set_emin!
_BigFloat             get_emin               setprecision
__init__              get_emin_max           string_mpfr
_cpynansgn            get_emin_min           version
_duplicate            had_inexact_exception
```

**Comment by thofma** [comment]
Yes, I think it worked on an old julia version and this path is not tested.

**Comment by tthsqe12** [comment]
So it is now it uses the `convert` function
```
convert(::Type{MPFRRoundingMode}, ::RoundingMode{:Down})     = MPFRRoundDown
```

But, honestly I would just put `MPFRRoundDown` in our code.

**Comment by thofma** [comment]
Maybe going the `convert` route is more future proof? Or maybe there is an easier way to get the smallest long `r` with `2^-r < x` for an mpfr `x`?

**Comment by tthsqe12** [comment]
convert is probably better. I wouldn't change the rest of the code too much. Also, can you export integrate while you are at it?

**Comment by PeterLuschny** [comment]
A side question: How do I call integrals of the following type:
 "int_0^{inf} sech(x) dx   (using domain truncation)",
 "int_0^{inf} 1/gamma(x) dx   (using domain truncation)",
 from https://github.com/fredrik-johansson/arb/blob/master/examples/integrals.c

**Comment by thofma** [comment]
There is no automatic way to do this. You have to integrate up to a bound and then use an explicit error term for the tail.
