### ISSUE TITLE
Should remove always return an fmpz?

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#1156]
remove(10, 2) returns an fmpz. Is this desired behaviour?

@fieker @thofma @tthsqe12

**Comment by tthsqe12** [comment]
It is bit surprising to return fmpz for Int input. For example, the binomial function binom returns Int for Int input and throws if the answer doesn't fit.
If there were a generic implementation of remove in AA (hint :)), we could probably get the Int answer here for free.

**Comment by thofma** [comment]
Agreed.

**Comment by wbhart** [comment]
Wait. There's no generic implementation of remove in AA? What manner of.....

**Comment by tthsqe12** [comment]
AA.ZZ does not even satisfy the Euclidean interface, so there lost of room for improvement.

**Comment by wbhart** [comment]
Ok, I'll bite. What does it screw up?

**Comment by tthsqe12** [comment]
well, there was the gcd(a,b)*lcb(a,b) != a*b thing, which we are changing to be ok. But also, remove didn't work in pure AA without nemo.

**Comment by wbhart** [comment]
I see.

**Comment by tthsqe12** [comment]
I am on this integer remove issue.
