### ISSUE TITLE
`root(a::fmpq, b::Int) -> fmpq` is missing

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/Nemo.jl#1178]

**Comment by wbhart** [comment]
Root is missing for all types in the system except integers. It's an ongoing project.

**Comment by tthsqe12** [comment]
Ok, but the fact that it is missing is embarrassingly on display in the oscar docs. Flint implementation, or just pop this into Nemo?

**Comment by wbhart** [comment]
Not sure how easy it is. It might be better in Flint.
