### ISSUE TITLE
Update the website

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#1187]
I was just informed that people are unaware there has been a release of Nemo since 2018 because the (Nemo) website has not been updated. For example a researcher wanted to know when the next release would be since he wanted to use Calcium (which has been in Nemo for ages).

**Comment by fredrik-johansson** [comment]
On top of this, http://nemocas.github.io/Nemo.jl/latest/ does not actually give documentation for the latest version, but some old version (unclear which).

**Comment by wbhart** [comment]
Yeah I added #1188 for that

**Comment by wbhart** [comment]
Website is updated.
