### ISSUE TITLE
jl_calloc overflows

### ISSUE THREAD

**Issue by mkitti** [Nemocas/Nemo.jl#1193]
I notice that Nemo.jl uses `jl_calloc`. Just be warned that currently the integer multiplication overflows:
https://github.com/JuliaLang/julia/issues/42673

It may return a non-null value and not allocate the memory requested.

```julia
julia> ccall(:jl_calloc,Ptr{Nothing},(Csize_t, Csize_t), 0xffffffffffffffff, 0xffffffffffffffff)
Ptr{Nothing} @0x000000001ebd1180
```

**Comment by wbhart** [comment]
Thanks for letting us know.
