### ISSUE TITLE
`/(::fmpq, ::Int64)` does not exist

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#1194]
Would be nice to have. Probably needs to be implemented in Flint first in that case.

**Comment by thofma** [comment]
I guess you are looking for `divexact`?

**Comment by thofma** [comment]
Interesting. For us it would make things even more inconsistent. In Z the operation `/` gives floating point numbers and in Q it does not. The "exact" things in julia Base really are a lot of nonsense and I personally don't want to add more of it to Nemo.
