### ISSUE TITLE
No method matching `setindex!(::fmpz_mat, ::fmpz, ::Int64)`

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#1203]
```
julia> b = fmpz_mat(1, 3)
[0   0   0]

julia> b[2] = ZZ(2)
ERROR: MethodError: no method matching setindex!(::fmpz_mat, ::fmpz, ::Int64)
```

However, we have
```
julia> b[2]
0
```
I suppose it's similar for other structs.

**Comment by wbhart** [comment]
The main reason we haven't provided setindex! is that Julia is column major, whereas Flint is row major. This cause general could in confusion.

However, we could support it for vectors only, now that this seems to be a thing in Nemo.

**Comment by lgoettgens** [comment]
Resolved by https://github.com/Nemocas/AbstractAlgebra.jl/pull/1407.
