### ISSUE TITLE
Documentation for is_negative, needs_parentheses and show_minus_one is missing

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#125]
These functions are needed for any ring that is designed to work with Polynomial.jl. But their interface is not documented anywhere. See issue #126

**Comment by thofma** [comment]
Some more functions I found out about yesterday:
- `(::Ring)()`
- `zero(::Ring)`
- `+`, `-`, `*` for `RingElem`
- `add!`, `zero!` for `RingElem`
- `elem_type(::Type{Ring})`
- `parent_type(::Type{RingElem})`

**Comment by wbhart** [comment]
These are obsolete.
