### ISSUE TITLE
Document what functions any new RingElem module needs to work

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#126]
Each kind of generic ring in Nemo, e.g. polynomials, multivariate polynomials, etc., needs certain functions to exist in the base ring before it can be used, e.g. mul!, addeq!, zero!, add!, needs_parentheses, parent, hash, etc.

These should be documented somewhere for people implementing a new kind of ring.

**Comment by thofma** [comment]
Some more functions I found out about yesterday:
- `(::Ring)()`
- `zero(::Ring)`
- `+`, `-`, `*` for `RingElem`
- `add!`, `zero!` for `RingElem`
- `elem_type(::Type{Ring})`
- `parent_type(::Type{RingElem})`

**Comment by wbhart** [comment]
deepcopy, (::Ring)(Integer), (::Ring)(fmpz), show, promote_rule, base_ring, divexact (if possible)

**Comment by kalmarek** [comment]
I'd be very much interested in this list (to make `GroupRings` play nice with the rest of Nemo).

By naive experimentation I've found that You need also `(::Ring)(i::Int)` (and I guess it'd better agree with  `(::Ring)()`).

**Comment by thofma** [comment]
Still working on the list.

**Comment by wbhart** [comment]
I suggest we might try and address this at our coding sprint next week [1].

[1] https://github.com/Nemocas/Nemo.jl/wiki/OSCAR-:-Antic-Workshop--and--coding-sprint

**Comment by wbhart** [comment]
Done.
