### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#127]
While talking about consistency, maybe we can also decide on names.

1. ~~The first issue would be underscores and `is*` functions. I think apart from some minor exceptions, in julia all the `is*` functions don't have an underscore after the `is`. In Nemo we have both. I propose that we also rename every `is_*` to `is*`.~~
2. ~~In 0.6, julia has changed `num` to `numerator` and `den` to `denominator`. We should probably do the same (once we have switched to julia 0.6).~~

**Comment by wbhart** [comment]
I agree with both your proposals.
