### ISSUE TITLE
convenience methods for arithmetics with vectors of `fmpz` and `fmpq`

### ISSUE THREAD

**Issue by ThomasBreuer** [Nemocas/Nemo.jl#1297]
Currently `fmpz[1, 2, 3] // 2` and `2 * fmpz[1, 2, 3]` work because of generic methods in `base/arraymath.jl` and `base/rational.jl`, respectively.
However, the "more natural" inputs `fmpz[1, 2, 3] // fmpz(2)` and `fmpz(2) * fmpz[1, 2, 3]` do not work.
The same applies to the situation where `fmpz` is replaced by `fmpq`.

I propose to add the following.
```julia
//(v::Vector{fmpz}, x::fmpz) = v .// x
//(v::Vector{fmpq}, x::fmpq) = v .// x

*(x::fmpz, v::Vector{fmpz}) = x .* v
*(x::fmpq, v::Vector{fmpq}) = x .* v

*(v::Vector{fmpz}, x::fmpz) = v .* x
*(v::Vector{fmpq}, x::fmpq) = v .* x
```
Where would be the right place for the methods in question, perhaps `Nemo/src/flint/fmpz.jl` and `Nemo/src/flint/fmpq.jl`, respectively?

**Comment by wbhart** [comment]
Yes, I think just a conveniently labeled section somewhere near to the bottom of those files should do it.
