### ISSUE TITLE
Scalar arithmetic broken for nmod_poly

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#1303]
```
julia> R = ResidueRing(ZZ, 3)
Integers modulo 3

julia> Rx, x = R["x"]
(Univariate Polynomial Ring in x over Integers modulo 3, x)

julia> zero(x) - UInt(1)
1
```
I expected `-1` or `2`.

I think this is directly calling `nmod_poly_sub_ui`, so I can't dig deeper without compiling flint.

**Comment by wbhart** [comment]
It's a bug in Flint. It's setting the coefficient to 1 in that special case, instead of p - 1.

I've fixed the bug in trunk and it will appear in the 2.9 release of Flint.

**Comment by thofma** [comment]
Thanks!
