### ISSUE TITLE
problem with parents of polynomials

### ISSUE THREAD

**Issue by ThomasBreuer** [Nemocas/Nemo.jl#1307]
The following looks strange to me.
```
julia> using Nemo;

julia> R = FqDefaultFiniteField(fmpz(2), 3, :x);  PR, x = PolynomialRing(R, "x");  z = zero(x);

julia> typeof(x)
fq_default_poly

julia> typeof(z)
AbstractAlgebra.Generic.Poly{fq_default}

julia> parent(x) == PR
true

julia> parent(z) == PR
false

julia> typeof(parent(x))
FqDefaultPolyRing

julia> typeof(parent(z))
AbstractAlgebra.Generic.PolyRing{fq_default}
```
The problem seems to be caused by the first `similar` method in `AbstractAlgebra/src/Poly.jl`, which sets a different parent in its result in this situation. (`x` is not a `Generic.Poly{TT}`.)
Thus the issue may be in fact one for AbstractAlgebra.

**Comment by wbhart** [comment]
This was due to the fact that the similar method was never implemented for `fq_default_poly`, probably because the PR's crossed over in time.

I've opened a PR which will fix this.
