### ISSUE TITLE
is_squarefree is missing for fmpz_poly and fmpq_poly

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#1311]
The function is documented as existing in AbstractAlgebra, but missing in Nemo.

**Comment by wbhart** [comment]
Both functions do however exist in Flint.

**Comment by fingolfin** [comment]
Tried `fmpz_poly_is_squarefree` but it gives incorrect results (it considers $4$ or $4*x$ to be square free). With our version of FLINT, at least -- dunno if it is different in FLINT 3.x, @fredrik-johansson ?)

**Comment by thofma** [comment]
It depends a bit on the definition, but most functions related to factoring of fmpz_poly are mathematically wrong. They always give results for the polynomial considered as an element of Q[x] and not Z[x]. We jump through some hoops to make them mathematically correct.

**Comment by fingolfin** [comment]
Was resolved by #1742.
