### ISSUE TITLE
Missing method `(::GaloisFmpzMatSpace)(::fmpz_mat)`;   add conformance tests?

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/Nemo.jl#1317]
The following was observed by a student of me
```
julia> A = ZZ[1 2; 3 4]
[1 2]
[3 4]

julia> K = GF(5)
Galois field with characteristic 5

julia> typeof(K)
Nemo.GaloisField

julia> M = matrix_space(K, 2, 2)
Matrix Space of 2 rows and 2 columns over Galois field with characteristic 5

julia> M(A)
[1 2]
[3 4]
```

So far, so good. The method used in the last line is from `src/flint/gfp_mat.jl:431`:
```julia
function (a::GFPMatSpace)(b::fmpz_mat)
  (ncols(a) != b.c || nrows(a) != b.r) && error("Dimensions do not fit")
  z = gfp_mat(a.n, b)
  z.base_ring = a.base_ring
  return z
end
```

But if we try the same with a "big" prime field, it doesn't work:
```
julia> K = Nemo.FpField(ZZ(5))
Galois field with characteristic 5

julia> typeof(K)
Nemo.GaloisFmpzField

julia> M = matrix_space(K, 2, 2)
Matrix Space of 2 rows and 2 columns over Galois field with characteristic 5

julia> M(A)
ERROR: MethodError: no method matching (::GaloisFmpzMatSpace)(::fmpz_mat)
```

So that missing method needs to be added... or perhaps instead we could add a general implementation?

In any case, I also think that we need conformance tests for MatrixSpace (and many other interfaces) to discover and prevent similar inconsistencies in the future.

PS: Is there a "better" way to convert an `fmpz_mat` to a "native" matrix over an arbitrary Oscar field?

**Comment by thofma** [comment]
I guess we should add that method.

> PS: Is there a "better" way to convert an `fmpz_mat` to a "native" matrix over an arbitrary Oscar field?

Yes, `map_entries(R, M)` or `change_base_ring(R, M)`.

P.S.: The matrix space objects exist "mainly" for the purpose of providing parents for matrices. In most cases there is no need to use them.

**Comment by fingolfin** [comment]
Of course `map_entries`, thank you. I don't know why this doesn't stick in my brain *sigh*
