### ISSUE TITLE
Segmentation fault on global RealField

### ISSUE THREAD

**Issue by zhaoli-IHEP** [Nemocas/Nemo.jl#1328]
We are struggling with the strange problem. Our code always crashes with segmentation fault. This can be reproduced in a sample code on several different computers with Linux or MacOS. It contains two files, `my_test.jl` and `test.jl`. Is it something not legally written?

```
# my_test.jl
module my_test

using Nemo

const precision_digits = 256
const precision_bits =  round(Int64, precision_digits*log(10)/log(2) )

const RR = RealField(precision_bits)

const xx = RR("1e-100")

export my_main

function my_main()::Nothing

  println( xx )

  return nothing
end # function my_main

end # module my_test
```

```
# test.jl
push!( LOAD_PATH, "." )

using my_test

my_main()
```

**Comment by thofma** [comment]
Is it different from https://github.com/Nemocas/Nemo.jl/issues/810?

**Comment by zhaoli-IHEP** [comment]
> Is it different from #810?

oops. It is indeed. Thank you for reminding us of this. I will just close this.
