### ISSUE TITLE
nemocas.org unavailable 

### ISSUE THREAD

**Issue by gvanuxem** [Nemocas/Nemo.jl#1347]
Hi, I don’t know where to put this so I put it here. The nemocas.org is unavailable for me or throws an ssl connection error.
![6CA47441-9B94-40F6-A62F-36F0F5903E92](https://user-images.githubusercontent.com/42774576/193768357-4a9b2ef7-251b-4e2f-9f97-9b05fb83a6af.png)

**Comment by thofma** [comment]
@fredrik-johansson @wbhart do you know what is up with that?

**Comment by fredrik-johansson** [comment]
Bill chose not to renew the domain, which recently expired.

(flintlib.org is in my custody, however.)

**Comment by thofma** [comment]
Thanks for the heads-up. I have purged the domain from the repository. @fredrik-johansson Would you mind sending me a tar archive containing the sources for the homepage? There was some information about timings that would be great not to lose.

**Comment by fredrik-johansson** [comment]
Sure!
