### ISSUE TITLE
no method matching `zero(::Type{qqbar})`

### ISSUE THREAD

**Issue by sumiya11** [Nemocas/Nemo.jl#1348]
Hi! I need method `zero(::Type{qqbar})` for using QQBar with SparseArrays.jl. I am wondering if it's possible to add it ? thank you.

The following is curious:

```julia
using Nemo
qqbar(0)       # works !
zero(qqbar)    # doesn't work :(
```

**Comment by thofma** [comment]
The way LinearAlgebra and SparseArrays implement linear algebra is at odds with our approach to representing elements of rings/fields. This is a fundamental issue, see https://github.com/JuliaLang/julia/issues/37022. We could add the zero for this specific type, but it is low priority. I would just add it yourself for now.

**Comment by sumiya11** [comment]
Just adding the method seems to work; thanks for your answer
