### ISSUE TITLE
MatElem and GenMat

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#135]
I was trying to understand what our `MatElem` "interface" is and where the corresponding functions for `GenMat` are.

I think it would help a lot if we could separate functions for `MatElem` and `GenMat` filewise. But where would the `MatElem` functions go?

Second question. I think we write in the documentation that a custom matrix type has to overload the `getindex` function. Now in generic/Matrix.jl we have
```
function getindex{T <: RingElem}(a::MatElem{T}, r::Int, c::Int)
   return a.entries[r, c]
end
```
This looks like a very specific fallback, which I am not sure we want to have. We would now say in the documentation: A custom matrix type has to implement `getindex` OR it has to have a field named `entries`, which is of type `Array{T, 2}`, where the entries are stored as rows and columns (in this specific order).

I would suggest to restrict the signature to `GenMat` since this is actually the getindex implementation for `GenMat`.

**Comment by wbhart** [comment]
You can separate the files if you want. MatElem.jl and GenMat.jl are ok.

I think the getindex function you list might actually be used by some of the Flint matrices, but I'm not sure. If not, I have no objection to restricting it to GenMat.

**Comment by thofma** [comment]
Ok, I will check. Should there be a src/abstract directory?

**Comment by wbhart** [comment]
It doesn't matter to me. If you want to add one, go right ahead.
