### ISSUE TITLE
Some checks missing for univariates over finite fields

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#1353]
```
F, _ = FiniteField(2, 1, "1")
E, α = FiniteField(2, 15, "α")
S, x = PolynomialRing(F, "x")
defsetf = [1, 2, 4, 8, 16, 19, 32, 38, 59, 64, 76, 85, 105, 118, 128]
f = S(1)
for i in defsetf
    f *= (x - α^i)
end
```
This makes Nemo crash with a segfault.

**Comment by lgoettgens** [comment]
The underlying problem here is that https://github.com/Nemocas/Nemo.jl/blob/a5ba24beca110d33cec131166f65a60b9972d9a1/src/flint/fq_nmod_poly.jl#L825 is not doing any parent check.
