### ISSUE TITLE
Half-gcd ?

### ISSUE THREAD

**Issue by sumiya11** [Nemocas/Nemo.jl#1365]
Hi! Thanks for developing this amazing package.

Is there a way to use half gcd from flint in nemo ?

**Comment by thofma** [comment]
For which coefficient ring? At the moment they are not exposed for the user. The `gcd` function uses them for certain parameter ranges automatically.

**Comment by sumiya11** [comment]
For finite fields and Z/Zp[x], in particular.

To clarify just in case, by half gcd I mean the algorithm that returns the first row of the EEA that has the degree in the reminder sequence less than some number

**Comment by thofma** [comment]
What is the name of flint function that returns this (the function you mentioned in the first post)?

**Comment by sumiya11** [comment]
Sorry, it seems that my terminology was wrong; I've seen the "half gcd" in [flint features](http://flintlib.org/features.html) and assumed they have the algorithm I described in my post above
But going through the flint documentation now, it looks like that by "half-gcd" flint means the nlog^2n gcd implementation

**Comment by thofma** [comment]
Yes, I think so. I will close this for now. If there is a specific flint function that you would like to see wrapped, just reopen or open a new issue.
