### ISSUE TITLE
`roots` is probably quadratic in the worst case

### ISSUE THREAD

**Issue by sumiya11** [Nemocas/Nemo.jl#1370]
Hi, I wanted to share my observation: it looks like root finding over finite fields (perhaps, other fields also) in Nemo has soft quadratic complexity in the worst case. In fact it can be very slow. 

It is suboptimal:
`Nemo.roots` calls `factor`, which is at least quadratic in case there are irreducible factors. Full factorization is not needed for root finding -- roots can be found in average soft linear time.

My guess would be that functions like `nmod_poly_factor_equal_deg` from flint can be used for finite fields, in particular.

Just to illustrate how slow things can become, here is a tiny comparison of `Nemo.roots` to my vanilla 50 lines of code function:

```julia
using Nemo, BenchmarkTools
include("vanilla-roots.jl")

# dense polynomial of degree 2^10
R, x = GF(3*2^30 + 1)["x"]
f = rand(R, 2^10:2^10);

@btime Nemo.roots($f);
#  750.009 ms (17 allocations: 1.58 KiB)

@btime vanilla_roots($f);
#  20.170 ms (166 allocations: 5.91 KiB)

@assert Set(Nemo.roots(f)) == Set(vanilla_roots(f))
```

The file `vanilla-roots.jl` can be found here: https://gist.github.com/sumiya11/ab3eb455cc94ec37333cd9f0c93fe191
The output of `vanilla_roots` is guaranteed to be correct (the algo is Las Vegas).

**Comment by thofma** [comment]
We forgot to wrap the corresponding C functions for root calculation. I will open a PR.
