### ISSUE TITLE
Why is `number_of_partitions` "not available on Windows 64"?

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/Nemo.jl#1387]
From the code:
```julia
function number_of_partitions(x::Int)
   if (Sys.iswindows() ? true : false) && Int == Int64
      error("not yet supported on win64")
   end
...
```
Why is this needed? Is it, actually?

**Comment by thofma** [comment]
According to git blame we would need to ask @fredrik-johansson or try it out ourselves?

**Comment by fredrik-johansson** [comment]
Input >= 2^31 not working for some reason? Don't remember the precise issue though.

**Comment by fingolfin** [comment]
We should find out and add at least a comment with an explanation, ideally also pointing at an issue tracking this (e.g. this one). Even better of course would be to resolve the issue ;-) but then we need someone who has access to a system where one can debug this.

Off my cuff, I wonder if this bug might be related to the fact that on Windows, `long` is 32 bit...
