### ISSUE TITLE
`polynomial_ring`: inconsistent support for `AbstractString`, `Symbol` and `Char`

### ISSUE THREAD

**Issue by mgkurtz** [Nemocas/Nemo.jl#1405]
I would like `polynomial_ring` to consistently support all of `Union{AbstractString, Symbol, Char}` for all types of base rings. Looking at `methods(polynomial_ring)` shows, that actually support haphazardly depends on the base ring type.

Could we add a `polynomial_ring(R, s::Union{AbstractString, Symbol, Char}; kw...)` method, that simply calls `polynomial_ring(R, String(s); kw...)` and remove all the specialized methods? Likewise for the methods creating multivariate polynomial rings.

**Comment by thofma** [comment]
I think that a polynomial ring implementation should implement only the method with `::Symbol` and on top of that we should have a generic
```
function polynomial_ring(R, s::Union{AbstractString, Char}; kw...)
```

**Comment by fingolfin** [comment]
I agree with @thofma. And yes it would be good to have this. @mgkurtz maybe you could work on this?
