### ISSUE TITLE
Wrong reference to `fmpz_mod_mpoly_factor_squarefree`?

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#1419]
https://github.com/Nemocas/Nemo.jl/blob/fb8ae860e6cf4a7a51f1a50212e94816e72df99a/src/flint/fmpz_mod_mpoly.jl#L537

Looks like it should be `fmpz_mod_mpoly_factor_squarefree` instead of `nmod_mpoly_factor_squarefree`. I don't know much about the multivariates, just noticed that my CI failed calling this function.

**Comment by thofma** [comment]
Yes, what you write makes sense.

**Comment by albinahlback** [comment]
Would you like to make a PR for this? Or should I?

**Comment by thofma** [comment]
If you have time to do a PR, that would be great. You probably also have a test that triggers it.

**Comment by albinahlback** [comment]
Actually no, but we should test against the master branch, as opposed to what `Pkg` gives us. I'll fix it.

**Comment by thofma** [comment]
Fixed in #1420
