### ISSUE TITLE
Third root of the zero element of the real numbers fails

### ISSUE THREAD

**Issue by HechtiDerLachs** [Nemocas/Nemo.jl#1440]
Try this:
```julia
CC = ComplexField(128)
RR = parent(abs(one(CC)))
a = zero(RR)
root(a, 3)
```
For me the result is `nan`. This seems to only happen for the third root. `root(a, 2)` is fine, for instance.

**Comment by thofma** [comment]
@fredrik-johansson, do you have an idea what is happening here? This is just calling `arb_root`:
```
julia> RR = ArbField(64)
Real Field with 64 bits of precision and error bounds

julia> a = zero(ArbField(64))
0

julia> for i in 1:10; @show i, root(a, UInt(i)); end;
(i, root(a, UInt(i))) = (1, 0)
(i, root(a, UInt(i))) = (2, 0)
(i, root(a, UInt(i))) = (3, nan)
(i, root(a, UInt(i))) = (4, 0)
(i, root(a, UInt(i))) = (5, nan)
(i, root(a, UInt(i))) = (6, nan)
(i, root(a, UInt(i))) = (7, nan)
(i, root(a, UInt(i))) = (8, nan)
(i, root(a, UInt(i))) = (9, nan)
(i, root(a, UInt(i))) = (10, nan)
```

**Comment by thofma** [comment]
Thanks! I will probably do an `is_zero` check in Nemo for now.

**Comment by HechtiDerLachs** [comment]
Good to have this clarified. But what about the case when `!(x== 0)` but `contains_zero(x)==true`? Then `log(x)` is also ill-defined, isn't it? I'm a bit worried that `is_zero` might not be the correct thing to check.

**Comment by thofma** [comment]
Hm, the check in Nemo is not quite correct. At the moment it is
```
x < 0 && throw(DomainError("x must be positive"))
```
but it should be
```
is_zero(x) && return x
!isnonnegative(x) && throw(DomainError("x must be positive"))
```

Or maybe we should only check `is_zero` and let it return `nan` whenever it wants to.
