### ISSUE TITLE
Conversion from QQ to BigFloat

### ISSUE THREAD

**Issue by daviddelaat** [Nemocas/Nemo.jl#1441]
When using Nemo in combination with other Julia packages it can be useful to be able to convert Nemo types to BigFloat. Currently 
```julia
using Nemo
BigFloat(QQ(3))
```
does not work. Is that something that can be added to Nemo?

**Comment by fingolfin** [comment]
Code for this already exists in Hecke, see https://github.com/thofma/Hecke.jl/blob/master/src/Misc/Integer.jl#L102

So it's mostly a question of whether someone is willing to backport this (@fieker @thofma any concerns?)

Alternatively, just use Hecke or Oscar ;-)

**Comment by fieker** [comment]
no concerns
other than the release cascade

**Comment by fingolfin** [comment]
Resolved in current Nemo
