### ISSUE TITLE
Extra field in fmpz_mod_ctx_struct 

### ISSUE THREAD

**Issue by fredrik-johansson** [Nemocas/Nemo.jl#1463]
In https://github.com/flintlib/flint2/pull/1383 is a change to ``fmpz_mod_ctx_struct`` (adding an extra precomputed inverse structure for huge moduli) which predictably breaks Nemo.

Appending a ``Ptr{Nothing}``  at https://github.com/Nemocas/Nemo.jl/blob/ea5a67a890cb1961c4fe7554c2af5f9d322b2fb2/src/flint/FlintTypes.jl#L512 ought to be a backwards compatible fix, but I haven't tested it in Nemo.

**Comment by thofma** [comment]
Thanks for the heads up.

**Comment by fredrik-johansson** [comment]
Already merged this in Flint, so it would be good to fix in Nemo ASAP.

**Comment by fredrik-johansson** [comment]
Sure. The only catch is that we test Nemo on Flint's CI and for the time being these tests will fail.

**Comment by thofma** [comment]
Ah right, I forgot about CI. I opened #1465.

**Comment by fredrik-johansson** [comment]
Looks like Nemo's tests are still failing: https://github.com/flintlib/flint2/actions/runs/4973156754/jobs/8898812913

**Comment by fredrik-johansson** [comment]
The same fix is needed for ``fq_ctx_struct`` and ``fmpz_mod_mpoly_ctx_struct`` since these structures include an ``fmpz_mod_ctx_struct``. Not sure if there are any others.

**Comment by thofma** [comment]
@fredrik-johansson Will the next official flint release be 3.0 or 2.10? I want to put those changes behind a version check, but I am not sure it should be >= 3.0 or >= 2.10?

**Comment by fredrik-johansson** [comment]
3.0. I will bump the version numbers to 3.0.0-dev.

**Comment by thofma** [comment]
Fixed in #1472

**Comment by thofma** [comment]
@fredrik-johansson could you retrigger https://github.com/flintlib/flint2/actions/runs/5001305511? I would like to check that it also passes there

**Comment by fredrik-johansson** [comment]
Everything is green :-)
