### ISSUE TITLE
RealField constructor without precision

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#1475]
https://nemocas.github.io/Nemo.jl/latest/real/#Real-ball-constructors

RR = RealField()

c = RR(1, precision = 100)
d = RR(1//2, precision = 4)

Return:

MethodError: no method matching (::RealField)(::Int64; precision::Int64) 

(Julia 1.9.0; Nemo v0.34.2)

**Comment by fieker** [comment]
By the looks of it 
```julia> RR(1//3, 10)
[0.333 +/- 4.97e-4]

julia> RR(1//3, 100)
[0.33333333333333333333 +/- 3.34e-21]

julia> precision(RR)
64
```
so we have a default precision... We should have a precision named parameter. What should the semantic be?
