### ISSUE TITLE
is_invertible_with_inverse gives surprising error for matrix over RealField

### ISSUE THREAD

**Issue by fredrik-johansson** [Nemocas/Nemo.jl#1498]
A user reported this:

    mm=MatrixSpace(Nemo.RealField(20),1,1)()
    mm[1,1]=1
    is_invertible_with_inverse(mm)

    results in surprising error message:

    Matrix must be square

    With ComplexField it works fine.

**Comment by lgoettgens** [comment]
Fixed by https://github.com/Nemocas/Nemo.jl/pull/1513.
