### ISSUE TITLE
problem with `gen(Nemo._GF(p, 1))`

### ISSUE THREAD

**Issue by ThomasBreuer** [Nemocas/Nemo.jl#1520]
It seems that `gen(Nemo._GF(p, d))` returns the zero element if `d == 1`.
```
julia> using Nemo

Welcome to Nemo version 0.35.1

Nemo comes with absolutely no warranty whatsoever


julia> p = 2; iszero(gen(Nemo._GF(p, 1)))
true
```
The same happens for other primes `p`.

**Comment by thofma** [comment]
Why is this a problem or a bug? It returns an algebra generator over the base field. Or in other works, it trrats GF(p) as GF(p)[x]/(x) and the generators corrwsppnss to the class of x.

**Comment by ThomasBreuer** [comment]
How can a zero element be a generator of an algebra that contains more than this zero element?

One could argue that a prime field can be generated by an empty set of generators if the field is regarded as an algebra-with-one, but I would expect that `gen` returns a unit when it is called with a prime field.

**Comment by thofma** [comment]
A field is generated by any element over itself. The only guarantee for `a = gen(F)` is that `F[x] -> F, p -> p(a)` is a surjective morphism, which it is if `a` is zero. Or in other words, any element of `F` is a polynomial in `gen(F)`. I don't understand the problem.

**Comment by ThomasBreuer** [comment]
According to the documentation for `gen(a::FqField)`, an algebra generator is returned, but a zero element generates only a zero algebra.
As I wrote above, the concepts of generation as an algebra and as an algebra-with-one are different.

**Comment by thofma** [comment]
What is your definition? For me, an algebra A over K is finitely by a1,...,an, if the evaluation map K[x_1,...,x_n] -> A is surjective.

I am talking about the category of K-algebras.

**Comment by thofma** [comment]
OK, lets forget about algebras. The function returns a generator for the field extension GF(p)/GF(p) (like all functions constructing fields).

**Comment by fieker** [comment]
I'm happy to say that 0 is an unfortunate generator, but I agree with Tommy: a legal one. Q[t]/t is isomorphic to Q and gen would be 0

**Comment by ThomasBreuer** [comment]
O.k.

Then "algebra" means always "algebra-with-one" in Hecke/Oscar.
In particular any matrix algebra contains the scalar matrices, and Lie algebras aren't algebras.

Is this documented anywhere?

**Comment by thofma** [comment]
I am still confused. Where is it stated that `gen(F)` must return a generator as an algebra? I just looked at the definition and saw
```
 gen(a::FqField)

  Return the algebra generator of the finite field over its base field.

  Note that this is in general not a multiplicative generator.
```
If there is some place, where we write that `gen(::FqField)` should return a unit or a generator as a an algebra-without-necessarily-one, then we should fix this.

`gen` depends very much on the category we are working in. I don't understand why gen for fields must treat fields as arbitrary algebras.

P.S.: Of course Lie algebras aren't algebras, since they are not even associative :)

**Comment by thofma** [comment]
Since the defining polynomial is `x`, the generator for this field extension must be zero, since we always want `defining_polynomial(F)(gen(F)) == 0`:

```
julia> gen(F)
0

julia> defining_polynomial(F)
x
```
@ThomasBreuer: Can you explain what you want to do with the generator? We can also discuss this after the Friday meeting if you want.

**Comment by ThomasBreuer** [comment]
@thofma Yes, is will be easier to discuss this today after the meeting.

**Comment by thofma** [comment]
We discussed this and adjusted the docstring.
