### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/Nemo.jl#1537]
Consider this input, taken from one of the Nemo test files and then slightly modified:
```
using Test, Nemo
@testset "ComplexMat.charpoly" begin
   CC = ComplexField()
   S = matrix_space(CC, 3, 3)
   R, x = polynomial_ring(CC, "x")
   ZZy, y = polynomial_ring(ZZ, "y")

   A = S(["2.0 +/- 0.1" "3.0 +/- 0.1" "5.0 +/- 0.1";
          "0.0 +/- 0.1" "4.0 +/- 0.1" "7.0 +/- 0.1";
          "0.0 +/- 0.1" "0.0 +/- 0.1" "3.0 +/- 0.1"])

   f = (y - 2)*(y - 4)*(y - 3)

   g = charpoly(R, A)

   @test contains(g, f)
end
```

In current `master` this results in an error:
```
ComplexMat.adhoc_divexact |    6      6
ComplexMat.charpoly: Error During Test at /home/runner/work/AbstractAlgebra.jl/AbstractAlgebra.jl/oscar-dev/Nemo/test/arb/ComplexMat-test.jl:364
  Got exception outside of a @test
  MethodError: no method matching charpoly(::ComplexPolyRing, ::ComplexMat)
  Closest candidates are:
    charpoly(::AcbPolyRing, ::ComplexMat) at /home/runner/work/AbstractAlgebra.jl/AbstractAlgebra.jl/oscar-dev/Nemo/src/arb/ComplexMat.jl:521
    charpoly(::AcbPolyRing, ::ComplexMat, ::Int64) at /home/runner/work/AbstractAlgebra.jl/AbstractAlgebra.jl/oscar-dev/Nemo/src/arb/ComplexMat.jl:521
    charpoly(::PolyRing{T}, ::MatrixElem{T}) where T<:RingElement at /home/runner/work/AbstractAlgebra.jl/AbstractAlgebra.jl/src/Matrix.jl:4318

```

This also is broken in CI for our pull requests, see e.g. PR #1536 by @ThomasBreuer 

But it also breaks the AbstractAlgebra "Oscar CI" tests, see e.g. https://github.com/Nemocas/AbstractAlgebra.jl/actions/runs/6220341297/job/16880225156

According to `git bisect` the regression was introduced by 1da1aeaaf6ced3ffda5abb7dc985d3757f5fa3b5 resp. PR #1531 by @lgoettgens

**Comment by thofma** [comment]
@lgoettgens Are you looking at this? If not, I can have a look

**Comment by lgoettgens** [comment]
I am on the IRTG seminar this week, so no plan how much time I have. But I have some ideas I would like to test before you invest too much time into this. I'd say I either have a fix ot have tried my ideas and ping you to dig deeper, at latest tomorrow.

**Comment by lgoettgens** [comment]
That was easier than expected to find. #1538 fixes the code piece in https://github.com/Nemocas/Nemo.jl/issues/1537#issue-1900682083. Let's see if CI succeeds.
