### ISSUE TITLE
MethodError: no method matching length(::Nemo.fmpq)

### ISSUE THREAD

**Issue by OpenLibMathSeq** [Nemocas/Nemo.jl#154]
Please consider the following snippet which throws an  

    MethodError: no method matching length(::Nemo.fmpq).

Is this an error or do I use things incorrectly?

    using Nemo
    function qq()
        println("--- julia-rat")
        F = [1//1]
        println(typeof(F[1]))
        println(typeof(F))
        for i in 1:6 append!(F, F[i]*i) end
        println(F)
    end

    function nqq()
        println("--- nemo-rat")
        # F = [QQ(1,1)]
        F = [fmpq(1,1)]
        println(typeof(F[1]))
        println(typeof(F))
        for i in 1:6 append!(F, F[i]*i) end
        println(F)
    end

    qq()
    nqq()

**Comment by thofma** [comment]
You want `push!(F, F[i]*i)` instead of `append!(F, F[i]*i)`. The function `append!` is for appending arrays to arrays. In julia numbers can be treated like collections:
```
julia> for i in 2 println(i) end
2
```                              
That's why your function `qq` works. Nemo element types cannot  be treated as collections.

**Comment by OpenLibMathSeq** [comment]
Thanks!
