### ISSUE TITLE
Missing operations on Vector{QQFieldElem} and Vector{ZZRingElem}

### ISSUE THREAD

**Issue by YueRen** [Nemocas/Nemo.jl#1555]
Would it be fine to add the following operations (probably to `flint/fmpq.jl`)?  This is just for the sake of a beginner OSCAR user, the initiated know that `.*` and `.*=` exist.

Division
* `/(::Vector{QQFieldElem}, ::QQFieldElem)`
* `/(::Vector{QQFieldElem}, ::ZZRingElem)`

Multiplication
* `*(::Vector{QQFieldElem}, ::ZZRingElem)`
* `*(::ZZRingElem, ::Vector{QQFieldElem})`

The operations above work if the scalar is `Int` or `Rational` thanks to generic implementations in `Base/arraymath.jl`:
```
julia> @which QQ.([0,0,0])*1//1
*(A::AbstractArray, B::Number)
     @ Base arraymath.jl:24
```

**Comment by thofma** [comment]
I guess we can have this for consistency.

**Comment by fingolfin** [comment]
@YueRen sounds good to me. If someone provides a PR, I'd be happy to merge it.

**Comment by lgoettgens** [comment]
Closed by https://github.com/Nemocas/Nemo.jl/pull/1559
