### ISSUE TITLE
has/will nemo be merged with Flint3?

### ISSUE THREAD

**Issue by ultravioletcatastrophe** [Nemocas/Nemo.jl#1561]
title basically. is this now just a wrapper for flint? it's somewhat unclear

**Comment by fingolfin** [comment]
No, it is not just a wrapper for Flint. And it certainly won't be merged with Flint in any version, as Flint is a C-only project. And Flint3 really changes nothing of relevance when it comes to Nemo; it mainly merges various other libraries which we were also using (Arb, Calcium).

**Comment by ultravioletcatastrophe** [comment]
sorry, I'm a little confused. older documentation implies that Nemo is more than a wrapper while here it says that Nemo is "more or less just a wrapper" (http://nemocas.github.io/Nemo.jl/latest/developer/introduction/). by "merged" i meant if it's a wrapper, will the backend be upgraded to flint3. but it seems like nemo already wraps these other libraries. I am just somewhat confused about the status of this project as it seems like the pure julia components were spun off into AbstractAlgebra.jl. If Nemo is a Flint + others wrapper, why are the benchmarks in https://arxiv.org/pdf/1705.06134.pdf so much worse for Nemo? Sorry if this sounds rude, I'm just reading a lot of conflicting info.
