### ISSUE TITLE
Copying matrices via .= fails 

### ISSUE THREAD

**Issue by LukasKuehne** [Nemocas/Nemo.jl#1565]
I tried copying the entries of a Nemo matrix using the `.=` operator:
```
julia> a1 = matrix(GF(2),ones(Int,3,4))
[1   1   1   1]
[1   1   1   1]
[1   1   1   1]

julia> a2 = matrix(GF(2),zeros(Int,3,4))
[0   0   0   0]
[0   0   0   0]
[0   0   0   0]

julia> a1 .= a2
ERROR: MethodError: no method matching ndims(::Type{fpMatrix})
```
Is this intended? Or could that be fixed easily by providing this 'ndims' method?
Thanks in advance.

**Comment by thofma** [comment]
We could implement `ndims`, but this will not solve the problem. We need to implement much more to support the broadcasting operations (this is what julia calls these `.=`, `.+` etc methods). Would be definitely nice to have it, but it is quite some work. In the meantime, you could do `map!(identity, a1, a2)`, which will do the same (of course it does not look as nice).

**Comment by LukasKuehne** [comment]
Thank you very much for your quick and helpful response. Yes, that works perfectly for now. :)
