### ISSUE TITLE
Remove dependency of `Arb_jll`, `Antic_jll` and `Calcium_jll`, and upgrade `FLINT_jll`

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#1567]
Cannot seem to find an issue related to this, but there seems to be a new version `FLINT_jll` which Nemo isn't using. With this, both the dependency of `Arb_jll`, `Antic_jll` and `Calcium_jll` can be removed.

**Comment by fingolfin** [comment]
This has been completed now, I believe, thanks to work by @thofma and @albinahlback
