### ISSUE TITLE
Precompilation error in Nemo

### ISSUE THREAD

**Issue by sumiya11** [Nemocas/Nemo.jl#1595]
Hi! Just in case it can be useful, I have the following Nemo-related error in my CI:

https://github.com/sumiya11/Groebner.jl/actions/runs/7160573843/job/19495105706#step:5:263

I will try to reproduce it locally..

**Comment by thofma** [comment]
I think you are doing something non-standard (aka illegal) with the versions: You install
```
 [c3fe647b] + AbstractAlgebra v0.34.5
  [6b79fd1a] + GitHubActions v0.1.7
  [2edaba10] + Nemo v0.38.2
```
(at the top).
Later it says
```
Start benchmarking..
Benchmarking Groebner.jl, stable
  dir_stable = "/home/runner/work/Groebner.jl/Groebner.jl/benchmark/CI-scripts/run-on-stable"
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed BenchmarkTools ── v1.4.0
   Installed AbstractAlgebra ─ v0.33.0
   Installed Groebner ──────── v0.5.0
```
and it fails to load Nemo with
```
     Deleted no artifacts, repos, packages or scratchspaces
ERROR: LoadError: UndefVarError: `solve_tril!` not defined
Stacktrace:
  [1] getproperty(x::Module, f::Symbol)
    @ Base ./Base.jl:31
  [2] top-level scope
    @ ~/.julia/packages/Nemo/WXI3d/src/flint/fmpz_mat.jl:1588
```
but `WXI3d` is verison 0.38.2, which requires AbstractAlgebra 0.34.5

**Comment by sumiya11** [comment]
Indeed, the issue disappeared once I changed the way I install the packages, thanks for the pointer !
