### ISSUE TITLE
Centralize import/export statements?

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/Nemo.jl#1601]
For Oscar we by now have a single file for imports resp. exports. Maybe time to also do this in Nemo (and AA etc.)?

CC @lgoettgens @thofma @fieker

**Comment by lgoettgens** [comment]
I would be in favor of this and have the capacity to tackle this in the next few days.

**Comment by fieker** [comment]
If it makes you happy....

I generally avoid changing working code....
