### ISSUE TITLE
Question about using

### ISSUE THREAD

**Issue by lesobrod** [Nemocas/Nemo.jl#1613]
Hello! I need to find roots of s.c. 0,1 - polynomials with high degrees many times.
More exactly I need just number of real roots, [see detailed here](https://math.stackexchange.com/questions/4839115/number-of-real-roots-of-0-1-polynomial).
How can I use your package most efficiently for it?

**Comment by thofma** [comment]
Here is one way to do it;

```julia
julia> using Nemo

julia> Zx, x = ZZ["x"];

julia> num_roots(f) = sum(signature(g)[1] for (g, e) in factor_squarefree(f); init = 0);

julia> num_roots(x^10 + x^9 + x^7 + x^4 + x^2 + x)
4
```

Now we compute the maximal number of roots of all $0$-$1$ polynomials of degree $\leq 19$ and $\leq 20$ respectively:

```
julia> fmax = 0*x; maxroots = 0; for c in Iterators.product([0:1 for i in 1:19]...)
         f = Zx(collect(c)); if is_zero(f); continue; end
         vf = num_roots(f)
         if vf > maxroots
           fmax = f
           maxroots = vf
         end
       end; @show maxroots
maxroots = 4
4

julia> fmax = 0*x; maxroots = 0; for c in Iterators.product([0:1 for i in 1:20]...)
         f = Zx(collect(c)); if is_zero(f); continue; end
         vf = num_roots(f)
         if vf > maxroots
           fmax = f
           maxroots = vf
         end
       end; @show maxroots
maxroots = 5
5
```

This shows that $nu(5) = 19$. If `nu(6)` really is $42$, you will have a hard time proving it with this naive ansatz, since there are too many polynomials to check. But you can probably compute the maximal number of roots for $0$-$1$ polynomials of degree 24.

**Comment by lesobrod** [comment]
Wow, thank you very much!!
Yes, with brute-force and your package I will be able to advance further, but I need filtering methods to not look for the roots of all polynomials.
Looks like desired ones have _minimal absolute value in [-1, 0] interval,_  
like 0,1-polynomial approximation of y = 0 for -1<x<0.
Have your package approximation instruments?

**Comment by thofma** [comment]
Hm, not sure what you exactly mean with approximation, but we don't have tools for numerical investigation.

P.S.:
```julia
julia> fmax = 0*x; maxroots = 0; for c in Iterators.product([0:1 for i in 1:25]...)
         f = Zx(collect(c)); if is_zero(f); continue; end
         vf = num_roots(f)
         if vf > maxroots
           fmax = f
           maxroots = vf
         end
       end; @show maxroots
maxroots = 5
5
```
This shows that $\nu(6) > 24$.

**Comment by lesobrod** [comment]
Thank you very much! The main discussion now [here](https://mathoverflow.net/questions/461631/number-of-real-roots-of-0-1-polynomial), I mentioned your help (^_^).  
So for now $24 \lt \nu(6) \le 38$  and if you'll find something new please post here or there!

**Comment by thofma** [comment]
Thanks for the update. I will follow the discussion over at stackexchange.
