### ISSUE TITLE
Neccessity of function calls for setters and getters

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#1616]
In FLINT, we have functions such as
```c
slong fq_nmod_ctx_degree(const fq_nmod_ctx_t ctx)
{
    return ctx->modulus->length - 1;
}
```
and
```c
void fmpq_numerator(fmpz_t n, const fmpq_t q)
{
   fmpz_set(n, fmpq_numref(q));
}
```
where the first function returns the degree of a finite field and the second function sets `n` to be the numerator of `q`. 

My question is, why rely on such C calls? As the structs are already set in `flint/FlintTypes.jl`, why not do something like
```julia
function numerator(a::QQFieldElem)
   z = ZZRingElem()
   ccall((:fmpz_set, libflint), Nothing, (Ref{ZZRingElem}, Ref{ZZRingElem}), z, a.num)
   return z
end
```
instead of
```julia
function numerator(a::QQFieldElem)
   z = ZZRingElem()
   ccall((:fmpq_numerator, libflint), Nothing, (Ref{ZZRingElem}, Ref{QQFieldElem}), z, a)
   return z
end
```
and something similar for `fq_nmod_ctx_degree`?

This would result in less C calls (for example, the Julia function for `fq_nmod_ctx_degree` could have zero C calls), and Julia could perhaps optimize things more.

I understand that the current solution somewhat lowers the complexity of all Julia functions by simply relying on some symbol in FLINT, which means that Nemo has a bijection between functions for FLINT in Julia and the symbols in the FLINT binary. Moreover, internal changes in representations or how functions work in FLINT would probably result in a change of the C functions you call, so this would be easier. However, at the same time it (minimally, but still) increases the binary size of FLINT and requires FLINT to have and maintain symbols in our library that are typically inlined (or have an inline-version) -- those using C will never touch these symbols.

Would you be open to replacing such function calls? I would be open to making a PR in that case.

**Comment by thofma** [comment]
This is very brittle because of the GC, which your snippet exemplifies.
```
function numerator(a::QQFieldElem)
   z = ZZRingElem()
   ccall((:fmpz_set, libflint), Nothing, (Ref{ZZRingElem}, Ref{ZZRingElem}), z, a.num)
   return z
end
```
This is wrong. There need to be some GC guards to not make this wrong. This is all very brittle and and makes everything much more difficult to maintain.

What exactly is the problem with binary size?

**Comment by albinahlback** [comment]
> This is very brittle because of the GC, which your snippet exemplifies.
> 
> ```
> function numerator(a::QQFieldElem)
>    z = ZZRingElem()
>    ccall((:fmpz_set, libflint), Nothing, (Ref{ZZRingElem}, Ref{ZZRingElem}), z, a.num)
>    return z
> end
> ```
> 
> This is wrong. There need to be some GC guards to not make this wrong. This is all very brittle and and makes everything much more difficult to maintain.

I understand, thanks for the explanation.

> What exactly is the problem with binary size?

Nothing important. Our binaries are pretty large, but I mainly focus on removing unused/unnecessary functions/symbols to reduce "bloat".
