### ISSUE TITLE
Structs within structs

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#1617]
Why does Nemo not use other structs within structs? For instance, why is `QQFieldElem` defined as
```julia
mutable struct QQFieldElem <: FracElem{ZZRingElem}
   num::Int
   den::Int
```
and not
```julia
mutable struct QQFieldElem <: FracElem{ZZRingElem}
   num::ZZRingElem
   den::ZZRingElem
```
Does this has to do with optimizations within Julia?

Edit: The question is related to #1616

**Comment by thofma** [comment]
Because then the are not compatible with `ccall`. See https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/#Struct-Type-Correspondences.

**Comment by albinahlback** [comment]
Alright, thanks!
