### ISSUE TITLE
Weird `finite_field` dispatch

### ISSUE THREAD

**Issue by lgoettgens** [Nemocas/Nemo.jl#1623]
```julia
julia> F = GF(2,2)
Finite field of characteristic 2 of degree 2

julia> F2 = finite_field(F, 10)
Finite field of characteristic 2 of degree 10
```

I would rather expect the second one to construct a degree 10 extension over `F` instead of over $\mathbb{F}_2$.
This is due to this dispatch: https://github.com/lgoettgens/Nemo.jl/blob/1654ffbfe244b58165574070f27c54c9e6c5db6e/src/flint/fq_default.jl#L943

**Comment by fingolfin** [comment]
yes I agree, to me this looks like a bug, maybe? Let's ask @thofma as he did the overhaul, and perhaps he can clarify if this is an accident or perhaps intentional in a way we don't yet understand?

**Comment by thofma** [comment]
Let's remove it.
