### ISSUE TITLE
Error: could not find function in library libflint

### ISSUE THREAD

**Issue by OpenLibMathSeq** [Nemocas/Nemo.jl#171]
Please have a look at this test run:

    https://ci.appveyor.com/project/OpenLibMathSeq/intseq/build/job/w7d8uvspn4t6jlw3

It has an ErrorException: 

    ccall: could not find function fmpz_factor_get_fmpz in library libflint

(Note in passing that their is also a discrepancy in the printed Nemo version (0.6.0 instead of 0.6.1)).

**Comment by wbhart** [comment]
The function is defined in fmpz_factor/inlines.c.

At a guess, tying flint to a certain commit wasn't a good idea for us.

**Comment by OpenLibMathSeq** [comment]
The same module runs successful on Linux and Apple with Julia 0.5.2. Looks like a Windows-32 regression.

**Comment by wbhart** [comment]
Ok, thanks for the info. Possibly the dlls have not been correctly updated.
We'll look into that.

**Comment by thofma** [comment]
Yes, I never updated the Windows 32 bit binaries. I think I never got them to built.

**Comment by thofma** [comment]
Is Windows 32 bit support important?

**Comment by OpenLibMathSeq** [comment]
I'm surprised that Nemo still supports W32. I personally think it is obsolete and would not regret it if it would be dropped.

**Comment by OpenLibMathSeq** [comment]
wbhart> The function is defined in fmpz_factor/inlines.c.

In some other test on AppVeyor I just saw:

    INFO: Building Nemo
    configure: WARNING: mpir.h doesnt recognise compiler "inline", inlines will be unavailable

So perhaps this is the reason.

**Comment by thofma** [comment]
No, that is unrelated.

I just looked at the dll's. The Windows 32 one is from October 2016, but the function was added January 2017. It is definitely not contained in the binary.

**Comment by thofma** [comment]
Don't think so.

**Comment by tkelman** [comment]
win32 julia is used about a third to half as often as win64, from the last numbers I saw

**Comment by tkelman** [comment]
it's also currently the easiest 32-bit platform to test against in case you have 32-bit-int bugs anywhere, which you'd also see on 32 bit ARM or i686 Linux (though the latter is very rarely used)

**Comment by thofma** [comment]
We will think of something.

**Comment by tkelman** [comment]
Not super critical, just useful to cover if you can. How are you compiling things? Maybe if you're trying to use the obsolete mingw.org i686-pc-mingw32-gcc compiler vs the better mingw-w64 32 bit i686-w64-mingw32-gcc, that could be part of the problem? (yeah these names are awfully confusing)

**Comment by thofma** [comment]
It has been a while and I don't quite remember the problem. I have to check when I have access to the machine again.

**Comment by tkelman** [comment]
could try cross-compiling from linux, if everything uses autotools then it's not too hard, configure with `--host=i686-w64-mingw32`
