### ISSUE TITLE
Faster `is_zero_row` for Nemo matrices

### ISSUE THREAD

**Issue by lgoettgens** [Nemocas/Nemo.jl#1805]
the point is that is_zero_row for ZZ should be done via
 - get the pointer of the row (no c-call!)
 - check if the entries are binary zero (no c-call)
Currently it uses 2 c-calls per entry hence the generic is fine.
The same logic would apply also to Z/nZ, small or large and possible Native.GF(p)

_Originally posted by @fieker in https://github.com/Nemocas/Nemo.jl/issues/1801#issuecomment-2191295771_

**Comment by fingolfin** [comment]
Here are some steps towards that:

1. Replace `ccall`s in `mat_entry_ptr` methods with direct pointer computations, e.g. as done in PR #1807
2. Replace `ccall`s in various test functions with more direct access, e.g. as done in PR #1808 -- another e.g. also `is_zero` etc. for `QQFieldElem` could be im

My two PRs mark the way, but similar techniques should be applied to many other flint wrappers. Perhaps @aaruni96 can work on that after the Begehung (we'll talk about it when he's back in Kaiserslautern)

**Comment by fingolfin** [comment]
With https://github.com/Nemocas/AbstractAlgebra.jl/pull/1802 added to the mix, I really think we can close this.
