### ISSUE TITLE
ERROR: UndefVarError: fmpz_mat not defined

### ISSUE THREAD

**Issue by vmmhep** [Nemocas/Nemo.jl#1815]
I'm just refreshing an old package and it won't compile because of this function:
```
julia> using Nemo
Welcome to Nemo version 0.45.6

Nemo comes with absolutely no warranty whatsoever

julia> function Base.convert(::Type{Matrix{Int}}, x::Nemo.fmpz_mat)
           m,n = size(x)
           mat = Int[x[i,j] for i = 1:m, j = 1:n]
           return mat
       end
ERROR: UndefVarError: fmpz_mat not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ REPL[2]:1
```
I couldn't find any issues etc or anything in the changelogs that shows `fmpz_mat` has been removed/renamed... If someone could point me at the note I've obviously overlooked, I would greatly appreciate it!

**Comment by fingolfin** [comment]
`fmpz_mat` was renamed to `ZZMatrix` in February 2023 at which point the old name was marked as deprecated, with the change first released in v0.33.0 . The old deprecated name was then removed one year later in February 2024, with the change first released in v0.42.0.

A table of the renamings can be found e.g. here: https://github.com/oscar-system/Oscar.jl/wiki/The-Big-Renaming

Or look at the commit 5c6b16fad016068fb8aea0c04de9b31d5d03a9ee

**Comment by vmmhep** [comment]
Thanks so much!  This refresh is gonna take longer than I thought then :|

**Comment by fingolfin** [comment]
There is a shell script on that wiki page that can do most of the renaming for you.

if you can't find a new name, feel free to ask.
