### ISSUE TITLE
Add random generation functions

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#182]
Here is some code to get things going:

```
import Base:rand
using Nemo

rand(R::FlintIntegerRing, r::UnitRange{Int}) = R(rand(r))

function rand{T <: RingElem}(M::MatSpace{T}, vs...)
   m = M()
   for i = 1:M.rows
      for j = 1:M.cols
         m[i, j] = rand(base_ring(M), vs...)
      end
   end
   return m
end

function rand{T <: RingElem}(R::PolyRing{T}, n::Int, vs...)
   x = gen(R)
   f = R()
   for i = 0:n
      f += rand(base_ring(R), vs...)*x^i
   end
   return f
end

function rand{T <: RingElem}(R::ResRing{T}, vs...)
   return R(rand(vs...))
end

function rand(R::ResRing{fmpz})
   m = convert(Int, R.modulus)
   return R(rand(0:m - 1))
end
```
It can be used as follows:

```
R, x = PolynomialRing(ZZ, "x")
M = MatrixSpace(R, 10, 10)

m1 = rand(M, 2, -5:5)

S = ResidueRing(ZZ, 3)
T, y = PolynomialRing(S, "y")
N = MatrixSpace(T, 10, 10)

m2 = rand(N, 2, 0:2)
m3 = rand(N, 2)
```

We need to add rand functions for all leaf types (ZZ, padic, fq, fq_nmod, arb, acb, nf_elem) and then for all generic types (FracField, PolyRing, MPolyRing, ResRing, AbsSeriesRing, ResSeriesRing).

I suggest we start with ranges of the form Int:Int for now, and leave ZZ:ZZ for a future incarnation (unfortunately Julia doesn't allow overloading of the relevant functions for types not belonging to Real, so we have to duplicate a lot of the range/colon code for Nemo.)

**Comment by thofma** [comment]
I think we have some code in Hecke for the `ZZ:ZZ` buisness.
