### ISSUE TITLE
Issue with "Go to latest documentation" 

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/Nemo.jl#1820]
The new links added by @lgoettgens (thanks!) mostly work great but in a few of the oldest version they are broken:
- http://nemocas.github.io/Nemo.jl/v0.6/ links to http://nemocas.github.io/stable instead of <http://nemocas.github.io/Nemo.jl/stable>
- http://nemocas.github.io/Nemo.jl/v0.5/ same

Hopefully we can just fix this with a global search and replace or so.

**Comment by lgoettgens** [comment]
Resolved in https://github.com/Nemocas/Nemo.jl/pull/1822
