### ISSUE TITLE
Problems building Nemo 0.6.2 in OSX

### ISSUE THREAD

**Issue by lbenet** [Nemocas/Nemo.jl#183]
I am having problems to build Nemo in OSX, both using Julia 0.5.2 or 0.6.0-rc2. 

The final output of `Pkg.build("Nemo")` is the following:
```julia
tmp-mul_1.s:144:no such instruction: `mulx 24(%rsi), %rbx,%rax'
make[2]: *** [mul_1.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -D__GMP_WITHIN_GMP -I.. -DOPERATION_preinv_mod_1 -m64 -O2 -march=corei7 -mtune=corei7-avx -c preinv_mod_1.c  -fno-common -DPIC -o .libs/preinv_mod_1.o
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
I did not get any further by doing `julia build.jl` in `deps/`. I think the problem is related to mpir-3.0.0.

Any ideas or suggestions?

**Comment by wbhart** [comment]
Did you do Pkg.rm("Nemo") first?

If that doesn't work, there's probably an issue with your machine not
supporting the new Intel instructions, which means it's being incorrectly
detected.

Can you go into .julia/v0.5/Nemo/deps/mpir-3.0.0 and run

./config.guess

and tell us the output, and then give us the output of

cat /proc/cpuinfo

or whatever the equivalent is on a Mac.

**Comment by lbenet** [comment]
Thanks for the reply. 

I just did the `Pkg.rm("Nemo")`, `Pkg.add("Nemo")` (and `Pkg.buil("Nemo")` in Julia 0.5, since in Julia0.6 seems to be automatic). In both cases it stops with an error message of the form:

```julia
hgcd2.c:38:no such instruction: `lzcnt %rdi, %rax'
hgcd2.c:38:no such instruction: `lzcnt %rdx, %rcx'
make[2]: *** [hgcd2.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

> Can you go into .julia/v0.5/Nemo/deps/mpir-3.0.0 and run `./config.guess`

haswell-apple-darwin13.4.0

> and tell us the output, and then give us the output of `cat /proc/cpuinfo` or whatever the equivalent is on a Mac.

$ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz

**Comment by thofma** [comment]
Looks like a problem with MPIR. As a dirty workaround, you can replace every `mpir-3.0.0` with `mpir-2.7.2` in `Nemo/deps/build.jl`.

**Comment by wbhart** [comment]
It turns out the CPU is being detected correctly. In fact, the C compiler
is generating invalid instructions for your CPU.

This is probably due to the wrong compiler flags being used. In order to
diagnose further, I need a copy of

.julia/v0.5/Nemo/deps/mpir-3.0.0/config.log

**Comment by wbhart** [comment]
Actually, I'm simply wrong. Haswell supports BMI and BMI2 instructions,
which is what the assembler is complaining about here.

Unfortunately, your assembler is broken. This is something we can't fix.
You have to update your assembler (gas) for your platform, if you wish to
use MPIR-3.0.0. Of course MPIR-2.7.2 doesn't use BMI or BMI2 instructions,
so it will continue to work with the out-of-date assembler.

On Linux, gas is part of binutils, so you probably need to look up how to
update this for the Mac.

**Comment by lbenet** [comment]
I haven't found anything reliable to update the assembler for the mac, so for the time being, I went back to v0.5.2, and rebuild from scratch. That works.

Thanks a lot!

**Comment by wbhart** [comment]
Unfortunately, none of us are Mac experts. You could file a ticket on the
MPIR website (which I will see, since I am the maintainer) and see if any
Mac experts respond.

Don't forget to include the version of OSX, XCode and/or Homebrew you are
using.

**Comment by lbenet** [comment]
In https://github.com/wbhart/mpir/issues/217 it was suggested to `export CFLAGS="-Wa,-q $CFLAGS"`, which allows to build MPIR-3.0.0. 

The question is, where should I include this in the building process of Nemo?

**Comment by wbhart** [comment]
I'm not 100% sure, but I think if you type that before you start Julia,
that might be enough.

If not, you can set environment variables in .julia/v0.5/Nemo/deps/build.jl
around line 110-116 with a withenv block (see line 215 for an example).

Be careful that $ is string interpolation in Julia, so if you want to
include the existing CFLAGS environment variable, you need to get it first
, e.g. with

old_cflags = ENV["CFLAGS"]

Then use $old_cflags instead of $CFLAGS.

**Comment by thofma** [comment]
I guess the proper fix for Nemo is to wait for a new MPIR release which fixes this?

**Comment by wbhart** [comment]
I'm not sure we can fix it. The problem is with the out of date assembler.
Short of supplying our own toolchain, there's little we can do.

**Comment by lbenet** [comment]
@wbhart Thanks for the suggestion. It did work to have the `CFLAGS` exported before starting Julia, though I got a really long list of warnings from clang. 

Thanks for all the help!

**Comment by wbhart** [comment]
That's pretty standard. Clang complains a lot!

**Comment by isuruf** [comment]
You can add
```
if is_apple() && !("CC" in keys(ENV))
    ENV["CC"] = "clang"
    ENV["CXX"] = "clang++"
end
```
to the top of `build.jl`

**Comment by thofma** [comment]
Thanks @isuruf. We will probably do that.

**Comment by thofma** [comment]
@isuruf Will this work for all recent OSX versions?

**Comment by isuruf** [comment]
Yes. `GAS` is not updated anymore in OSX while the `llvm-as` assembler is. If `llvm-as` is out-of-date, `GAS` probably is too.
