### ISSUE TITLE
Is Nemo.jl compatible with LGPL v3 ?

### ISSUE THREAD

**Issue by sumiya11** [Nemocas/Nemo.jl#1836]
Hi,

For context, I would like to link with Flint for its fast polynomial arithmetic in a closed-source commercial library in Julia.
Flint is distributed under LGPL v3, so I would need to wrap Flint in Julia in an LGPL v3 compatible way.

According to https://github.com/Nemocas/Nemo.jl/blob/master/LICENSE.md, Nemo.jl is "almost" compatible with LGPL v3, except for the ANTIC and Pari libraries which it may link to. However, from a quick scan of the source code, I did not see any use of ANTIC or Pari in Nemo.jl (?). 

So I have two questions:
- Is Nemo.jl Julia source code is compatible with LGPL v3+ ?
- Does Nemo.jl only links to LGPL v3+ compatible libraries ?

Thank you.

**Comment by thofma** [comment]
Nowadays, Nemo calls into libmpfr, libgmp and libflint. On the other hand, it also requires the julia runtime, which has again its own dependencies.

**Comment by thofma** [comment]
See the updated LICENSE in https://github.com/Nemocas/Nemo.jl/pull/1838.

**Comment by sumiya11** [comment]
Thank you very much for the clarification.
