### ISSUE TITLE
Not working for prime fields

### ISSUE THREAD

**Issue by tasbihi** [Nemocas/Nemo.jl#1841]
While the command ```F, x = finite_field(q, "x")``` works for a non-prime field, it seems that it has a bug for a prime field. Indeed, for a non-prime field, ```x``` is a (correct) primitive element of ```F```. However, if ```q``` is prime, then ```x``` is always ```0``` (not the primitive element of the field!)

**Comment by tasbihi** [comment]
For example, for a non-prime field we have

    julia> F, x = finite_field(9,"x");

    julia> x^2
    x + 1

which is correct. However, for a prime field we have 

    julia> F, x = finite_field(5,"x");

    julia> x
    0

which is wrong!

**Comment by thofma** [comment]
The second element is not guaranteed to return a primitive element.  Indeed, the documentation for `finite_field` refers to `gen(K)`, which says:
```
help?> gen(K)
  gen(L::FqField)

  Return a K-algebra generator `a` of the finite field L, where K is the base field of L. The element `a` satisfies `defining_polyomial(L)(a) == 0`.

  Note that this is in general not a multiplicative generator and can be zero, if L/K is an extension of degree one.
```
