### ISSUE TITLE
specification of `mul!`

### ISSUE THREAD

**Issue by kalmarek** [Nemocas/Nemo.jl#207]
It might sound like a silly question, but what exactly is `mul!` supposed to do? (the same explanation for `addeq!` would be appreciated as well.)
By looking at code in different places I perceive that `mul!(a, b, c)` computes `b*c`, stores the result in `a` and then returns `a`, all with the aim of saving on memory allocation.
but then I am somewhat confused by examples of [code](https://github.com/Nemocas/Nemo.jl/blob/f874685dd064e53e7f6a1797844749f92d026b2d/src/generic/Matrix.jl#L1745) like

```julia
b[i, k] = mul!(b[i, k], b[i, k], d)
```

Lets settle on simple `c = mul!(c, c, d)`. When `c` is a more complicated object (e.g. when actual multiplication `c*d` takes part in "stages" (e.g. across several loops) providing the same `c` as a "storage"
may alter the result of the next stage, and result in an incorrect result.

This is exactly the case with `backsolve!` which gave me incorrect results until I allocated another `tmp` object and replaced all of `mul!(c, c, d)` by `mul!(tmp, c, d)`

Is this a bug, or have I implemented `mul!` incorrectly?

**Comment by wbhart** [comment]
You are correct that mul! writes the result into the output. It returns the
result so that it will also work with immutable types (which can't be
directly modified).

You certainly have to be careful when using it, hence the exclamation point
in the name. You need explicit control over the object you are writing
into, which means you have to have created it yourself and know that no one
else is making use of the value you are going to modify.

You would have to point out explicit examples in the code that you are
unclear about. In cases I've used it, I believe I've done so carefully, but
perhaps someone has used it somewhere in the wrong way.

Bill.

**Comment by kalmarek** [comment]
I tried to do some computations in `MatrixSpace` over my GroupRing.
My implementation of multiplication is as follows (`pm` is cached product formula for fast lookup):
```julia
function mul!{T}(result::AbstractVector{T}, X::AbstractVector{T}, Y::AbstractVector{T}, pm::Array{Int,2})
   z = zero(T)
   for (j,y) in enumerate(Y)
      if y != z
         for (i, index) in enumerate(pm[:,j])
            if X[i] != z
               index == 0 && throw(ArgumentError("The product don't seem to belong to the span of basis!"))
               result[index] += X[i]*y
            end
         end
      end
   end
end
```
Now I can not use
```julia
function mul!{T}(result::GroupRingElem{T}, X::GroupRingElem{T}, Y::GroupRingElem{T})
   mul!(result.coeffs, X.coeffs, Y.coeffs, parent(X).pm)
   return result
end
```
because in `mul!` we loop multiple times `+=` to `result` -- I first need to zero it: `result.coeffs *= zero(T)` before `mul!(result, X.coeffs,Y.coeffs, parent(X).pm)`.
But still `mul!(a,a,b)` may overwrite entries of `result` (now bound to X) in the `for` loops.

for now, just to get correct results from matrix multiplication (and I still don't trust it ;-) I allocate zeros to result before zeroing (which breaks the whole idea...)
```julia
function mul!{T}(result::GroupRingElem{T}, X::GroupRingElem{T}, Y::GroupRingElem{T})
   result = deepcopy(result)
   result.coeffs *= zero(T)
   mul!(result.coeffs, X.coeffs, Y.coeffs, parent(X).pm)
   return result
end
```

**Comment by wbhart** [comment]
Certainly the current matrix code assumes the coefficient ring of the
matrices is commutative.

Usually, if you want to do += multiple times, you would use addeq! into a
value that you zeroed and have complete control over. This is a win because
you aren't allocating a new value every time you do +. Instead, you just
allocate one value at the start and just accumulate into it.You certainly
can't use these functions to accumulate into a value you don't have control
over.

Bill.

**Comment by kalmarek** [comment]
> Certainly the current matrix code assumes the coefficient ring of the
> matrices is commutative. 
First of all that's good to know ;-) although it would be even better if written somewhere in docs;
Surprisingly I `@asserted`-checked all the relations between elementary matrices and multiplication now seems to be correct (at least on radius=8 ball).

**Comment by thofma** [comment]
Did you solve your problem?

By the way, I think we should revisit the basic matrix functions and make sure that they also work for noncommutative rings. I am mainly thinking of the various multiplications, matrix times matrix as well as matrix times scalar.

**Comment by kalmarek** [comment]
not at all; for the moment I just defined `mul!` and `addeq!` with `deepcopy`-ing the result to avoid overriding elements;
However, the non-commutativity seems to be a larger issue. 
One solution would be to add another abstract type `Group :> Ring :> CRing :> ... ` and write algorithms for `Rings` without assuming commutativity, while those (simpler/faster??) assuming commutativity should dispatch after `CRings(Elems)`.

**Comment by kalmarek** [comment]
maybe we should close this issue (which is resolved) and open a new one with non-commutative rings in the title?

**Comment by thofma** [comment]
Yes, but one final comment. I think your
```julia
function mul!{T}(result::AbstractVector{T}, X::AbstractVector{T}, Y::AbstractVector{T}, pm::Array{Int,2})
```
should zero the result, then you won't need the deepcopy later. But you should zero it inplace (with a loop) to cut down allocations.

**Comment by kalmarek** [comment]
like this?
```julia
function mul!{T}(result::AbstractVector{T}, X::AbstractVector{T}, Y::AbstractVector{T}, pm::Array{Int,2})
   z = zero(T)
   result .*= zero(T) # broadcasts 
   for (j,y) in enumerate(Y)
      if y != z
         for (i, index) in enumerate(pm[:,j])
            if X[i] != z
               index == 0 && throw(ArgumentError("The product don't seem to be supported on basis!"))
               result[index] += X[i]*y
            end
         end
      end
   end
end
```
Without `deepcopy` I still get
```julia
Nemo.setpermstyle(:cycles)
G = PermutationGroup(4)
ZG = GroupRing(G)
a = ZG(1) + ZG(G([2,3,4,1]))
b = ZG(G([1,3,4,2]))
@show a*b
@show mul!(a,a,b);
```
> `a * b = 1*(1,2,4,3) + 1*(2,3,4)`
>  `mul!(a,a,b) = 0*()`

**Comment by thofma** [comment]
Sorry, my remark cannot work. I now see the problem but I cannot see a allocation free solution. It is the same problem if you want to write a `mul!` version for matrix multiplication. Then the case `mul!(a, a, b)` is kind of tricky to get allocation free.

**Comment by kalmarek** [comment]
one thing possible would be to ask if `result === X` and only then allocate the additional array (i.e. `deepcopy(result)`. However I'm surprised to see the same amount of allocation in `@benchmark`: (`a,b,z` are random, dense elements from the group ring of `PermutationGroup(7)`)
```julia
@benchmark mul!(a,a,b)
BenchmarkTools.Trial: 
  BenchmarkTools.Trial: 
  memory estimate:  194.29 MiB
  allocs estimate:  14615
  --------------
  minimum time:     87.061 ms (7.11% GC)
  median time:      88.384 ms (7.02% GC)
  mean time:        88.363 ms (6.92% GC)
  maximum time:     94.098 ms (7.00% GC)
  --------------
  samples:          57
  evals/sample:     1
```
```julia
@benchmark mul!(z,a,b)
BenchmarkTools.Trial: 
  memory estimate:  194.25 MiB
  allocs estimate:  14609
  --------------
  minimum time:     88.508 ms (6.27% GC)
  median time:      89.524 ms (7.08% GC)
  mean time:        89.898 ms (6.95% GC)
  maximum time:     94.491 ms (6.84% GC)
  --------------
  samples:          56
  evals/sample:     1
```

**Comment by thofma** [comment]
I think `pm[:,j]` is allocating. You should use `@view` or `view.

**Comment by wbhart** [comment]
I believe view still allocates as well, (at least if there are mixed
objects inside the thing you are taking a view of)

**Comment by kalmarek** [comment]
definitely `enumerate` is allocating. At the expense of readability:
```julia
function mul!{T}(result::AbstractVector{T}, X::AbstractVector, Y::AbstractVector, pm::Array{Int,2})
   z = zero(T)
   result .= z
   for j in eachindex(Y)
      if Y[j] != z
         for i in 1:size(pm,1)
            if X[i] != z
               pm[i,j] == 0 && throw(ArgumentError("The product don't seem to be supported on basis!"))
               result[pm[i,j]] += X[i]*Y[j]
            end
         end
      end
   end
end
```
is completely allocation free; for small examples giving almost 2x speedup;
```julia
z = ZG(similar(a.coeffs))
@time w = mul!(z, a, b)
@time x = mul!(a, a, b)
@time y = a*b
@assert x == y == w == z
```
> `0.053368 seconds (4 allocations: 160 bytes)`
> `0.054371 seconds (10 allocations: 40.453 KB)`
> `0.091267 seconds (5.05 k allocations: 197.141 KB)`

(confirmed by `@benchmark`. note that `a*b` also checks that parents of `a` and `b` agree)

**Comment by thofma** [comment]
No, `enumerate` is not allocating, but `A[i, :]` is.

```julia
julia> A = rand(1:2, 2000, 2000);

julia> @time B = enumerate(view(A, 1, :));
  0.000005 seconds (6 allocations: 224 bytes)

julia> @time B = enumerate(A[1, :])
  0.000033 seconds (6 allocations: 15.922 KB)

```

**Comment by kalmarek** [comment]
I agree that creation of enumerate object does not allocate. However iterating does:
```julia
A = rand(1:2, 2000, 2000);
c = 0
@time for (i, x) in enumerate(view(A,1,:))
    c += x
end
c = 0
@time for (i, x) in enumerate(A[1,:])
    c += x
end
c = 0
@time for i in 1:size(A,2)
    c += A[1,i]
end
```
  > 0.002130 seconds (23.62 k allocations: 619.078 KB)
  0.001456 seconds (18.08 k allocations: 392.047 KB)
  0.000503 seconds (6.63 k allocations: 134.938 KB)

**Comment by thofma** [comment]
No, you have to put in a function to get proper timings. Else your benchmarks are flawed because of global variables (see https://docs.julialang.org/en/release-0.5/manual/performance-tips/).
```julia
function f()
  A = rand(1:2, 2000, 2000);
  c = 0
  @time for (i, x) in enumerate(view(A,1,:))
    c += x
  end
  c = 0
  @time for (i, x) in enumerate(A[1,:])
    c += x
  end
  c = 0
  @time for i in 1:size(A,2)
    c += A[1,i]
  end
end
```
Now
```julia
julia> f()
  0.000052 seconds (2 allocations: 64 bytes)
  0.000010 seconds (1 allocation: 15.750 KB)
  0.000002 seconds
```
The allocations look correct.

**Comment by kalmarek** [comment]
always forget about this...

**Comment by thofma** [comment]
Can we close this?
