### ISSUE TITLE
Deprecation warning in Julia v0.6

### ISSUE THREAD

**Issue by siddMahen** [Nemocas/Nemo.jl#214]
When performing some matrix arithmetic I get the following warning:

```
WARNING: `x $ y` is deprecated.  use `xor(x, y)` or `x ⊻ y` instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] $ at ./deprecated.jl:376 [inlined]
 [3] hash(::Nemo.GenMat{Nemo.fq_nmod}, ::UInt64) at /Users/siddmahen/.julia/v0.6/Nemo/src/generic/Matrix.jl:57
```

I believe the fix is easy; all occurrences of `$` should be replaced appropriately.

**Comment by thofma** [comment]
Thanks. There are quite a few other deprecation warnings, but if we fixing them means breaking Nemo for julia 0.5.

So our plan is to fix some bugs during the next weeks, make a final release which works for both julia 0.5 and 0.6 and then switch the master branch to julia 0.6, addressing all deprecation warnings.

**Comment by thofma** [comment]
Master branch is now drepecation free on 0.6.
