### ISSUE TITLE
building flint2 should not need gcc.

### ISSUE THREAD

**Issue by dimpase** [Nemocas/Nemo.jl#219]
On FreeBSD 11.0 I see the following
```
HEAD is now at 768d1aaa5... Fix for fq_poly_divides.
DONE
Building flint ...
Configuring...x86_64-FreeBSD
Testing __builtin_popcountl...no
Testing __thread...no
Testing fenv...no
FLINT was successfully configured.
make[1]: Entering directory '/usr/home/dima/.julia/v0.6/Nemo/deps/flint2'
    CC   build/printf.lo
/bin/sh: gcc: command not found
make[1]: *** [Makefile:259: build/printf.lo] Error 127
make[1]: *** Waiting for unfinished jobs....
    CC   build/fprintf.lo
/bin/sh: gcc: command not found
make[1]: *** [Makefile:259: build/fprintf.lo] Error 127
make[1]: Leaving directory '/usr/home/dima/.julia/v0.6/Nemo/deps/flint2'
make: *** [Makefile:174: library] Error 2
ERROR: LoadError: failed process: Process(`make -j4`, ProcessExited(2)) [2]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
 [3] #3 at /usr/home/dima/.julia/v0.6/Nemo/deps/build.jl:218 [inlined]
 [4] withenv(::##3#4, ::Pair{String,String}, ::Vararg{Pair{String,String},N} where N) at ./env.jl:157
 [5] include_from_node1 at ./loading.jl:569
 [6] include at ./sysimg.jl:14
 [7] process_options at ./client.jl:305
 [8] _start at ./client.jl:371
while loading /usr/home/dima/.julia/v0.6/Nemo/deps/build.jl, in expression starting on line 216
```

I did not try digging this up much: I guess it works on OSX as Xcode provides a fake `gcc` - a symlink to `clang`.  Needless to say, building `flint2` works without `gcc` command available - is it just a Julia quirk?

**Comment by wbhart** [comment]
You have to pass CC=clang to Flint's configure.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dimpase** [comment]
Shouldn't the default in `build.jl` be the `CC` used to build Julia, and not `gcc`, out of nowhere, seemingly?

**Comment by wbhart** [comment]
Ah I see, this is a Nemo ticket, not a Flint one. My mistake.

**Comment by fingolfin** [comment]
This is resolved because precompiled binaries are used these days. So could be closed

**Comment by dimpase** [comment]
it's overtly optimistic to assume that a system library is always there - and hardcoding `gcc` is still a big.

**Comment by fingolfin** [comment]
? My point was that there is no compilation being done anymore, so no C compiler is invoked. Hence this bug simply cannot appear anymore.

**Comment by dimpase** [comment]
> precompiled binaries are used these days

I read that as "may be used". Sorry for noise.
