### ISSUE TITLE
static inline is not compatible with  -ansi 

### ISSUE THREAD

**Issue by dimpase** [Nemocas/Nemo.jl#220]
on clang/FreeBSD  (with gcc being a symbolic link to clang, OSX-style) it leads to 
```
    CC   ../build/fmpz_lll/is_reduced_d_with_removal.lo
In file included from is_reduced_d_with_removal.c:14:
/usr/include/fenv.h:117:15: error: unknown type name 'inline'
__fenv_static inline int
              ^
/usr/include/fenv.h:117:22: error: expected identifier or '('
__fenv_static inline int
                     ^
...
```
Here is what Perl [does](http://grokbase.com/t/perl/perl5-changes/14bsvt9hjg/perl-git-branch-blead-updated-v5-21-6-88-gf5fdb02) for this issue.

**Comment by wbhart** [comment]
We don't use static inline, but BSD seems to.

I advise using -std=c99 on FreeBSD. This would need to changed somewhere in
Flint's configure.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dimpase** [comment]
Apparently, Nemo puts `-ansi` into `CFLAGS`. 
Without this flag things build, as well as with `-std=c99`.

**Comment by wbhart** [comment]
Flint puts it into CFLAGS during configure. We have to do a switch to -std=c99 on Windows too.

**Comment by dimpase** [comment]
OK, the following flint patch allows Nemo build on FreeBSD/clang:
```
diff --git a/configure b/configure
index 39798b3a8..02aeae683 100755
--- a/configure
+++ b/configure
@@ -612,6 +612,8 @@ if [ -z "$CFLAGS" ]; then
       CFLAGS="-O2 -funroll-loops -g -D _WIN64 $POPCNT_FLAG $ABI_FLAG $OPENMP_FLAG"
    elif [ "$MACHINE" = "mips64" ]; then
       CFLAGS="-O2 -funroll-loops -g $POPCNT_FLAG $ABI_FLAG $OPENMP_FLAG"
+   elif [ "$KERNEL" = FreeBSD ]; then
+      CFLAGS="-std=c99 -pedantic -Wall -O2 -funroll-loops -g $POPCNT_FLAG $ABI_FLAG $OPENMP_FLAG"
    else
       CFLAGS="-ansi -pedantic -Wall -O2 -funroll-loops -g $POPCNT_FLAG $ABI_FLAG $OPENMP_FLAG"
    fi
```
So this has to be fixed by a flint2 pull request, which I will do.

**Comment by wbhart** [comment]
Thanks! Look forward to the PR.

**Comment by wbhart** [comment]
Fixed in trunk.
