### ISSUE TITLE
Error in solve_rational for GenMat

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#223]
Recent travis build failed:

https://travis-ci.org/Nemocas/Nemo.jl/jobs/260163137

**Comment by wbhart** [comment]
This is very likely to be fixed when we fix all the bugs in the Poly.jl module that have shown up with all the new test code we've been writing.

Leave this open and we'll run that test for a very long time when Poly.jl is fixed (in particular the interpolation code is broken). I have seen this bug before plenty often, so it's not terribly rare, I believe.

**Comment by thofma** [comment]
Ok. I was just wondering, because I have never seen it before.

**Comment by thofma** [comment]
@wbhart You said something about bugs in the interpolation. How can I reproduce them?

**Comment by wbhart** [comment]
The test code in the poly_test branch in my repo, fails.

**Comment by thofma** [comment]
The bug is already in flint:

```julia
julia> R, x = PolynomialRing(ZZ, "x")
(Univariate Polynomial Ring in x over Integer Ring,x)

julia> f = interpolate(R, fmpz[1,2,3], fmpz[1, -4, 4])
6*x^2-23*x+18

julia> f(1)
1

julia> f(2)
-4

julia> f(3)
3
```
He calls `:fmpz_poly_interpolate_fmpz_vec`. Do you want me to open an issue at the flint repository?

**Comment by wbhart** [comment]
Yes, please open a ticket there.

I fixed the gcd bugs that I saw before. That only leaves this bug to be
fixed and poly_test can be merged into trunk.

**Comment by thofma** [comment]
The code cannot work for polynomials over rings which are not fields. The correct polynomial is `13/2*x^2 - 49/2*x + 19`.

**Comment by thofma** [comment]
https://github.com/Nemocas/Nemo.jl/blob/master/src/generic/Poly.jl#L2076 should fail if the division is not exact.

**Comment by thofma** [comment]
I guess for rings we can make it fail in case the interpolated polynomial does not have coefficients in the ring. 

For fmpz_poly's it is more involved. Flint assumes that the interpolated polynomial has integer coefficients. But we have no way of checking this before the computation.

We could make flint throw an error if it encounters a non-exact division at https://github.com/wbhart/flint2/blob/trunk/fmpz_poly/interpolate_fmpz_vec.c#L37
What do you think @wbhart?

**Comment by wbhart** [comment]
I agree, we should raise an exception in both Flint and Nemo when the
division is not exact.

Of course the test code should start with an exact polynomial, evaluate it,
interpolate it, then check the result is the same. The test code is just
wrong.

**Comment by wbhart** [comment]
Fixing the interpolation code to raise an exception if it encounters an inexact division also fixes the issue in GenMat. I was able to reproduce it reliably about every 100 iterations of the final test. It now no longer occurs. We still have to fix the Flint code to raise an exception of course.

**Comment by wbhart** [comment]
I've fixed Flint so that it now raises an exception.
