### ISSUE TITLE
Add support for lattices of compatibly embedded finite fields

### ISSUE THREAD

**Issue by defeo** [Nemocas/Nemo.jl#233]
As discussed at the Hecke/Nemo/Flint workshop, there is a plan to add support for lattices of compatibly embedded finite fields to Nemo/Flint. This issue tracks progress on the subject.

There is an ongoing effort to add the basic algorithms to Flint, documented here: https://github.com/wbhart/flint2/issues/366. 

On the Nemo side, @thofma has implemented an abstract map type, that should be a good object to represent the embeddings: https://github.com/Nemocas/Nemo.jl/tree/th/map

The branch https://github.com/wbhart/flint2/pull/351 of Flint contains algorithms (only naive ones, atm) for computing and evaluating embeddings. By wrapping those in a sensible interface, we shall

- [ ] implement maps between generic finite fields in Nemo;
- [ ] store the embedding information in a lattice, taking care of maintaining compatibility;
- [ ] wrap everything in a Fp-bar type.

Eventually, as support in Flint improves, we could think of using special families of irreducible polynomials for representing Fp-bar.

**Comment by defeo** [comment]
@wbhart, do you have the pictures of the API we drafted at the blackboard?

**Comment by defeo** [comment]
Hello. I am at the [atelier PARI/GP](http://pari.math.u-bordeaux.fr/Events/PARI2018/), and [just showcased](https://github.com/defeo/Nemo-embeddings-demo) the work @erou has been doing on compatible lattices, based upon my PR [wbhart/flint2#351](https://github.com/wbhart/flint2/pull/351).

This is getting quite mature. It'd be good to start planning for the merge.

**Comment by wbhart** [comment]
That's great news.

We will have to plan it well, since Nemo is in the process of being split
into a pure Julia generic component and a component that depends on Flint.

I anticipate that to take about 2 weeks. Usually it's pretty
straightforward to see where stuff should go, and there shouldn't be a lot
of work in doing this, so don't panic.

**Comment by wbhart** [comment]
Actually, are you talking about merging the Flint stuff of both Flint and
Nemo stuff? What does @erou's work depend on?

**Comment by erou** [comment]
Hello, 
On Flint's side, it depends on @defeo 's PR. On Nemo's side, it is based on @thofma 's implementation of abstract maps. But I guess it is not crucial to have abstract maps : it is just to define embeddings as a subtype of the abstract map type.

**Comment by defeo** [comment]
Let's do step by step. My PR to Flint first. It's waiting for input.

**Comment by wbhart** [comment]
Sure. Actually, abstract maps are suddenly needed by a lot of people, so we
will have to do it soon anyway.

But I will try to review the Flint PR soon.
