### ISSUE TITLE
Warning in fmpz_mat tests

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#236]
fmpz_mat.convert...WARNING: When trying to convert a fmpz_mat to a Matrix{Int}, some elements were too large to fit the standard Int type: try to convert to a matrix of BigInt.

**Comment by thofma** [comment]
That is on purpose to test the warning.

**Comment by wbhart** [comment]
I bet it gets reported a lot.

**Comment by kalmarek** [comment]
how about using `@test_warn`?
https://github.com/JuliaLang/julia/pull/19903

**Comment by wbhart** [comment]
This is only in Julia-0.7, yes?

**Comment by kalmarek** [comment]
I have it in my `julia-0.6`

**Comment by wbhart** [comment]
Ok, then I guess we should do that then.

**Comment by wbhart** [comment]
The problem is that the test actually throws an InexactError. We currently
use @test_throws for this, but it transmutes the error into a warning,
which is then printed. I don't see how to work around this. It seems like a
bug in Julia to me.

**Comment by thofma** [comment]
The function first gives a warning and then throws an error. We cannot test both in the test. How about we only throw the error, but change it's text to the text of the warning?

**Comment by wbhart** [comment]
Sounds fair.
