### ISSUE TITLE
inv conflicts with the meaning in Julia

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#240]
It's not possible to compute the Hessenberg form of a Nemo matrix over Julia BigInts because it uses inv, which for a BigInt is defined to be a BigFloat. We should probably rename our inv to inverse.

**Comment by wbhart** [comment]
After discussing with Claus, we think Julia should be interpreted as taking inv, sqrt, exp, log, sin, cos, etc., in "the" completion. But this is meaningless for algebra, as there may be more than one completion we might be interested in. Therefore, we will define inverse, square_root, exponential, logarithm, sine, cosine, etc., which are expected to return their values in the same ring as the input, but for "convenience of the user", define catchalls, inv(x) = inverse(x), sqrt(x) = square_root(x), etc. This won't be consistent with Julia, but there's no meaningful way to make it consistent. Of course generic library code will have to call the long name functions to be consistent.

Later, when we want such functions for a given completion, one must write e.g. exp(R, n) where R is the completed ring that we want the result to lie in. The Julia people probably won't like this, since it would imply defining exp(BigFloat, BigInt), which they consider type piracy. But they haven't left us any way around this.

**Comment by thofma** [comment]
I am for it as long as we don't do the type pircay. There is no gain if we cannot new Nemo releases.

**Comment by wbhart** [comment]
Then we will have to use some name other than exp, etc., when we want the exponential for a completion, despite the fact that Julia uses exp for that. It seems like this is completely backwards to me. But if users don't want the functions renamed and they still want everything to work, there's no choice, otherwise we won't be able to write proper working test code.

**Comment by thofma** [comment]
What is the parent/ring of objects of type `BigFloat` in Nemo? Is it `BigFloat`?

**Comment by wbhart** [comment]
Actually it isn't included in the type hierarchy at the moment. I've only
included integers and rationals.

**Comment by thofma** [comment]
I don't think it will be. It seems that the interface wants the completed ring first, but this won't be `BigFloat` or `Float64`. For the same reason `BigInt` is not the ring for elements of type `BigInt`.

**Comment by wbhart** [comment]
I'm not sure I understand the question. But of course BigFloat won't be the
parent of BigFloat, if we ever add it to Nemo.

**Comment by thofma** [comment]
Then why do you write "The Julia people probably won't like this, since it would imply defining exp(BigFloat, BigInt), which they consider type piracy."? If BigFloat is not the ring, why would we want to define this?

**Comment by wbhart** [comment]
Oh I see. Now I understand your point. Thanks for clarifying. Yes, of
course you are right.

**Comment by wbhart** [comment]
Fixed a long time ago.
