### ISSUE TITLE
solve_with_det computes determinant up to sign

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#248]
Currently solve_with_det only computes the determinant up to sign. The code was copied from Flint, which did the same thing. The sign of the determinant and matrix need to be changed if the sign of the permutation used in fflu to permute the rows is odd. Note: fflu returns this permutation, and its sign can be computed efficiently as per Flint.

**Comment by thofma** [comment]
As usual, my head starts spinning when I look at the solve code. Exactly which function is doing the wrong thing?

**Comment by wbhart** [comment]
The function that is wrong is 

```
solve!(A::MatElem{T}, b::MatElem{T}) where {T <: RingElement}
```
in generic/Matrix.jl. It first does a fraction free LU decomposition, then a backsolve. This is the strategy as per Flint's fmpz_mat/solve_fflu.c, fmpz_mat/find_pivot_any.c fmpz_mat/fflu.c, fmpz_mat_solve_fflu_precomp.c.

Unfortunately, someone (probably me), has removed the explicit reference to permutations, so it isn't quite trivial to do the adjustment to the determinant based on the parity of the permutation, as we now do in Flint after the call to fmpz_mat_solve_fflu_precomp in fmpz_mat/solve_fflu.

**Comment by thofma** [comment]
Now that the permutations are in generic, we can use them this function.

**Comment by wbhart** [comment]
That's true.

**Comment by thofma** [comment]
Would it make more sense, to mirror the behavior of flint here? So let `solve!` first call lufact on the matrix and then define `solve_with_lu` etc. This would also allow us to use solve with the same left side over and over again.

**Comment by wbhart** [comment]
I thought that's what it was doing already. Maybe Claus changed it? Of
course it has to continue to be fraction free or division free if it is
currently.

**Comment by thofma** [comment]
No, no one changed it. The function `solve!(A, b)` does the LU factorization on `A`, but also does some transformations in `b`. Then the result is passed to `backsolve!(A, b)`.

The computation of the LU factorization comes with manipulating `b`. This is not how it is done in flint. There you first call the LU factorization on `A` and then you do `solve_with_lu_precomp`.

**Comment by wbhart** [comment]
That's right. I combined the two things for reasons of efficiency.
