### ISSUE TITLE
Permutations may be faster with smaller integer types

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#249]
Someone just showed me some Julia code for permutations that is about 2x faster than the code we currently have in Nemo (for permutations on 1100 points).

I think the main reason is that they used UInt16 for the arrays. I wonder if it is worth parameterising permutations by an integer type. PermutationGroup could return permutations parameterised by Int by default, but there could be an optional argument specifying a smaller integer type for when we want to pack things tightly for a given problem.

What do you think of this idea @kalmarek

**Comment by kalmarek** [comment]
Sounds cool;

At the moment I'm preparing a grant application, with deadline on 15th of September; I will look into this when I'm finished, is that ok?

**Comment by wbhart** [comment]
Yeah of course. It's not urgent at all. It's just something worth trying.

**Comment by kalmarek** [comment]
So I have some time to look at the issue now;
How should I structure the performance tests?
I guess that the tests should contain creating permutations, decomposing into cycles, inverting them, rising to power. 
Do You have some specific numbers (lengths, powers etc) that need to be evaluated, like the 1100 mentioned above?

**Comment by wbhart** [comment]
I don't have any particular examples, but I think the benchmark I was
looking at was raising a permutation to a power, e.g. 1000 or something
like that.

The issue here was the cost of the basic arithmetic, since we were
essentially comparing the same algorithm. It would be enough to simply
compare the times before and after supporting smaller integers. According
to the Gap people, their Julia code was 30% faster if they used integers
half the size. Of course you need to support both sizes, which is why I
think it should be a parameter of the type.

By the way, there has been a lot of refactoring in Nemo since you last
looked. All your code has been moved into the Generic submodule. But there
are two major changes I made:

1) In three places where you were using fmpz I replaced it with BigInt,
since it is our intention to split Nemo into a Julia only generic package
and a Flint dependent package. I saw no reason to not have your code in the
Generic part, except for those three fmpz's (which are flint bignums). This
definitely slowed down some of your code substantially. It might be worth
either dealing with the case where these bignums are known to be Int's
specially, or if you decide you absolutely want to use Flint in your code,
to move your code back out of the Generic module (I'd prefer not to have to
do it if possible).

2) In the test code, you were calling Nemo.blah in a lot of places because
blah was (intentionally) not exported from Nemo, as blah was an internal
function that you still wanted to test. I basically changed this and
exported all the functions that are called from the test code. You can see
them exported and then reimported in the big long lists of exports and
imports in Nemo.jl. But I didn't know for sure which functions were
definitely internal and not intended to be called by a user. I would
recommend going back to what you originally had in cases where the
functions are definitely not intended to be called by the user. I guess you
have to do Generic.blah now to call them from the test code if you don't
export them.

Sorry for screwing those two things up, but I wanted to get it working and
wasn't 100% sure how you would deal with these two things.

Bill.

**Comment by kalmarek** [comment]
Since merge it's not my code, it's Nemos code  -- You should do with it what the direction of the development of Nemo suggests. No objections on my side. I've seen the changes when I was porting my code to v0.6 (it turned out to be slower so I abandoned the port for a moment).

1) (these four places are in YoungTabs, right?) I don't see an easy way to get around these;
Is using e.g. two different dictionaries `_charvalsTable`, `_charvalsTableBig` a solution?

2) Ok, I'd propose the following changes:
 * export `permtype`
 * i have certain doubts about `matrix_repr` for permutations (i.e. that the function should be completely removed);
 * `partitionseq` should be internal (??)
3) Is eye(G::) = G() still necessary?

Before I commit any changes I want to have a full performance testing suite, to be able to test my expectations against reality. Does Nemo have already any performance-regressions framework?

**Comment by wbhart** [comment]
On 13 October 2017 at 12:28, kalmarek <notifications@github.com> wrote:

> Since merge it's not my code, it's Nemos code -- You should do with it
> what the direction of the development of Nemo suggests. No objections on my
> side. I've seen the changes when I was porting my code to v0.6 (it turned
> out to be slower so I abandoned the port for a moment).
>
>    1.
>
>    (these four places are in YoungTabs, right?) I don't see an easy way
>    to get around these;
>    Is using e.g. two different dictionaries _charvalsTable,
>    _charvalsTableBig a solution?
>
> I'm not super familiar with the code, but it should work in theory. You
can certainly do things like Dict{Int, Sometype}() vs Dict{BigInt,
Somtype}().

>
>    1.
>    2.
>
>    Ok, I'd propose the following changes:
>
>
>    - export permtype
>    - i have certain doubts about matrix_repr for permutations (i.e. that
>    the function should be completely removed);
>    - partitionseq should be internal (??)
>
> I have only been exporting the actual types if the user needs to directly
use them in code, rather than just using values of that type constructed
some other way. But I have no objection to exporting it if you want to do
so.

Feel free to make anything you like internal.


>
>
>    1. Is eye(G::) = G() still necessary?
>
> I believe Tommy introduced a new identity_matrix function, which might be
what you are looking for. Otherwise I don't recall what the issue was here.
Perhaps Tommy can answer this.

>
>
> Before I commit any changes I want to have a full performance testing
> suite, to be able to test my expectations against reality. Does Nemo have
> already any performance-regressions framework?
>
No. We have a benchmarks directory, with a handful of benchmarks. The
timings are pretty erratic and there's a very low coverage. But benchmarks
which we publish on the webpage are in theory covered by this benchmark
suite. I check it from time to time (and complain if there have been major
regressions). Feel free to add any benchmarks you like to that directory.

**Comment by kalmarek** [comment]
Have You considered using `BenchmarkTools`? e.g.

```julia
using BenchmarkTools
function benchmark_fateman2()
   print("benchmark_fateman ... ")
   R, x = PolynomialRing(FlintZZ, "x")
   S, y = PolynomialRing(R, "y")
   T, z = PolynomialRing(S, "z")
   U, t = PolynomialRing(T, "t")

   p = (x + y + z + t + 1)^20
   
   b = @benchmark $p*($p+1)
   m = median(b)
   println(rpad(m.time, 20), rpad(m.memory, 15), rpad(m.allocs,15))
end
```
median times are usually pretty stable, though this particular benchmark gets only 4 samples (which will not be much more stable).

**Comment by wbhart** [comment]
Yeah that looks pretty good. We might use that. Thanks!

**Comment by kalmarek** [comment]
note that this will result in much longer runs: benchmark object has to be tuned, etc before it is run several times. in this case it takes ~ 12s on my laptop to run `benchmark_fateman2()`

**Comment by wbhart** [comment]
The benchmarking is run rarely, and we probably should be using benchmarks
that take less than a second (or not using benchmark tools for the
exceptions.

**Comment by thofma** [comment]
While I would like to use BenchmarkTools, I don't want to make it a requirement for Nemo. I think this is one of the reasons we don't use it at the moment.

**Comment by wbhart** [comment]
I believe this was implemented a long time ago.
