### ISSUE TITLE
Rename isnegative

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#253]
isnegative is currently very confusingly named. It is used solely to determine whether to print a minus sign or a plus sign when printing polynomials.

**Comment by wbhart** [comment]
It's only defined for arbs and acbs these days, as it is essentially obsolete.

**Comment by thofma** [comment]
I have not timed it, but probably `ispositive(x::arb)` is faster than `x > 0`?

**Comment by wbhart** [comment]
Maybe. I just realised why it is defined for arbs though, which means I can close this ticket.
