### ISSUE TITLE
Use the Julia way of bounds checking

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#271]
Currently we have our own functions for bounds checking, which apparently means we can't turn it off when bounds checking is disabled in Julia. We should use the Julia method, if possible, and ensure it is used for all Nemo matrix types.

**Comment by thofma** [comment]
If I understand https://docs.julialang.org/en/latest/devdocs/boundscheck/ correctly, we just have to sparkle `@boundscheck` around?
