### ISSUE TITLE
Matrix constructors should not call MatrixSpace

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#279]
The MatrixSpace function could be expensive/not typesafe and should really only be called by the user. This means the Matrix, hvcat and hcat functions (currently moved out to Nemo.jl) should not call MatrixSpace if at all possible.

Each matrix type should have its own inner constructor for matrices, and these should be called by the Matrix outer constructors (which will have to be separately implemented per matrix type).

**Comment by thofma** [comment]
Fixed by https://github.com/Nemocas/Nemo.jl/pull/289
