### ISSUE TITLE
Generic test code needs extensive improvement

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#283]
I've added the following notes to the generic test file Poly-tests.jl, but the same applies for all other generic test code:

```
# In general we want to test over:
#    1) Exact rings, e.g. Z
#    2) Exact fields, e.g. Q or GFp
#    3) Inexact rings, e.g. polynomials over Julia RealField, or power series over Z
#    4) Inexact fields, e.g. Julia RealField
#    5) A field of char p > 0, e.g. GF(p)
#    6) A ring of char p > 0, e.g. Z/pZ
#    7) Commutative ring, not an integral domain, e.g. Z/nZ or Z[x]/(f) reducible f
# In some cases, we may also wish to test over:
#    8) Polynomial rings, e.g. to test interpolation strategies
#    9) Fraction fields, such as Q, e.g. to test fraction free algorithms, quasidivision, etc.
# Note: only useful to distinguish rings and fields for 1/2, 3/4, 5/6 if the algos differ,
# and to test 7 if it has to be handled specially, i.e. in presence of division.
```

**Comment by wbhart** [comment]
We should also test each type of generic construction over each other type of generic.

**Comment by martinra** [comment]
In another project, I have some tests for Nemo types based on https://github.com/martinra/QuickTest.jl . I just updated QuickTest a bit to provide an interface more adjusted to what you do in the Nemo test suit. Would that be an option for you?

**Comment by wbhart** [comment]
We actually have done a significant rework of the generic test code,
recently. The matrix test code still needs some more carefully thought out
tests, but I'm relatively happy with what we have for the other modules now.

But QuickTest might still pick up some things we miss. It's hard to know,
actually.

**Comment by martinra** [comment]
You can get an impression of how that would look like at https://github.com/martinra/Nemo.jl/tree/quicktest. I've simply added a file *test/runquicktests.jl*, which you can invoke by
``
julia -L test/runquicktests.jl -e "runtests_nemo()"
``

**Comment by wbhart** [comment]
Whilst the principle of having common arithmetic tests which run over a
variety of rings is a good one, it does look like it'll need some hand
holding. There aren't random functions for every ring that take just the
ring and a size. This doesn't even seem like a good idea, especially in the
case of towers of rings.

We'll also need different sets of identities tested for different kinds of
rings. In the end, it seems to me that you end up splitting everything back
up into the specific categories that we are already testing individually.

I really am not sure if this is actually worth doing. It also looks like
there's still plenty of scope to get things wrong in the actual
infrastructure that we set up to support QuickTests for our rings, rather
than in the library itself.

I'm undecided on this. If others think this can work, we'll do it. But I
think we need some more opinions. @thoffma @fieker @fredrik-johansson, any
opinions? Is our existing testing framework good enough, or is this also
required?

**Comment by thofma** [comment]
I agree with @wbhart. Maybe at some later point, after we have decided on some random interface for (generic) rings.

**Comment by martinra** [comment]
That indeed would help very much. And if you then want to consider QuickTest, I'm happy to look into the Nemo test code more closely.
In the meantime, I hope to have an idea how to integrate a proper Haskell-style quickcheck into the testset interface.

**Comment by wbhart** [comment]
We basically have fully reworked test code now.
