### ISSUE TITLE
Bug in discriminant??

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#290]
According to the section "Product of polynomials" of the Wikipedia page for discriminant [1], our discriminant function returns the wrong answer. However, I am unable to find any error on our part, either in the implementation or in the resultant.

Does anyone else have a reference for the identities there, which don't seem to hold? Or a reference defining the discriminant in terms of the resultant?

[1] https://en.wikipedia.org/wiki/Discriminant

**Comment by thofma** [comment]
Can you post the polynomials for which this is failing?

**Comment by wbhart** [comment]
Sure, for example:

f = -3*x^3+6*x^2+x-8;
g = -5*x^3-3*x^2-10*x+3;

It also seems to fail if either of the polynomials is constant.

**Comment by wbhart** [comment]
Magma doesn't define the discriminant of constant polynomials, which is weird.

**Comment by fredrik-johansson** [comment]
In Q[x], I get:

    julia> f = -3x^3+6x^2+x-8;
    julia> g = -5x^3-3x^2-10*x+3;
    julia> discriminant(f)
    -6000
    julia> discriminant(g)
    -32951
    julia> resultant(f,g)
    -686325
    julia> discriminant(f*g)
    93127830764096250000
    julia> discriminant(f)*resultant(f,g)^2*discriminant(g)
    93127830764096250000

**Comment by wbhart** [comment]
Yeah, but that's not the identity as given on Wikipedia.

**Comment by thofma** [comment]
It is just the sign, right?

**Comment by wbhart** [comment]
Yeah, if you don't consider degree 0 polynomials, it's just the sign. I'd prefer to have a reference though to say what was correct. The definition of the sign we've also taken from the Wikipedia article.

Magma agrees with us, but both could be wrong!

**Comment by fredrik-johansson** [comment]
Perhaps the (-1)^(pq) in the Wikipedia identity should just be (-1)^(p+q) or something like that?

**Comment by wbhart** [comment]
I can't get a failure if I leave out the sign altogether!

**Comment by wbhart** [comment]
I could report it as a bug on the Sage list. That would be funny.

**Comment by wbhart** [comment]
Our disciminant agrees in sign with what Wikipedia has for degree 2, 3 and 4 polynomials, which is three of the four cases. So I'm leaning towards thinking the identity itself is wrong. I think the identity may be as Fredrik gave it.

We just need a reference.

**Comment by wbhart** [comment]
I added a citation needed to the Wikipedia article. So we should be able to close this ticket in just one or two decades.

**Comment by thofma** [comment]
In Bourbaki, Algebra, IV., section 6, Corollary 1, there is the formula without any -1. So just disc(f*g) = disc(f) * disc(g) * res(f, g)^2. They probably have a different definition of everything.

**Comment by wbhart** [comment]
Thanks, that will do nicely.

**Comment by thofma** [comment]
It is also Theorem 3.10 in here: http://www2.math.uu.se/~svante/papers/sjN5.pdf

**Comment by wbhart** [comment]
Thanks.
