### ISSUE TITLE
Some (important) fmpz_mat functions are gc unsafe

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#297]
I just realized that all setindex/getindex functions for fmpz_mat are gc unsafe:
https://github.com/Nemocas/Nemo.jl/blob/c258f66a1f53c1877333b7a93e0d47ca303b5306/src/flint/fmpz_mat.jl#L91-L120
There is no guarantee that the underlying matrix is not gc'ed after we obtained the pointer to the entry.

I think the solution is to use `Base.@gc_presevere`, which is available in the latest version of julia.

**Comment by wbhart** [comment]
This looks to be a likely candidate for why we are seeing occasional
crashes in this module.
