### ISSUE TITLE
Overload Pkg to control C libraries

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#299]
It is common that we want to apply updates to Flint or some other C library that we depend on. This usually involves navigating to the flint2 repository in the Nemo source tree, doing git stash, checking out a given branch, doing git pull, then issuing make -j4 install, then git stash apply.

This series of commands could be called from Nemo by overloading Pkg.blah, e.g. Pkg.switch("Nemo", "flint") to switch to the Flint master branch and rebuild, or Pkg.switch("Nemo", "flint", "fubar") to switch to the "fubar" branch of Flint and rebuild. The same could be done for arb and any other dependencies for which we rely on git repositories.

Alternatively, of course, we could just separate out separate Flint, Antic and Arb packages for Julia. But that relies on doing Pkg.build for those packages (and this happens automatically whenever Nemo or Hecke are built). 

[Actually, now that I think of it, we could make building of Flint, Antic and Arb separate operations for Nemo, so they don't happen automatically when you do Pkg.build("Nemo") (since this seems to happen automatically in lots of places). This would complicate things slightly for new users of Nemo, but only very marginally so.]

**Comment by thofma** [comment]
I agree that something should be done to improve the build process. In an ideal world, Pkg.build takes optional arguments, which get passed to deps/build.jl. I have seen an issue for this, but I was not able to find it.

I think at the moment the best thing to do is to wait for Pkg3 (that is, 1.0), which hopefully allows for an elegant solution to this problem.
