### ISSUE TITLE
Weak dict for caching

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#304]
A weak dictionary only stores the object if there is an external reference to it somewhere. If not, the value is garbage collected from the dict. This is a much safer approach, since it prevents memory leaks. Otherwise, every parent you ever create is cached, even when you stop using them.

**Comment by thofma** [comment]
I said this before, but this won't work, since the objects we cache are not the keys but the values. For example, you look that for a given pair `(::Symbol, ::Ring)` there exists a key in `Dict{Tuple{Symbol, Ring}, PolynomialRing}`.

**Comment by wbhart** [comment]
I wonder if we can write our own implementation of a WeakKeyDict that does the same trick for values instead of keys.

It looks like they somehow chain finalizers. I know this has special gc support, but if it works for keys, maybe it works for values.

I suppose the problem is, whereas keys are normally unique, values don't have to be. But in our case, that is the whole idea of our values. So maybe we can make it work in our case.

**Comment by fingolfin** [comment]
We have WeakKeyDict and more these days, and use them.
