### ISSUE TITLE
MPoly powering fails over Z/nZ

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#318]
Powering of multivariates uses FPS, which does exact divisions. This actually fails over Z/nZ for various n, and so we ought to catch the exception and use RMUL instead.

**Comment by fingolfin** [comment]
Can't reproduce this on current master:
```
julia> R, h = residue_ring(ZZ, 12)
(Integers modulo 12, Map: ZZ -> R)

julia> S, (x,y) = R[:x,:y]
(Multivariate polynomial ring in 2 variables over R, zzModMPolyRingElem[x, y])

julia> (x+y)^10
x^10 + 10*x^9*y + 9*x^8*y^2 + 6*x^6*y^4 + 6*x^4*y^6 + 9*x^2*y^8 + 10*x*y^9 + y^10

julia> (3x+4y)^10
9*x^10 + 4*y^10
```

This uses `nmod_mpoly_pow_ui`.

This also works and uses the generic `^(a::MPoly{T}, b::Int) where {T <: RingElement}`:
```
julia> R, h = residue_ring(ZZ, ZZ(12))
(Integers modulo 12, Map: ZZ -> R)

julia> S, (x,y) = R[:x,:y]
(Multivariate polynomial ring in 2 variables over R, AbstractAlgebra.Generic.MPoly{ZZModRingElem}[x, y])

julia> (3x+4y)^10
9*x^10 + 4*y^10
```

Perhaps there is something else going wrong but without a way to (re)produce an issue I see nothing we could do here right now. If someone has an idea feel free to re-open, or just open a new issue with details.
