### ISSUE TITLE
PowerSeries and LaurentSeries can't do exact_division with non-invertible leading coeff

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#343]
There doesn't seem to be any reason to prevent division of power series when the second series doesn't have invertible leading coefficient. We need an algorithm for it, but it should be possible to implement, so long as one can divide all the relevant coefficients by that leading coeff.

**Comment by PeterLuschny** [comment]
This seems to be exactly the point that hinders me from popularizing Nemo on OEIS very much, because such cases occur a lot there. 

I mean cases like 

       R, x = PowerSeriesRing(ZZ, 22, "x")
       G(x) =  divexact(1 - sqrt(1 - 4x), 3 - sqrt(1 - 4x)) 

which lead to the error message "Unable to invert power series".

Peter

**Comment by wbhart** [comment]
I'll have to look at this. I think it's a bug, for the example you give. Or perhaps we just never got around to implementing the correct thing here. I'm not sure. But I think this can be fixed.

**Comment by wbhart** [comment]
I have fixed this issue in AbstractAlgebra, but not in Nemo yet. It's really quite complex, as the problem exists for relative, absolute and Laurent series. Moreover, keeping the code fast is quite hard. I was able to do AbstractAlgebra in about a day's work because the algorithms there are quadratic time. The ones in Flint/Nemo are quasilinear, and at the present moment I'm not 100% sure how to fix them without altering this. But it can probably be done. I'll take a look on Monday.

**Comment by PeterLuschny** [comment]
Thank you very much for your support!

I am not sure how deep this bug really is. As an example I offer two variants of an example, the first works nicely, the second fails (in Nemo, I did not yet test the new version of AbstractAlgebra).

    """
    Return the list of coefficients of the power series s.
    """
    function Coefficients(s, len)
        R, x = PowerSeriesRing(ZZ, len+2, "x")
        ser = s(x)
        return [coeff(ser, k) for k in 0:len-1]
    end

    """
    The generating function of the large Schröder numbers.
    """
    G006318(x) = divexact(shift_right(1 - x - sqrt(1 - 6x + x^2), 1), 2)
    Coefficients(G006318, 12) |> println

    Gx006318(x) = divexact(1 - x - sqrt(1 - 6x + x^2), 2x)
    Coefficients(Gx006318, 12) |> println

Peter

**Comment by wbhart** [comment]
I should have mentioned, it is not a bug, but was intentional, since we did not have code for the general case. We merely put in some temporary code to handle the case where the second series was invertible.

It's deep because the code actually needs writing, and there are many algorithms involved, including fast divisibility testing, base case, divide and conquer and if possible newton iteration, all of which now need to abort the moment they discover that the division isn't possible.

But it is a problem I am really interested in fixing. Fortunately it should only be a problem over Z in practice.

**Comment by wbhart** [comment]
I have a version of this working now in my own Nemo installation, after significant modifications to Flint. But I have just realised that I can make it significantly faster, so will do so before making a PR for Nemo. 

The examples you give above do work though, so the new code will certainly fix the problem.

**Comment by wbhart** [comment]
We now have relatively fast division of series over Z. It's asymptotically slightly slower (by a log factor in the length of the series) in the case that the leading coefficient of the divisor is not a unit. But I don't know an algorithm that is asymptotically fast in that case.

The next version of Nemo will contain these changes.

**Comment by thofma** [comment]
Next version with all of Bill's changes is on the way: https://github.com/JuliaLang/METADATA.jl/pull/22628.
