### ISSUE TITLE
Failure in powering of relative power series

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#349]
@wbhart You have probably seen it before:
```
Generic.RelSeries.powering...Test Failed
  Expression: f == 0 && (expn == 0 && r1 == 0) || isequal(r1, r2)
ERROR: There was an error during testing
```

Here is a minimal example:
```julia
julia> R, x = PowerSeriesRing(ZZ, 10, "x")
(Univariate power series ring in x over Integer Ring, x+O(x^11))

julia> f = x^7 + O(x^10)
x^7+O(x^10)

julia> f^0
1+O(x^3)

julia> isequal(f^0, R(1))
false
```
So the problem is that `isequal(1 + O(x^3), 1 + O(x^10)) == false`. Maybe we should be using `==`?

I am just guessing here, since I don't know what the idea behind `isequal` or `==` is.

**Comment by wbhart** [comment]
No, f^0 should be 1 + O(x^10). I thought I had already fixed that, but
apparently not. I'll look into this to see what's going wrong.

**Comment by wbhart** [comment]
Yeah, the order of the if statements in ^ in RelSeries is wrong. I think
the length(a) == 0 case should come first. Then should come b == 0, then
the other cases.

The same will be true in LaurentSeries and possibly in AbsSeries too.
