### ISSUE TITLE
Citing Nemo

### ISSUE THREAD

**Issue by kalmarek** [Nemocas/Nemo.jl#356]
I am not sure this is the place to ask, but:
the reference given on [Nemocas page](http://nemocas.org/authors.html) is outdated by several hundreds of commits.

Should we cite https://www.openaire.eu/search/publication?articleId=dedup_wf_001::ef735647f0b42305ee914fb0f1e5aab8

or something else?

**Comment by thofma** [comment]
Thanks for the reminder. We should update it.

Yes, https://dl.acm.org/citation.cfm?doid=3087604.3087611 is the article you should cite.
