### ISSUE TITLE
Type piracy

### ISSUE THREAD

**Issue by ChrisRackauckas** [Nemocas/Nemo.jl#372]
https://github.com/Nemocas/Nemo.jl/compare/b497032ee63fd46ada1ba2d38bedae1f4a94242f...324f892a858442def7f22edbf6b3f3ee9e6db6ae#diff-e5a8acdede3265069ecef76db1e57671R132

These functions are type piracy since they extend the behavior of a Base function on Base types and thus can cause problems in other packages that users may use.

**Comment by thofma** [comment]
The diff is not working for me.

**Comment by ChrisRackauckas** [comment]
https://github.com/Nemocas/Nemo.jl/blob/7f0a5b0634981779dd52672f14616e9a08e175f0/src/julia/Rational.jl#L119-L138

Those and the ones for Integers as well.

**Comment by thofma** [comment]
This is `Nemo.sqrt` and not `Base.sqrt`. We do not import `sqrt` from Base.

**Comment by ChrisRackauckas** [comment]
https://github.com/Nemocas/Nemo.jl/blob/7f0a5b0634981779dd52672f14616e9a08e175f0/src/julia/Rational.jl#L119-L138

Those and the ones for Integers as well.

**Comment by ChrisRackauckas** [comment]
Oh okay. Thanks!
