### ISSUE TITLE
View is broken for generic matrices

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#380]
It seems that the most general view function is missing. Also, one of the existing view functions has an error in it. There probably should be test code for these.

**Comment by thofma** [comment]
Broken? We talked about this in detail. There is currently no view function for generic matrices.

**Comment by wbhart** [comment]
We probably should remove the generic code for view that is there. I think I got confused with Flint matrices.

**Comment by thofma** [comment]
No, it is not broken. There is no view for generic matrices.

The two functions you see are not related to this. They except abstract matrices and the methods exist so that you don't have to write it for every single flint matrix.

**Comment by wbhart** [comment]
Oh I see!
