### ISSUE TITLE
Determinant over Z[x] is much slower

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#386]
The example on the main page of the Nemo documentation for determinant over Z[x] has slowed down by a factor of 6.

I assume this is due to the interpolation fix we did. At least I don't see a faster det method at present. Perhaps we ought to look at this and make sure we haven't broken something somewhere.

The main thing I could imagine going wrong would be not calling the det method in Flint for matrices over Z.

**Comment by thofma** [comment]
Found it. Will fix it in AbstractAlgebra.jl.
