### ISSUE TITLE
Provide binary dependencies

### ISSUE THREAD

**Issue by andreasnoack** [Nemocas/Nemo.jl#396]
(Continued from https://github.com/wbhart/Nemo.jl/issues/89)

This is a really cool project but it takes forever to compile when doing a Pkg.update() so it would be great to look into the new options for shipping binary dependencies to speed things up. E.g. https://github.com/JuliaPackaging/BinaryProvider.jl but anything that could avoid the compilation. I'm on Mac, btw.

**Comment by thofma** [comment]
I already looked into BinaryBuilder.jl/BinaryProvider.jl but I did not have time to investigate it further.

**Comment by wbhart** [comment]
That looks like an interesting package. The main issue we've had so far
with similar sorts of projects has been the inflexibility of what kinds of
packages they support. They all make assumptions about how the build will
proceed and what the dependencies will be. We have dependencies that have
dependencies, and this means setting RPATH and various other nonsense. One
of our dependencies is also built as an extension module of another
dependency and compiled into the same library, and various other
complications like that.

But I will have a look to see if that package could be useful. It don't
know if it will happen soon though, as we have a very long list of things
to work on. (At some stage I will put the entire list on GitHub as tickets.)

I imagine you've seen Nemocas/AbstractAlgebra.jl, which has no C
dependencies, but offers some similar functionality, though less optimised
of course?

**Comment by andreasnoack** [comment]
It would great if you could provide this feedback to the `BinaryProvider`/`Builder` folks. I think they'd like to support use cases like yours (but this is not really my area.)

**Comment by kalmarek** [comment]
Are there still any plans for providing BB for Nemo?

**Comment by thofma** [comment]
Yes.

**Comment by wbhart** [comment]
We will have to switch Singular.jl over too as it relies on the Nemo binaries, currently. Of course we can just make it depend on the older Nemo, until that doesn't work any more.

**Comment by thofma** [comment]
Fixed by https://github.com/Nemocas/Nemo.jl/pull/564
