### ISSUE TITLE
Representation matrix bug

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#414]
I have the following failure, which I know nothing about.

nf_elem.representation_matrix...Test Failed
  Expression: Mbb == $(Expr(:typed_vcat, :QQ, :(2 -1), :(28 2)))
   Evaluated: [2 -1]
[14 1] == [2 -1]
[28 2]
ERROR: LoadError: There was an error during testing

**Comment by thofma** [comment]
I'll habe a look.

**Comment by thofma** [comment]
Which version of antic is this? Did you rebuild Nemo?

**Comment by wbhart** [comment]
No, that is probably the issue.
