### ISSUE TITLE
Promotion weirdness

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#419]
There is no promotion rule for `fmpq_mat` and `fmpz_mat`, but `FmpqMatSpace(::fmpz_mat)` is defined. This yields the following weird behavior:
```julia
julia> using Nemo
julia> a = matrix(ZZ, 1, 1, [1])
[1]

julia> b = matrix(QQ, 1, 1, [2])
[2]

julia> a * b
[2]

julia> b * a
ERROR: MethodError: no method matching (::Nemo.FmpzMatSpace)(::Nemo.fmpq_mat)
Closest candidates are:
  FmpzMatSpace(::Nemo.fmpz_mat) at /home/thofmann/.julia/v0.6/Nemo/src/flint/fmpz_mat.jl:1223
  FmpzMatSpace(::Nemo.fmpz) at /home/thofmann/.julia/v0.6/Nemo/src/flint/fmpz_mat.jl:1212
  FmpzMatSpace(::Array{Nemo.fmpz,1}) at /home/thofmann/.julia/v0.6/Nemo/src/flint/fmpz_mat.jl:1198
  ...
Stacktrace:
 [1] *(::Nemo.fmpq_mat, ::Nemo.fmpz_mat) at /home/thofmann/.julia/v0.6/AbstractAlgebra/src/Rings.jl:64

julia> Nemo.promote_rule(fmpz_mat, fmpq_mat)
Union{}
```

**Comment by wbhart** [comment]
It's not completely surprising. Currently matrices belong to RingElem, even though there is no matrix ring type. Of course, matrices are non-commutative and the generic promotion rules for AbstractAlgebra.RingElem in Rings.jl shouldn't be applied to matrices, since they are only for commutative rings.

We need to soon introduce CommutativeRing and Ring, and separate these things, and introduce MatrixAlgebra <: Ring.

Writing all the promotion rules for non-commutative rings probably won't be a lot of fun!

**Comment by thofma** [comment]
Don't know why this is related. This will always happen when there is no promote rule but `parent(x)(y)` is still defined. Has nothing to do with commutativity.

**Comment by wbhart** [comment]
Sorry, I didn't mean "generic promotion rules", I meant generic fallbacks. But even so, you are correct. The generic fallbacks do not try a*b and b*a. They preserve the order. This is purely to do with promotion_rules.

Your analysis is 100% correct. The relevant promotion rule is missing.

In fact, the only promotion rules we have for matrices appear to be for Generic.Mat's. We don't even define them for AbstractAlgebra.MatElem's.

And it's even worse than that. We don't have any promotion rules for Mat{T} and Mat{U} with promote_rule(T, U) defined, even for Generic.Mat's.

**Comment by wbhart** [comment]
On the other hand, this would probably constitute a complex coercion of the kind we agreed not to support just yet.

**Comment by wbhart** [comment]
Actually, maybe not. There's a pretty canonical coercion from Matrix{T} to Matrix{U} if there is from T to U. It's not really a complex coercion, I don't think.

**Comment by wbhart** [comment]
Seems to work nowadays.
