### ISSUE TITLE
Installation fails with build errors

### ISSUE THREAD

**Issue by siddMahen** [Nemocas/Nemo.jl#426]
A fresh installation of Nemo on a Mac running Julia v0.6.2 gives the following error during installation:

```
.
.
. previous steps of the installation, omitted for brevity
.
.
Cloning arb ...
fatal: destination path 'arb' already exists and is not an empty directory.
error: Your local changes to the following files would be overwritten by checkout:
	Makefile.subdirs
Please commit your changes or stash them before you switch branches.
Aborting
==============================================[ ERROR: Nemo ]==============================================

LoadError: failed process: Process(`git checkout 232135f35eeebb74afcea5dd7be436142bee9227`, ProcessExited(1)) [1]
while loading /Users/siddmahen/.julia/v0.6/Nemo/deps/build.jl, in expression starting on line 239

===========================================================================================================

=============================================[ BUILD ERRORS ]==============================================

WARNING: Nemo had build errors.

 - packages with build errors remain installed in /Users/siddmahen/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Nemo")`
 - build a single package by running its `deps/build.jl` script

===========================================================================================================
```

**Comment by wbhart** [comment]
The arb directory has been modified locally on your machine. I don't know if this is something you have changed, or if it is something to do with a patch that was applied by the system.

But as it is a GitHub repository, it cannot check out the new changes to Arb.

One way to fix this is to simply delete the Arb directory:

/Users/siddmahen/.julia/v0.6/Nemo/deps/arb

Of course this will also delete the changes that are there.

**Comment by thofma** [comment]
Hm, you sure this is a fresh installation? Can you try `Pkg.rm("Nemo")` and `Pkg.add("Nemo")` before manually deleting the arb directory.

**Comment by siddMahen** [comment]
@thofma Tried `Pkg.rm("Nemo")` and `Pkg.add("Nemo")`; installation fails with the same error.
@wbhart I haven't made any local modifications. I also tried navigating to the directory (/Users/siddmahen/.julia/v0.6/Nemo/deps/arb) and making sure the staging area was empty before installing from scratch, i.e. `git checkout -- the offending file`, but that fails with the same error too.

**Comment by thofma** [comment]
Strange. The log in the original post, was it the first time you tried installing Nemo? There is a `fatal: destination path 'arb' already exists and is not an empty directory.`, which should not be there if Nemo is build for the first time.

**Comment by kalmarek** [comment]
I think I've seen this one once as well. @siddMahen have You tried manually checkouting master of arb and then `Pkg.build("Nemo")`?

**Comment by wbhart** [comment]
Another possibility: the debian PIE patch is applied to the file that says it is modified. But this would imply the relevant lines in build.jl have been uncommented for some reason. Unless it is an old version of Nemo.

**Comment by wbhart** [comment]
Oh, that's what it is. The debian PIE patch is currently being applied regardless of whether it's debian, in 0.8.3. I was looking at master.

**Comment by wbhart** [comment]
@siddMahen Something you can try (I don't guarantee it will work):

Pkg.rm("Nemo")

manually remove the directory /Users/siddmahen/.julia/v0.6/Nemo

Pkg.add("Nemo")

as soon as it starts building Nemo (as opposed to checking it out), kill it and do:

Pkg.checkout("Nemo")
Pkg.build("Nemo")

None of this should be necessary of course, but we obviously have an error in the logic in the latest released version of Nemo.

**Comment by thofma** [comment]
You are right. The current version is 0.8.2 and there we apply the patch. Should be fixed once 0.8.3 is merged at METADATA https://github.com/JuliaLang/METADATA.jl/pull/14485

**Comment by siddMahen** [comment]
Deleting `/arb` does the trick. Come to think of it, I think I may have been updating from a previous version of Nemo, sorry for the confusion.

**Comment by wbhart** [comment]
No problem. Of course, this should all just work automatically. It should detect previous installs and work out what needs to be done to update. Unfortunately we just haven't gotten around to encoding that logic yet. Thanks for the report.

**Comment by thofma** [comment]
Can be worked around via #427.
