### ISSUE TITLE
Inconsistency in nullspace between Nemo and AbstractAlgebra

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#434]
In AbstractAlgebra the nullity comes first, where in Nemo it is the second return value.

I have no preference but I want to make it consistent.

**Comment by wbhart** [comment]
I agree.

Perhaps we have a precedence in the functions that return both a rank and
something else. We should perhaps make the order consistent with those?

**Comment by thofma** [comment]
The function rref returns (rank, matrix). So we should adjust nullspace accordingly?

**Comment by wbhart** [comment]
That's what I was thinking. Does that make sense for you, i.e. nullity first?
