### ISSUE TITLE
Build error when trying to install flint2

### ISSUE THREAD

**Issue by kirtsar** [Nemocas/Nemo.jl#437]
First error was "flint2: no such directory", and the second concerning "git fetch" command. I've figured out that the build in not possible until you manually install git on your computer. I believe the existence of git can be checked during the flint2 installation process with some helpful message in case of "nonexistence" of git on the computer.

**Comment by wbhart** [comment]
We will eventually use libgit, which is supplied with Julia. For now you
have to have Git and a sane build environment on your machine.

One day we will offer the option of a binary build, which will mean you
won't have to have any prerequisites.

If you want a package without C dependencies, you can try
AbstractAlgebra.jl, which is pure Julia, but still quite powerful.

**Comment by thofma** [comment]
Fixed by https://github.com/Nemocas/Nemo.jl/pull/564
