### ISSUE TITLE
Convert AbstractAlgebra.Generic.Poly{Nemo.arb} to Nemo.arb_poly

### ISSUE THREAD

**Issue by heiderich** [Nemocas/Nemo.jl#452]
Is there already a function to convert elements of type `AbstractAlgebra.Generic.Poly{Nemo.arb}` to `Nemo.arb_poly`? If not, I think this would be desirable.

**Comment by thofma** [comment]
You should not be able to construct something of type `AbstractAlgebra.Generic.Poly{Nemo.arb}` in the first place.

**Comment by heiderich** [comment]
I am able:

```
julia> K = Nemo.ArbField(64);

julia> R,x = AbstractAlgebra.Generic.PolynomialRing(K,"x");

julia> typeof(x)
AbstractAlgebra.Generic.Poly{Nemo.arb}
```

**Comment by thofma** [comment]
I don't think we should encourage the use of `AbstractAlgebra.Generic.Poly{Nemo.arb}`. Is there something that is missing for `arb_poly`?

**Comment by heiderich** [comment]
It would be nice if the conversion function proposed in https://github.com/Nemocas/AbstractAlgebra.jl/issues/131 could be defined generically. Therefore the type `AbstractAlgebra.Generic.Poly{Nemo.arb}` would be useful (same for the complex case). I guess a conversion to arb_poly will not be expensive.

**Comment by thofma** [comment]
How about converting it to whatever `PolynomialRing(base_ring(R), "x")` returns. This should use the "correct" univariate polynomial type.

**Comment by heiderich** [comment]
This returns a tuple. The first element of it is a type for a ring, not a type for a polynomial.

Again, I think it is useful to have `AbstractAlgebra.Generic.Poly{Nemo.arb}` in order to be able to write templated functions.

**Comment by thofma** [comment]
The conversion function will have to call `PolynomialRing` to construct the parent of the resulting polynomial. So if you use `PolynomialRing` instead of `AbstractAlgebra.Generic.PolynomialRing` it will pick up the correct type (`arb_poly`).

**Comment by wbhart** [comment]
This can be done using the change_base_ring function:

```
julia> using Nemo

julia> R, x = Nemo.AbstractAlgebra.Generic.PolynomialRing(K, :x)
(Univariate Polynomial Ring in x over Real Field with 64 bits of precision and error bounds, x)

julia> S, y = PolynomialRing(K, "y")
(Univariate Polynomial Ring in y over Real Field with 64 bits of precision and error bounds, y)

julia> change_base_ring(K, x; parent=S)
y
```
