### ISSUE TITLE
check_parent(::Nemo.arb, ::Nemo.arb) and check_parent(::Nemo.acb, ::Nemo.acb)

### ISSUE THREAD

**Issue by heiderich** [Nemocas/Nemo.jl#457]
`function gcd(x::T, y::T) where {T <: FieldElem}` from AbstractAlgebra calls `check_parent(x,y)`. The function `check_parent` exists for arguments of type `AbstractAlgebra.gfelem{Int64}`, but not for arguments of type`Nemo.arb` and `Nemo.acb`. Is there a special reason for this?

**Comment by thofma** [comment]
Not really, see #458
