### ISSUE TITLE
coerce AbstractArray{T<:Integer, 2} to fmpz_mat

### ISSUE THREAD

**Issue by kalmarek** [Nemocas/Nemo.jl#460]
Is there a reason why `fmpz_mat` https://github.com/Nemocas/Nemo.jl/blob/master/src/flint/FlintTypes.jl#L2512 accepts only `Array{T<:Integer,2}` (similarly for the next method with `Vector{T}`)?

Right now if I have `A::SparseMatrixCSC` and `M = MatrixSpace(Nemo.ZZ, 3,3)` I need to go through `full`:
```julia
using Nemo
M = MatrixSpace(Nemo.ZZ, 3,3)
A = spzeros(Int, 3,3)
M(full(A))
```

but looking at https://github.com/Nemocas/Nemo.jl/blob/ad6e6ac68e4960c5b166ce473109b883076956eb/src/flint/FlintTypes.jl#L2512 it seems that any matrix type which satisfies indexing should do.
I suggest changing
```julia
function fmpz_mat(r::Int, c::Int, arr::Array{T, 2}) where {T <: Integer}
```
to
```julia
function fmpz_mat(r::Int, c::Int, arr::AbstractArray{T, 2}) where {T <: Integer}
```
what do You think?
(making `M(A)` work will require one more change to AbstractAlgebra)

**Comment by wbhart** [comment]
Yes, I believe you are right. It can be changed.
