### ISSUE TITLE
Convertion from Arb to Floats

### ISSUE THREAD

**Issue by kirtsar** [Nemocas/Nemo.jl#466]
Simple example here:
```
using Nemo
RR = RealField(20)
x = RR(1)
y = convert(Float64, x)
ERROR: MethodError: Cannot `convert` an object of type arb to an object of type Float64
```

**Comment by kirtsar** [comment]
I've suddenly realized, that the code `Float64(x)` works just fine (returning Float64 number). Is it the expected behaviour?

**Comment by thofma** [comment]
Yes.

**Comment by wbhart** [comment]
If one is defined, I guess the other should be.

>
I'm not sure what it really means to convert something with a higher
precision to something of lower precision. For example,

Int(3249872349872734982374)

raises an InexactError.

**Comment by kirtsar** [comment]
![image](https://user-images.githubusercontent.com/32797932/44673628-c9796e80-aa34-11e8-8110-cb978567ff56.png)

**Comment by thofma** [comment]
Yes, this is expected. What can `convert(Float64, x)` do that `Float64(x)` cannot do?

**Comment by kirtsar** [comment]
I believe it is basically the same, that's why it is a little discouraging. Documentation does not say anything about this convention.

**Comment by thofma** [comment]
There was `convert(::Type{Float64}, ::arb)` in the old Nemo version. I think I removed it when moving to julia 1.0. I will add it back so that we have both.

**Comment by thofma** [comment]
Fixed. Thanks!
