### ISSUE TITLE
Docs no longer compile with Documenter.jl under Julia-1.0.0

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#471]
This doesn't appear to be their fault, but probably a number of things broke when we updated Nemo for 1.0.0.

The errors are as follows:

```
  !! No docs found for 'in{T}(a::T, ::Fac{T})'. [src/factor.md]
 !! No docs found for 'getindex{T}(::Fac{T}, T)'. [src/factor.md]
 !! No docs found for 'length(::Fac)'. [src/factor.md]
 !! No docs found for 'unit(::Fac)'. [src/factor.md]
 !! Undefined binding 'Nemo.trace'. [src/finitefield.md]
 !! Undefined binding 'Nemo.trace'. [src/numberfield.md]
 !! No docs found for 'isprime(::fmpz)'. [src/integer.md]
```

**Comment by thofma** [comment]
I only see warnings and no erros when running `julia docs/make.jl`. Did it crash for you? What is your Documenter version?

**Comment by thofma** [comment]
I also enabled the doc build on travis and it works: http://nemocas.github.io/Nemo.jl/latest/

**Comment by wbhart** [comment]
It doesn't crash. It's just that it can't find some docstrings.

**Comment by wbhart** [comment]
I think we no longer care about this, so I'm closing the issue.
