### ISSUE TITLE
GF(p) doesn't use fmpz_mod_poly for large p

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#474]
Currently GF(p) for bignum p calls ResidueField (which is ok). But this results in polynomials over GF(p) being generic, rather than using fmpz_mod_poly.

**Comment by thofma** [comment]
Do you have an idea how the polynomial type for p large should be called? I want to implement it.

**Comment by wbhart** [comment]
No preference. Perhaps gfp_fmpz_poly?
