### ISSUE TITLE
Cannot install Nemo under MacOS with Skylake CPU

### ISSUE THREAD

**Issue by saschatimme** [Nemocas/Nemo.jl#482]
I cannot build Nemo under MacOS with a Skylake CPU (so basically any Mac from the last 3 years) since I run into build errors for MPIR. The problem is some faulty assembler 
```
 ld: in section __DATA,__const reloc 0: X86_64_RELOC_SUBTRACTOR must have r_extern=1 file 'mpn/.libs/addmul_1.o' for architecture x86_64
```
I found a similar ticket for sage https://groups.google.com/forum/#!topic/sage-devel/P4GtTf2zo8k where it seems that they have a patch for it.

**Comment by wbhart** [comment]
Yeah this is an open ticket for MPIR. So I will close this here, as it has to be fixed there. Applying patches from Nemo itself is already causing issues, unfortunately. So we can't follow the Sage model there.

**Comment by thofma** [comment]
I agree that this is a MPIR bug. This reported was reported a while ago when we first visited the MPI at Leipzig. But since then nothing has changed. This leads to very bad user experience MacOS. I think we should just apply the patch. It is different to flint, since we don't build MPIR using git. This makes it much easier.

**Comment by wbhart** [comment]
To solve this issue going forward, we might want to transition to a model similar to what Sage is doing, namely to maintain community versions of "dead" upstream packages.

Currently MPIR has a 1400 file merge conflict which I and Brian have tried sorting out, with help from Jens Nurmann, but unfortunately we've given up. It looks like no one is contributing on the Linux side.

This would make more sense if we transition over to a single large repository for Oscar, as seems to be going to happen. I would even suggest maintaining a community version of Flint which diverges completely from the official Flint, as Flint simply isn't getting releases out on a schedule that meets the needs of Oscar. And there's no chance I will convince the Flint developers to make it part of the Oscar repo.

**Comment by thofma** [comment]
If there is no maintainer for the official MPIR, I don't see how there will be one for a communitary version. Can we host the tarball produced by Sage people on the MPIR homepage and use that? Is there anything speaking against it? The instructions to build the tarball are here https://github.com/sagemath/sage/blob/854f9764d14236110b8d7f7b35a7d52017e044f8/build/pkgs/mpir/spkg-src

**Comment by wbhart** [comment]
Sage doesn't maintain MPIR. They simply merge patches they need against a repo (not for MPIR, but for other "dead" projects; they will soon do it for MPIR, I think). Maintaining MPIR so it works for everyone is much, much harder than maintaining it so it works for an individual project.

**Comment by saschatimme** [comment]
@thomfa Your branch compiles perfectly and all tests seem to pass :)

**Comment by wbhart** [comment]
To be more specific, we could drop MSVC Windows support, fat binary support, updating for newer arches, keeping up with the latest version of the GMP interface, etc. The community version would just keep the project updated with patches so it doesn't stop anyone from getting their job done. It's orders of magnitude less complex.

**Comment by thofma** [comment]
Thanks for testing Sascha. I deleted some files as suggested on the mailing list.

Bill, I understand that a community version could be useful, but I we don't need to discuss this now. But for the meantime, what about the following?

Can we host the tarball produced by Sage people on the MPIR homepage and use that? Is there anything speaking against it? The instructions to build the tarball are here https://github.com/sagemath/sage/blob/854f9764d14236110b8d7f7b35a7d52017e044f8/build/pkgs/mpir/spkg-src
So producing the tarball is easy, it is just a question of hosting the tarball.

**Comment by wbhart** [comment]
Wait, Sage just deletes the files? That's out of date. The issue was properly fixed since then without a performance deficit.

Regarding the tarball, I don't see why we can't host it. Fredrik so far hasn't complained about the cost of hosting tarballs for Oscar.

**Comment by wbhart** [comment]
I would suggest starting with a recent git version of MPIR (but back out the recent changes from Brian Gladman, which haven't been sorted out for linux), as this will be significantly ahead of Sage. It won't work on Windows with MSVC, but otherwise it should have a lot more bugs fixed.

**Comment by thofma** [comment]
Sorry for the misunderstanding. I did not say that Sage deletes the files. I just tried to test if it (deleting the files) works for @saschatimme.

@saschatimme. I have made a new tarball for MPIR and have updated the branch `th/osxskylake` to use it. Could you update and try it again? To make sure that he rebuilds everything, start with `NEMO_MAKE_CLEAN=1`. Can you also run `make check` in the mpir folder and `]test Nemo` in julia? The MPIR folder should look like "mpir-3.0.0-commit". I am lacking a Mac to test it myself, so thanks for all your help.

**Comment by thofma** [comment]
Thanks. Will clean it up and do a PR tomorrow.
