### ISSUE TITLE
Different number of allocations in Julia 0.6 and Julia 0.7

### ISSUE THREAD

**Issue by konkam** [Nemocas/Nemo.jl#487]
Not sure if this is relevant information for you or if it just linked to the transition process, I post it just in case.

I am getting a large decrease in speed in transitioning from 0.6 to 0.7, which lead me to notice the different number of allocations between the two versions, for the same operation.
Note that on 0.7, Nemo appears to be at version 0.8.5 with  AbstractAlgebra at version 0.0.9, whereas it seems to be at 0.8.6 with AbstractAlgebra at version 0.0.10 on Julia 0.6.

With Julia 0.7, Nemo 0.8.5

```
julia> using Nemo, BenchmarkTools

Welcome to AbstractAlgebra version 0.0.9

AbstractAlgebra comes with absolutely no warranty whatsoever

WARNING: Base.Void is deprecated, use Nothing instead.
 in module Nemo
in __init__ at /home/guillaume/.julia/packages/Nemo/U04fv/src/Nemo.jl
┌ Warning: `is_linux` is deprecated, use `Sys.islinux` instead.
│   caller = __init__() at Nemo.jl:201
└ @ Nemo ~/.julia/packages/Nemo/U04fv/src/Nemo.jl:201
┌ Warning: `is_windows` is deprecated, use `Sys.iswindows` instead.
│   caller = __init__() at Nemo.jl:212
└ @ Nemo ~/.julia/packages/Nemo/U04fv/src/Nemo.jl:212
┌ Warning: `cfunction(f, r, a::Tuple)` is deprecated, use `cfunction(f, r, Tuple{a...})` instead.
│   caller = __init__() at Nemo.jl:227
└ @ Nemo ~/.julia/packages/Nemo/U04fv/src/Nemo.jl:227
┌ Warning: The function `cfunction` is now written as a macro `@cfunction`.
│   caller = cfunction(::Function, ::Type, ::Tuple{}) at deprecated.jl:55
└ @ Base ./deprecated.jl:55

Welcome to Nemo version 0.8.5

Nemo comes with absolutely no warranty whatsoever


julia> RR = RealField(256)
Real Field with 256 bits of precision and error bounds

julia> @btime RR(6)
┌ Warning: `finalizer(o, f::Function)` is deprecated, use `finalizer(f, o)` instead.
│   caller = Type at FlintTypes.jl:31 [inlined]
└ @ Core ~/.julia/packages/Nemo/U04fv/src/flint/FlintTypes.jl:31
┌ Warning: `finalizer(o, f::Function)` is deprecated, use `finalizer(f, o)` instead.
│   caller = arb(::fmpz, ::Int64) at ArbTypes.jl:117
└ @ Nemo ~/.julia/packages/Nemo/U04fv/src/arb/ArbTypes.jl:117
  255.939 μs (210 allocations: 24.55 KiB)
6.00000000000000000000000000000000000000000000000000000000000000000000000000000

```

With Julia 0.6, Nemo 0.8.6

```
julia> using Nemo, BenchmarkTools

Welcome to AbstractAlgebra version 0.0.10

AbstractAlgebra comes with absolutely no warranty whatsoever


Welcome to Nemo version 0.8.6

Nemo comes with absolutely no warranty whatsoever


julia> RR = RealField(256)
Real Field with 256 bits of precision and error bounds

julia> @btime RR(6)
  275.509 ns (6 allocations: 144 bytes)
6.00000000000000000000000000000000000000000000000000000000000000000000000000000

```

**Comment by thofma** [comment]
Thanks for the report. The deprecation warnings in v0.7 are not for free.

Did you try it on v1.0?

**Comment by konkam** [comment]
Thanks for the quick reply. I just tried on v1.0, and was about to report it, the problem is not there anymore:

```
julia> using Nemo, BenchmarkTools
[ Info: Precompiling Nemo [2edaba10-b0f1-5616-af89-8c11ac63239a]

Welcome to AbstractAlgebra version 0.1.3

AbstractAlgebra comes with absolutely no warranty whatsoever


Welcome to AbstractAlgebra version 0.1.3

AbstractAlgebra comes with absolutely no warranty whatsoever


Welcome to Nemo version 0.10.1

Nemo comes with absolutely no warranty whatsoever

[ Info: Precompiling BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]

julia> RR = RealField(256)
Real Field with 256 bits of precision and error bounds

julia> @btime RR(6)
  98.890 ns (2 allocations: 80 bytes)
6.00000000000000000000000000000000000000000000000000000000000000000000000000000
```

So the problem was clearly solved with the updates of Nemo. The number of allocations even decreased.

Concerning the deprecation warnings, it might be that they play a role. However, when you run the function for a second time, the warnings do not appear anymore and the number of allocations remains the same. Nothing prevents them from occurring in the background though.

Feel free to close the issue if you do not deem the problem worth investigating.

**Comment by thofma** [comment]
I looked this up at some point and realized, that julia always checks for the deprecation (every call), but prints the warning only once. So there will always be allocations and a slowdown.

You can start julia 0.7 with --depwarn=no to check with disabled deprecation warnings.

**Comment by konkam** [comment]
Thanks for the pointer to `--depwarn=no`, indeed that brought the number of allocations in Julia 0.7 back to match that of Julia 1.0

I close the issue, thanks again for your time

**Comment by thofma** [comment]
Thanks for reporting this. It is always good to know if there regressions when updating the julia version. At the moment we don't have proper infrastructure to detect runtime/allocation regressions.
