### ISSUE TITLE
Build error on Windows 10

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#491]
Starts at line 219 in build.jl with Julia 1.0.1.

    if Sys.iswindows()
       println("Downloading flint ... ")
       if Int == Int32
          download_dll("http://nemocas.org/binaries/w32-libflint.dll", joinpath(vdir, "lib", "libflint.dll"))
       else
          download_dll("http://nemocas.org/binaries/w64-libflint.dll", joinpath(vdir, "lib", "libflint.dll"))
       end
       try
          run(`ln -sf $vdir\\lib\\libflint.dll $vdir\\lib\\libflint-13.dll`)
       catch
        # cp(joinpath(vdir, "lib", "libflint.dll"), joinpath(vdir, "lib", "libflint-13.dll"), remove_destination=true)
          cp(joinpath(vdir, "lib", "libflint.dll"), joinpath(vdir, "lib", "libflint-13.dll"))
       end
   
ERROR: LoadError: MethodError: no method matching cp(::String, ::String; remove_destination=true)
│ Closest candidates are:
│   cp(::AbstractString, ::AbstractString; force, follow_symlinks) at file.jl:330 
│   got unsupported keyword argument "remove_destination"

**Comment by thofma** [comment]
Thanks for reporting this Peter. Unfortunately this path is not tested on any machine we have, so we did not notice that the name of the keyword argument changes. Will be fixed by https://github.com/Nemocas/Nemo.jl/pull/493.
