### ISSUE TITLE
Error while testing AcbField and hyp1f1.

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#499]
Welcome to Nemo version 0.10.2
Nemo comes with absolutely no warranty whatsoever

The following test works with Julia 0.6.2 but fails with 1.1.0-DEV on Windows 10.

    function GammaHyp(a, b, c, d)
        println("\nInput parameters: $a $b $c $d \nprec: ")
        prec = 500
        while prec <= 10000
            print(prec, ", ")
            CC = AcbField(prec)
            c = gamma(CC(a)) * hyp1f1(CC(b), CC(c), CC(d))
            b, i = unique_integer(c)
            b && return i
            prec *= 2
        end
        #error("$a $b $c $d gives an InexactError!")
    end

Input parameters: 11 -9 2 -1
prec: 500,
Input parameters: 21 -10 -20 -2
prec: 500,
Input parameters: 21 -10 -20 -1
prec: 500,
Input parameters: 21 -10 -20 1
prec: 500,
Input parameters: 74 -72 2 -1
prec: 500,
Input parameters: 147 -73 -146 -2
prec: 500, 1000,
Input parameters: 147 -73 -146 -1
prec: 500, 1000,
Input parameters: 147 -73 -146 1
prec: 500, 1000,
Input parameters: 151 -149 2 -1
prec: 500, 1000,
Input parameters: 301 -150 -300 -2
prec: 500, 1000, 2000,
Input parameters: 301 -150 -300 -1
prec: 500, 1000, 2000,
Input parameters: 301 -150 -300 1
prec: 500, 1000, 2000,

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (i
n their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x212ff65d -- _fmpz_clear_mpz at C:\msys64\home\user\w64\fl
int2\fmpz\fmpz.c:130
in expression starting at C:\Users\Home\.julia\environments\v1.1\src\Hyper1F1.jl:117
_fmpz_clear_mpz at C:\msys64\home\user\w64\flint2\fmpz\fmpz.c:128
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1843
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2198
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1560 [inlined]
run_finalizer at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:232
jl_gc_run_finalizers_in_list at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:327
run_finalizers at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:362
jl_gc_enable_finalizers at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:373
jl_typeinf_end at /home/Administrator/buildbot/worker/package_win64/build/src\locks.h:136
typeinf_ext at .\compiler\typeinfer.jl:568
typeinf_ext at .\compiler\typeinfer.jl:604
jfptr_typeinf_ext_1 at C:\Users\Home\AppData\Local\Julia-1.1.0-DEV\lib\julia\sys.dll (unknown line)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2198
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1560 [inlined]
jl_apply_with_saved_exception_state at /home/Administrator/buildbot/worker/package_win64/build/src\r
tutils.c:252
jl_type_infer at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:275
jl_compile_method_internal at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1798
[inlined]
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1842
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2198 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1560 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56
#printstyled at .\none:0 [inlined]
print_test_results at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\jul
ia\stdlib\v1.1\Test\src\Test.jl:797
print_test_results at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\jul
ia\stdlib\v1.1\Test\src\Test.jl:774 [inlined]
finish at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1
.1\Test\src\Test.jl:840
macro expansion at C:\Users\Home\.julia\environments\v1.1\src\Hyper1F1.jl:87 [inlined]
macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\
stdlib\v1.1\Test\src\Test.jl:1083 [inlined]
test at C:\Users\Home\.julia\environments\v1.1\src\Hyper1F1.jl:79
test at C:\Users\Home\.julia\environments\v1.1\src\Hyper1F1.jl:77 [inlined]
main at C:\Users\Home\.julia\environments\v1.1\src\Hyper1F1.jl:112
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1843
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2198
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:323
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:411
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:362 [in
lined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:750
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\
interpreter.c:880
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000001D69E1CF)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:772
jl_eval_module_expr at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:180
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:610
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win64/build/src\ast.c:881
include_string at .\loading.jl:1008
#129 at C:\Users\Home\.julia\packages\Atom\7rQ1O\src\eval.jl:125
withpath at C:\Users\Home\.julia\packages\CodeTools\hB4Hy\src\utils.jl:30
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1843
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2198 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1560 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56
withpath at C:\Users\Home\.julia\packages\Atom\7rQ1O\src\eval.jl:46 [inlined]
#128 at C:\Users\Home\.julia\packages\Atom\7rQ1O\src\eval.jl:122 [inlined]
with_logstate at .\logging.jl:397
with_logger at .\logging.jl:493 [inlined]
#127 at C:\Users\Home\.julia\packages\Atom\7rQ1O\src\eval.jl:121 [inlined]
hideprompt at C:\Users\Home\.julia\packages\Atom\7rQ1O\src\repl.jl:85
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1843
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2198
macro expansion at C:\Users\Home\.julia\packages\Atom\7rQ1O\src\eval.jl:120 [inlined]
#126 at .\task.jl:85
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1843
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2198
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1560 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:539
Allocations: 28171954 (Pool: 28166938; Big: 5016); GC: 60
Julia has exited. Press Enter to start a new session.

**Comment by thofma** [comment]
Thanks for the report. Could you provide the full example that we can just copy & paste? I can't infer from the print statements what the input is (which types).

**Comment by PeterLuschny** [comment]
Although I think that my report states that completely and clearly I am happy to help you out:

    a, b, c, d =  11,  -9,     2, -1; GammaHyp(a, b, c, d)
    a, b, c, d =  21,  -10,  -20, -2; GammaHyp(a, b, c, d)
    a, b, c, d =  21,  -10,  -20, -1; GammaHyp(a, b, c, d)
    a, b, c, d =  21,  -10,  -20,  1; GammaHyp(a, b, c, d)
    a, b, c, d =  74,  -72,    2, -1; GammaHyp(a, b, c, d)
    a, b, c, d = 147,  -73, -146, -2; GammaHyp(a, b, c, d)
    a, b, c, d = 147,  -73, -146, -1; GammaHyp(a, b, c, d)
    a, b, c, d = 147,  -73, -146,  1; GammaHyp(a, b, c, d)
    a, b, c, d = 151, -149,    2, -1; GammaHyp(a, b, c, d)
    a, b, c, d = 301, -150, -300, -2; GammaHyp(a, b, c, d)
    a, b, c, d = 301, -150, -300, -1; GammaHyp(a, b, c, d)
    a, b, c, d = 301, -150, -300,  1; GammaHyp(a, b, c, d)

**Comment by thofma** [comment]
All integer types are printed the same way. I dont know if the input is of type Int, BigInt, fmpz, Int16 or arb. Or maybe there is a way that I missed?

**Comment by PeterLuschny** [comment]
OK, I see your point. Then do the most natural thing, insert the integers directly into the call, like this:
GammaHyp(301, -150, -300, 1). Since literals are always of type Int and of no other type this fixes any ambiguity. And in fact this single call is a minimal example for the issue.

**Comment by thofma** [comment]
I cannot reproduce on linux. I will look at it next Monday. Then I have access to a Windows machine. Does it also fail with julia v1.0.1?

**Comment by thofma** [comment]
Thanks for the hints!

**Comment by PeterLuschny** [comment]
You are welcome! By the way, the expected numeric values can be seen on this [page](http://luschny.de/math/seq/GammaHypPython.html), which shows the same function  implemented with Python, but under the surface probably accesses the same C functions, if I'm not mistaken.

**Comment by thofma** [comment]
I finally got my hands on a Windows machine. Note that the function is not the same as in the notebook that you linked. In the julia version in every iteration you are overriding `b` and `c`. Note sure if this is intended.

Nevertheless, there is some bug when calling `unique_integer`:
```julia
julia> using Nemo;
julia> RR = ArbField(1000)
Real Field with 1000 bits of precision and error bounds

julia> b, i = unique_integer(RR(2)^1000);
julia> b, i = unique_integer(RR(2)^1000);
julia> b, i = unique_integer(RR(2)^1000);
julia> b, i = unique_integer(RR(2)^1000);
julia> exit();

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x16a7f65d -- _fmpz_clear_mpz at C:\msys64\home\user\w64\flint2\fmpz\fmpz.c:130
in expression starting at no file:0
_fmpz_clear_mpz at C:\msys64\home\user\w64\flint2\fmpz\fmpz.c:128
```
Note that when looking closer at the finalizers, one notices that it crashes when calling `fmpz_clear_mpz` with argument `i`. I cannot reproduce it on Linux.

Do you have any idea @fredrik-johansson?

**Comment by fredrik-johansson** [comment]
Is it reproducible from C?

**Comment by thofma** [comment]
I feared that you were going to ask this. I will try.

**Comment by fredrik-johansson** [comment]
arf_get_fmpz does some low-level manipulation to write the fmpz data, so there could conceivably be a bug in that code resulting in a corrupted fmpz. But the valgrind output for arf/test/t-get_fmpz is completely clean on Linux.

**Comment by thofma** [comment]
I can reproduce it only on Windows. I will try to give you a C example.

**Comment by thofma** [comment]
I think they changed the order in which finalizers are run to LIFO between julia 0.6 and julia 1.0. But I could not find a reordering of *_clear which made it crash in a simple C program. I have to give up for the moment.

**Comment by wbhart** [comment]
We should not be relying on the order finalizers run.

**Comment by thofma** [comment]
Yes, and I don't think we are.

**Comment by PeterLuschny** [comment]
Thank you very much for your efforts!

I now use the current Julia-1.1.0-DEV\bin\julia.exe and Nemo version 0.11.0. The bug is still there but the error message looks completely different. Therefore I include it below.

My observations: It refers to w64\flint2\fmpz\fmpz.c which I could not find in the github repository. 
And I do not understand the lines:

     BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
     RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
I use it on Windows 64 and thought it was compiled for 64 bits?

---
    a, b, c, d = 301, -150, -300,  1; GammaHyp(a, b, c, d)

    function GammaHyp(a, b, c, d)
        println("\nInput parameters: $a $b $c $d \nprec: ")
        prec = 500
        while prec <= 10000
            print(prec, ", ")
            CC = AcbField(prec)
            g = gamma(CC(a)) * hyp1f1(CC(b), CC(c), CC(d))
            t, i = unique_integer(g)
            if t
                println("\nOK!")
                println(i)
                return i
            end
            prec *= 2
        end
        println("\nInexactError! ", g)
    end

OUTPUT:
Input parameters: 301 -150 -300 1 
prec: 
500, 1000, 2000, 4000, 
OK!
5043 .... 000

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1578ee6d -- _fmpz_clear_mpz at C:\msys64\home\user\w64\flint2\fmpz\fmpz.c:130
in expression starting at no file:0
_fmpz_clear_mpz at C:\msys64\home\user\w64\flint2\fmpz\fmpz.c:128
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1854
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2209
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
run_finalizer at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:232
jl_gc_run_finalizers_in_list at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:318
jl_gc_run_all_finalizers at /home/Administrator/buildbot/worker/package_win64/build/src\gc.c:346
jl_atexit_hook at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\init.c:249
wmain at /home/Administrator/buildbot/worker/package_win64/build/ui\repl.c:218
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:329
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:212
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 2725383 (Pool: 2725048; Big: 335); GC: 4

**Comment by wbhart** [comment]
It looks to me like the Flint memory manager is not working correctly on Windows.

@thofma perhaps it might be worth compiling with --reentrant on Windows (the code is still reentrant with the default --single, but it uses a much more complicated implementation which uses pthreads functionality which might not be implemented correctly on Windows).

**Comment by PeterLuschny** [comment]
This might be relevant:
https://discourse.julialang.org/t/my-simple-embedding-example-works-on-linux-fails-in-windows/18813

**Comment by thofma** [comment]
The issue is more about calling julia from C whereas here we want to call C code from julia. When I find some time, I will try to compile the binaries with --reentrant and see if it works.

**Comment by wbhart** [comment]
@thofma If you do, could you also advance the sha to the latest Flint trunk.
