### ISSUE TITLE
problem with inverting a matrix over a residue class ring

### ISSUE THREAD

**Issue by ThomasBreuer** [Nemocas/Nemo.jl#504]
Currently the following happens.

```julia
julia> using Nemo

Welcome to Nemo version 0.10.3

Nemo comes with absolutely no warranty whatsoever


julia> r = Nemo.ResidueRing( Nemo.ZZ, 6 );

julia> m = matrix( r, 2, 2, [ 4, 3, 3, 4 ] )
[4 3]
[3 4]

julia> isone( m * m )
true

julia> inv( m )
Flint exception (Impossible inverse):
    Cannot invert modulo 2*0
ERROR: Problem in the Flint-Subsystem
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] flint_abort() at .../packages/Nemo/XNd31/src/Nemo.jl:99
 [3] inv(::nmod_mat) at .../packages/Nemo/XNd31/src/flint/nmod_mat.jl:428
 [4] top-level scope at none:0
```

**Comment by wbhart** [comment]
Flint currently can't invert a matrix over Z/nZ if n is not prime. It tries, and will succeed often, but sometimes it hits an impossible inverse internally, which we catch in Nemo, so at least you know that it gave up.

Of course it could perform this computation, but the improvements that would be needed are not currently implemented. We are certainly aware of the issue.

**Comment by wbhart** [comment]
On the other hand, I'm not sure if the answer is unique.

**Comment by wbhart** [comment]
Ok, it's unique.

**Comment by ThomasBreuer** [comment]
@wbhart The background is that there is a GAP package `matgrp`
(see http://www.gap-system.org/Packages/matgrp.html)
which deals in particular with matrix groups over residues class rings.
The idea is to gain speed by using Flint's `nmod_mat` objects instead of GAP's own matrices
for the arithmetic operations.

As a temporary fix, I can catch the failure of `nmod_mat_inv` (or `nmod_mat_solve`),
and then delegate to the inversion of a lift to the integers or rationals, followed by a reduction.
Of course these computations are more involved than necessary, but it works for the moment.

**Comment by wbhart** [comment]
@ThomasBreuer Yes, that will work for the time being.

**Comment by fingolfin** [comment]
This seems to be working these days:
```
julia> r, = residue_ring( ZZ, 6 );

julia> m = matrix( r, 2, 2, [ 4, 3, 3, 4 ] )
[4   3]
[3   4]

julia> isone( m * m )
true

julia> inv( m )
[4   3]
[3   4]
```
