### ISSUE TITLE
sqrt of [+/- 5.57e-309] arb gives nan

### ISSUE THREAD

**Issue by konkam** [Nemocas/Nemo.jl#505]
The function `sqrt(::arb)` returns `nan` when called on a 0 value with arbitrary precision.

```
julia> RR = RealField(256)
julia> log(RR(2)) - log(RR(2))
[+/- 2.16e-77]
julia> sqrt(log(RR(2)) - log(RR(2)))
nan
```

However, `exp` returns the right value, and so do the few other functions that I have tried.

```
julia> exp(log(DualOptimalFiltering.RR(2)) - log(DualOptimalFiltering.RR(2)))
[1.0000000000000000000000000000000000000000000000000000000000000000000000000000 +/- 2.16e-77]
```

**Comment by thofma** [comment]
The ball `log(RR(2)) - log(RR(2))` contains negative numbers, so `nan` is the only possible answer.

**Comment by fredrik-johansson** [comment]
Depending on what you want, either convert to an `acb` or use `arb_sqrtpos` (not wrapped in Nemo right now).

**Comment by konkam** [comment]
Ah, many thanks for your explanation, this had slipped my mind
