### ISSUE TITLE
Fractions don't work correctly with negative components

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#515]
Doesn't look right.

```
julia> K = FractionField(ZZ)
Rational Field

julia> K(1, -2)
1//18446744073709551614
```

**Comment by thofma** [comment]
Looks like a flint problem:
```julia
julia> fmpq(2, -1)
2//18446744073709551615
```

**Comment by wbhart** [comment]
Flint expects a positive denominator. We have to normalise before passing to Flint. I will fix it tomorrow.

**Comment by thofma** [comment]
Documentation does not mention positive denominators. Maybe it should be fixed in flint.

**Comment by wbhart** [comment]
See fmpq_set_si [1].

http://flintlib.org/sphinx/fmpq.html
