### ISSUE TITLE
convert fmpz_mpoly to AbstractAlgebra.Generic.MPoly{fmpz}

### ISSUE THREAD

**Issue by heiderich** [Nemocas/Nemo.jl#522]
I would appreciate such a feature.

Motivation: I want to convert from `fmpz_mpoly` to `AbstractAlgebra.Generic.MPoly{BigInt}`.
As a first step, I would like to convert `fmpz_mpoly` to `AbstractAlgebra.Generic.MPoly{fmpz}` and then further to `AbstractAlgebra.Generic.MPoly{BigInt}` using `change_base_ring`.

I want to convert to `AbstractAlgebra.Generic.MPoly{BigInt}` in order to be able to serialize, which currently seems not to be possible for Nemo objects.

**Comment by thofma** [comment]
Out of curiousity, does the serialization of `AbstractAlgebra.Generic.MPoly{BigInt}` work?

**Comment by heiderich** [comment]
In view of https://github.com/Nemocas/AbstractAlgebra.jl/issues/206#issuecomment-445193053 I was hoping that this works. However there seem to be problems:

```
julia> using AbstractAlgebra

julia> using Serialization

julia> R,(x1,x2) = AbstractAlgebra.Generic.PolynomialRing(AbstractAlgebra.ZZ, ["x1","x2"])
(Multivariate Polynomial Ring in x1, x2 over Integers, AbstractAlgebra.Generic.MPoly{BigInt}[x1, x2])

julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> Serialization.serialize(io, x1)

julia> seekstart(io)
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=237, maxsize=Inf, ptr=1, mark=-1)

julia> deser_x1 = deserialize(io)
x1

julia> deser_x1 + deser_x1
2*x1

julia> deser_x1 * deser_x1
ERROR: Unable to coerce to polynomial
```

And

```
julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> Serialization.serialize(io, R)

julia> seekstart(io)
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=154, maxsize=Inf, ptr=1, mark=-1)

julia> deser_R = deserialize(io)
Multivariate Polynomial Ring in x1, x2 over Integers

julia> base_ring(deser_R) == base_ring(R)
false
```

Is that the expected behavior?

**Comment by thofma** [comment]
I am afraid this is expected (at least I expected it). The presence of the parents (which cannot be avoided for non-trivial objects) makes serialization pretty complicated.

**Comment by wbhart** [comment]
The problem is that parents have to be unique in the system. Deserialise is simply making a new parent object with the same data in it as the old one. But this is not the same object.

It seems we actually need to write serialisation functions for all the AbstractAlgebra types. On the other hand, it is not that hard. Everything will deserialise just fine if we reconstruct the parent object by looking up the data for the parent for the relevant parent cache.

**Comment by wbhart** [comment]
change_base_ring can be used to do this if one defines (R::Nemo.AbstractAlgebra.Integers{BigInt})(a::fmpz) = convert(BigInt, a)

**Comment by fingolfin** [comment]
Can be done using `map_coefficients`:
```
julia> S,(x,y) = polynomial_ring(ZZ, [:x,:y])
(Multivariate polynomial ring in 2 variables over ZZ, ZZMPolyRingElem[x, y])

julia> f = y^2 + 5*x*y - 17*x
5*x*y - 17*x + y^2

julia> typeof(f)
ZZMPolyRingElem

julia> g = map_coefficients(BigInt, f)
5*x*y - 17*x + y^2

julia> typeof(g)
AbstractAlgebra.Generic.MPoly{BigInt}
```
and then you can also get back that way; note the use of the `parent` kwarg.
```
julia> map_coefficients(ZZ, g; parent=S)
5*x*y - 17*x + y^2
```
