### ISSUE TITLE
Pick p-adic print mode for FlintPadicField

### ISSUE THREAD

**Issue by alexjbest** [Nemocas/Nemo.jl#523]
In Flint one can specify the print mode as one of PADIC_TERSE, PADIC_SERIES, PADIC_VAL_UNIT , it would be nice if this could be specified in Nemo too.

I can probably do this at some point, this is more of a note to self, if you think its faster to do it yourself go ahead though!

**Comment by wbhart** [comment]
Thanks Alex. It makes sense to add this, say as an optional named argument when creating the padic field, I think.

**Comment by alexjbest** [comment]
Closed by #524 ! Thanks
