### ISSUE TITLE
Coerce elements of Nemo.ZZ into AbstractAlgebra.Generic.ZZ or AbstractAlgebra.Generic.zz

### ISSUE THREAD

**Issue by heiderich** [Nemocas/Nemo.jl#541]
I would like to coerce elements of Nemo.ZZ into AbstractAlgebra.Generic.ZZ or AbstractAlgebra.Generic.zz. The following two commands throw errors:

```
AbstractAlgebra.Generic.ZZ(one(Nemo.ZZ))
AbstractAlgebra.Generic.zz(one(Nemo.ZZ))

```
The following however work:

```
convert( AbstractAlgebra.Generic.elem_type(AbstractAlgebra.Generic.ZZ), one(Nemo.ZZ))
convert( AbstractAlgebra.Generic.elem_type(AbstractAlgebra.Generic.zz), one(Nemo.ZZ))
```

Is this intended? If not, could these coercions be implemented?

**Comment by wbhart** [comment]
This is very much intended. ZZ in AbstractAlgebra is defined for people who only want to work with Julia types (BigInt in this case), whereas in Nemo, it is assumed you want to work with Nemo.ZZ throughout.

As BigInt is a type, not a Nemo RingElem, we make use of the standard Julia convert instead of our own parent coercion for this.

**Comment by heiderich** [comment]
Let me explain my use case: I was working with multivariate polynomials over Nemo.ZZ. Now I want to use Singular to compute Gröbner bases. As far as I know Nemo.ZZ does currently not work as a coefficient ring. Therefore my idea is to convert the coefficients of the polynomials to BigInt or Int.

The following does not work:

```
using AbstractAlgebra
R,(x,y) = AbstractAlgebra.Generic.PolynomialRing(Nemo.ZZ, ["x","y"])
change_base_ring( x, c -> convert(elem_type(AbstractAlgebra.Generic.ZZ), c) )

```

because of the coercion taking place in

https://github.com/Nemocas/AbstractAlgebra.jl/blob/530fbd886ec08e8495fcc1880f66ad9d755d1384/src/generic/MPoly.jl#L116

**Comment by wbhart** [comment]
You can just define it temporarily for your use case if you want.

But Nemo.ZZ will work as a coefficient ring soon. We actually have it working in a branch which is not quite ready to merge yet.

**Comment by heiderich** [comment]
Thanks. 

Would changing the mentioned line to a conversion instead of a coercion be a good alternative?

**Comment by wbhart** [comment]
I meant that you can define it in your own code.

Simply overload:

AbstractAlgebra.ZZ(a::fmpz) = convert(BigInt, a)

**Comment by wbhart** [comment]
That's not something we want to encourage at all. Usually when people are trying to do this they are trying to go via Julia types because something is missing. We would prefer to know what is missing and implement it.

**Comment by heiderich** [comment]
I see. So I will use the workaround you proposed.
