### ISSUE TITLE
zero! for abs_series

### ISSUE THREAD

**Issue by alexjbest** [Nemocas/Nemo.jl#546]
There is no zero! for AbsSeries.

I made the issue here instead of AbstractAlgebra as I mostly want to use fmpq_abs_series, but there is also no zero! for AbstractAlgebra.Generic.AbsSeries, but there is for AbstractAlgebra.Generic.RelSeries.

I want this as I want to expand divrem to work with SeriesElem's (plain absolute series for me, but why not others) either generically or in special cases like fmpq_abs_series.

This issue is more of a note to self, before I forget all the changes I made recently in my branch: but suggestions on how to add this most properly are welcome.

**Comment by wbhart** [comment]
Thanks for reporting it. I'll try to get to it as soon as I can.

**Comment by thofma** [comment]
At the moment alex is doing
```julia
function zero!(z::fmpq_abs_series)
   ccall((:fmpq_poly_zero, :libflint), Nothing,
                (Ref{fmpq_abs_series},), z)
   z.prec = parent(z).prec_max
   return z
end
```
Should we do this for all series types in Nemo?

**Comment by wbhart** [comment]
Yes, I think so. I'll work on the generic AbstractAlgebra version now, and that should clarify if I have overlooked anything.

**Comment by wbhart** [comment]
I've fixed the AbsSeries for AbstractAlgebra.

**Comment by alexjbest** [comment]
Great, thank you!
