### ISSUE TITLE
New error on latest 0.5

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#55]
https://travis-ci.org/Nemocas/Nemo.jl/builds/143837871
https://s3.amazonaws.com/archive.travis-ci.org/jobs/143837874/log.txt

What do we do about these changes in 0.5 which break Nemo? Try to fix them continuously? Or wait for 0.5 release and do them alltogether?

**Comment by wbhart** [comment]
Not sure. I'll be on holidays for about a week starting Wednesday. It's
pretty clear I won't even get a version of Nemo working with Julia 0.4
ready for release before then. So maybe we revisit it when I return.

My basic plan is to do three releases of Nemo:

0.5.0 - New version of Nemo, works with Julia 0.4.6
0.5.1 - works with Windows and Appveyor
0.5.2 - works with Julia 0.5

The first implies we shouldn't make any changes that break compatibility
with 0.4.6. I'm happy for you to fix the issues though if you want to, so
long as we keep 0.4.6 working.

Bill.

**Comment by thofma** [comment]
Sounds like a good plan to me.

Do you want 0.5.0 to be a release free of (ambiguity) warnings?

I think I am going to ignore the julia 0.5 errors for now and address them once we have released 0.5.0.

**Comment by wbhart** [comment]
Yeah we should have no ambiguity warnings. Not sure how best to do that for
now.

Obviously we'll remove all the extra code we add when we do the release to
support Julia 0.5, since it will thankfully not be needed.

Bill.

**Comment by thofma** [comment]
We also have `arb/acb_poly` modules in Fredrik's repository and `arb/acb_mat` modules in my repository. I think both are complete modulo documentation. I am happy to add documentation (end of next week) if there is a chance of them to be included in 0.5.0.

**Comment by wbhart** [comment]
arb_poly should definitely go in. I haven't looked at arb_mat.

Documentation for arb_poly should be easy. Just add arb_poly to the list of
polynomial types supported, in doc/src/polynomial.jl and then add any
functions to that document that are specific to arb_polys and not available
for other types.

The same should apply to arb_mat of course, in doc/src/matrix.jl.

If you'd like to add those, that would be great.

I have the acb documentation half done. I'll finish it when I return early
next week. It looks like I won't get a chance while I'm in the UK.

Bill.
