### ISSUE TITLE
Valuation of padic zero

### ISSUE THREAD

**Issue by alexjbest** [Nemocas/Nemo.jl#552]
Currently the valuation of zero in the padics returns 0, this is contrary to the doc and the behaviour of power series.

```
julia> zero(PadicField(5,5))
0 + O(5^5)

julia> valuation(ans) # expected 5
0

julia> zero(PowerSeriesRing(ZZ,5,"t",cached=false,model=:capped_absolute)[1])
0+O(t^5)

julia> valuation(ans)
5
```

The doc says:
Return the valuation of the given $p$-adic field element, i.e. if the given
element is divisible by $p^n$ but not a higher power of $p$ then the function
will return $n$.

But 0 + O(5^5) is divisible by 5^5.

**Comment by alexjbest** [comment]
Note that this is simply the flint behaviour, so maybe the solution is just for the nemo doc to be more specific about this, personally I prefer valuation to behave consistently with power series though.

**Comment by wbhart** [comment]
I agree with you Alex, and this is a bug in my opinion. Thanks for reporting it. I don't know how hard it is to fix, and this week will be my last chance for a long time (at least 2 months), but we will try to fix it as soon as we can.
