### ISSUE TITLE
Compilation on Win64 does not find libarb.

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#571]
After upgrading Julia today the following happens:

[ Info: Precompiling Nemo [2edaba10-b0f1-5616-af89-8c11ac63239a]
Welcome to Nemo version 0.13.0

The compilation crashes with

    error compiling uv_alloc_buf: error compiling !=: 
    error compiling Type: could not load library "libarb"
    The specified module could not be found.

I am on Windows64 and Julia Version 1.1.0 (2019-01-21).

Peter

**Comment by thofma** [comment]
Can you do a `Pkg.build("Nemo")` and post the output of `Pkg.status()`?

**Comment by thofma** [comment]
If it still doesn't work, can you post the content of `Nemo/deps/usr/local/bin` and `Nemo/deps/usr/local/lib`?

**Comment by PeterLuschny** [comment]
I completly reinstalled all of Julia. I am now on a fresh JuliaPro_v1.0.3.1.

While updating I noticed two downgrades:

[c3fe647b] AbstractAlgebra v0.4.5 => v0.4.1
[edaba10] Nemo v0.13.0 => v0.12.1

Thereafter the following errors occured:

[ Info: Precompiling Nemo [2edaba10-b0f1-5616-af89-8c11ac63239a]
ERROR: LoadError: LoadError: LoadError: LoadError: error compiling docm: could not load library "libflint"
The specified module could not be found.

Stacktrace:
 [1] @doc(::LineNumberNode, ::Module, ::Expr, ::Vararg{Expr,N} where N) at .\boot.jl:451
 [2] include at .\boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1044
 [4] include at .\sysimg.jl:29 [inlined]
 [5] include(::String) at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\Nemo.jl:1
 [6] top-level scope at none:0
 [7] include at .\boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at .\loading.jl:1044
 [9] include at .\sysimg.jl:29 [inlined]
 [10] include(::String) at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\Nemo.jl:1
 [11] top-level scope at none:0
 [12] include at .\boot.jl:317 [inlined]
 [13] include_relative(::Module, ::String) at .\loading.jl:1044
 [14] include(::Module, ::String) at .\sysimg.jl:29
 [15] top-level scope at none:2
 [16] eval at .\boot.jl:319 [inlined]
 [17] eval(::Expr) at .\client.jl:393
 [18] top-level scope at .\none:3
in expression starting at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\flint\fmpz.jl:1079
in expression starting at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\flint\fmpz.jl:1079
in expression starting at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\Rings.jl:18
in expression starting at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\Nemo.jl:328

ERROR: LoadError: Failed to precompile Nemo [2edaba10-b0f1-5616-af89-8c11ac63239a] 
to C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\compiled\v1.0\Nemo\SPUMD.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at .\loading.jl:1203
 [2] _require(::Base.PkgId) at .\loading.jl:960
 [3] require(::Base.PkgId) at .\loading.jl:858
 [4] require(::Module, ::Symbol) at .\loading.jl:853
in expression starting at C:\Users\Home\JuliaProjects\Sequences\src\Sequences.jl:15

--------------------------------

(Sequences) pkg> build Nemo
  Building Nemo -> `C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\deps\build.log`

The build.log shows: 

M4_VERSION = "1.4.17" = "1.4.17"
YASM_VERSION = "1.3.0" = "1.3.0"
MPIR_VERSION = "3.0.0-90740d8fdf03b941b55723b449831c52fd7f51ca" = "3.0.0-90740d8fdf03b941b55723b449831c52fd7f51ca"
MPFR_VERSION = "4.0.0" = "4.0.0"
ANTIC_VERSION = "ede86094503380648ce51fa56cd3ff16217cffed" = "ede86094503380648ce51fa56cd3ff16217cffed"
FLINT_VERSION = "f088d6c89d80b6b90a5653e1ada24dbe36964bd7" = "f088d6c89d80b6b90a5653e1ada24dbe36964bd7"
ARB_VERSION = "fe53e3f306380b5a65b30dcec776e10428601790" = "fe53e3f306380b5a65b30dcec776e10428601790"
Deleting old C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\local
Downloading libpthread ... 
DONE
Downloading MPIR sources ... 
DONE
Downloading MPIR ... 
DONE
Downloading MPFR sources ... 
DONE
Downloading MPFR ... 
DONE
Downloading flint ... 
DONE
Downloading arb ... 
DONE
Downloading antic ... 
DONE

----------------------------------------------
After this build I got:

WARNING: replacing module Sequences.[ Info: Precompiling Nemo [2edaba10-b0f1-5616-af89-8c11ac63239a]
ERROR: LoadError: LoadError: LoadError: LoadError: error compiling docm: could not load library "libflint"
The specified module could not be found.

Stacktrace: [1] @doc(::LineNumberNode, ::Module, ::Expr, ::Vararg{Expr,N} where N) at .\boot.jl:451
 [2] include at .\boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1044 [4] include at .\sysimg.jl:29 [inlined]
 [5] include(::String) at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\Nemo.jl:1 [6] top-level scope at none:0
 [7] include at .\boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at .\loading.jl:1044 [9] include at .\sysimg.jl:29 [inlined]
 [10] include(::String) at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\Nemo.jl:1 [11] top-level scope at none:0
 [12] include at .\boot.jl:317 [inlined]
 [13] include_relative(::Module, ::String) at .\loading.jl:1044
 [14] include(::Module, ::String) at .\sysimg.jl:29 [15] top-level scope at none:2
 [16] eval at .\boot.jl:319 [inlined] [17] eval(::Expr) at .\client.jl:393
 [18] top-level scope at .\none:3
in expression starting at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\flint\fmpz.jl:1079
in expression starting at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\flint\fmpz.jl:1079
in expression starting at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\Rings.jl:18
in expression starting at C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\packages\Nemo\q6aX4\src\Nemo.jl:328
ERROR: LoadError: Failed to precompile Nemo [2edaba10-b0f1-5616-af89-8c11ac63239a] to C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\compiled\v1.0\Nemo\SPUMD.ji.Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at .\loading.jl:1203 [2] _require(::Base.PkgId) at .\loading.jl:960
 [3] require(::Base.PkgId) at .\loading.jl:858 [4] require(::Module, ::Symbol) at .\loading.jl:853
in expression starting at C:\Users\Home\JuliaProjects\Sequences\src\Sequences.jl:15julia>

-----------------------------

Summa summarum: Alles fuer die Katz!

**Comment by thofma** [comment]
Das verstehe ich nicht. Bei `v0.12.3` hat sich nie was geändert. Und warum downgraded er? Was sagt denn "Pkg.status()" und "Pkg.update()"? Ich bin nicht vertraut mit JuliaPro.

**Comment by PeterLuschny** [comment]
> Was sagt denn "Pkg.status()" und "Pkg.update()"?

(Sequences) pkg> status
Project Sequences v0.1.0
    Status `C:\Users\Home\JuliaProjects\Sequences\Project.toml`
  [c3fe647b] ↓ AbstractAlgebra v0.4.5 ⇒ v0.4.1
  [6e4b80f9]   BenchmarkTools v0.4.2
  [861a8166]   Combinatorics v0.7.0
  [e30172f5] ↓ Documenter v0.21.5 ⇒ v0.21.1
  [7073ff75] ↓ IJulia v1.18.0 ⇒ v1.16.0
  [c8e1da08]   IterTools v1.1.1 #master (
https://github.com/JuliaCollections/IterTools.jl)
  [1914dd2f] ↓ MacroTools v0.4.5 ⇒ v0.4.4
  [c03570c3]   Memoize v0.3.0
  [2edaba10] ↓ Nemo v0.13.0 ⇒ v0.12.1
  [27ebfcd6]   Primes v0.4.0
  [ade2ca70]   Dates
  [cd3eb016]   HTTP v0.8.0
  [b77e0a4c]   InteractiveUtils
  [44cfe95a]   Pkg
  [8dfed614]   Test
  [cf7118a7]   UUIDs
    Status `C:\Users\Home\JuliaProjects\Sequences\Manifest.toml`
  [c3fe647b] ↓ AbstractAlgebra v0.4.5 ⇒ v0.4.1
  [e30172f5] ↓ Documenter v0.21.5 ⇒ v0.21.1
  [7073ff75] ↓ IJulia v1.18.0 ⇒ v1.16.0
  [1914dd2f] ↓ MacroTools v0.4.5 ⇒ v0.4.4
  [2edaba10] ↓ Nemo v0.13.0 ⇒ v0.12.1

  (Sequences) pkg> update
  Updating registry at
`C:\Users\Home\.juliapro\JuliaPro_v1.0.3.1\registries\JuliaPro`
  Updating git-repo `https://pkg.juliacomputing.com//registry/JuliaPro`
  Updating git-repo `https://github.com/JuliaCollections/IterTools.jl`
 Resolving package versions...
  Updating `C:\Users\Home\JuliaProjects\Sequences\Project.toml`
 [no changes]
  Updating `C:\Users\Home\JuliaProjects\Sequences\Manifest.toml`
 [no changes]

> Und warum downgraded er?
Er? Sie!

> Ich bin nicht vertraut mit JuliaPro.

I do not think that this makes any difference here.
JuliaPro has only some convenience features
pre-installed. Just think that I am on Julia v1.0.3.1 now.
Before, when the trouble started, it was Julia v1.2.0.

**Comment by thofma** [comment]
Before reinstalling, did you delete `C:\Users\Home.juliapro`? Could you show me also the output of `C:\Users\Home\JuliaProjects\Sequences\Project.toml`?

**Comment by PeterLuschny** [comment]
>
> Before reinstalling, did you delete C:\Users\Home.juliapro?
>
 You mean C:\Users\Home\.juliapro? Yes!

> Could you show me also the output of
C:\Users\Home\JuliaProjects\Sequences\Project.toml?

name = "Sequences"
uuid = "69b24c39-7887-5099-9a92-2bd65b45799c"
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

>

**Comment by thofma** [comment]
Ok, there are different problems.
1) JuliaPro has its own package registry, which is apparently not up to date.
2) There is a bug in Nemo that only shows up in JuliaPro on Windows. I could reproduce it. You can fix it yourself locally by going to the Nemo directory and opening fmpz.jl. On line 1079 there is a function "isprime". There is a comment between the docstring and the function definition. Just remove the comment. Then it will work. (You might have to change the permission of the file. It might be read-only.)

I will fix 2) properly on Monday but I can't do anything about 1).

**Comment by PeterLuschny** [comment]
Thanks! I can confirm that this works with

Version 1.2.0-DEV.527 (2019-03-22)
Commit 672bf8bea7 (0 days old master)
Installed AbstractAlgebra ───── v0.4.5
Installed Nemo ─────────── v0.13.0

**Comment by thofma** [comment]
I tagged a new release. Once https://github.com/JuliaLang/METADATA.jl/pull/22399 is merged you can just update and forget about the local workaround.
