### ISSUE TITLE
isirreducible(::fmpz_poly)

### ISSUE THREAD

**Issue by alexjbest** [Nemocas/Nemo.jl#578]
Would be nice to have this out of the box (using Gauss's lemma shouldn't be too hard unless I'm missing something?)

```
julia> Q,q = PolynomialRing(ZZ,"q")
(Univariate Polynomial Ring in q over Integer Ring, q)

julia> isirreducible(q^2 + 1)
ERROR: MethodError: no method matching isirreducible(::fmpz_poly)
```

**Comment by thofma** [comment]
Should it by default use `isprime` on the content?

**Comment by wbhart** [comment]
I don't think it matters too much for most applications, since that is only going to affect constant polynomials. So I would make it use isprime by default.

**Comment by alexjbest** [comment]
Apologies I was simply not aware of isprime being there and as
isirreducibld was there for fmpq_poly it seemed natural.
