### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#6]
I managed to get Nemo running on my Windows 7. It all works except for converting `fmpz` to strings:

```
julia> using Nemo

Welcome to Nemo version 0.4.0

Nemo comes with absolutely no warranty whatsoever


julia> bin(fmpz(2))
"\"\0"

julia> bin(fmpz(4))
"?\x000"

julia> bin(fmpz(12))
"\"\x0000"

julia> fmpz(12)
??

julia> fmpz(32)
?☺

julia> fmpz(12)
??
```

On the other hand, it works on appveyor, so it must be a local problem. Any ideas?

**Comment by wbhart** [comment]
No idea. Last time I updated my Nemo on Windows 64 it worked ok (just tried
it now).

So unless someone changed it recently, it should be ok.

**Comment by thofma** [comment]
@fieker showed that it has something to do with the flint_free here:
```julia
function base(n::fmpz, b::Integer)
    2 <= b <= 62 || error("invalid base: $b")
    p = ccall((:fmpz_get_str,:libflint), Ptr{UInt8}, 
              (Ptr{UInt8}, Cint, Ptr{fmpz}), C_NULL, b, &n)
    len = Int(ccall(:strlen, Csize_t, (Ptr{UInt8},), p))
    s = ASCIIString{}{}((pointer_to_array(p, len, false)))
    ccall((:flint_free, :libflint), Void, (Ptr{UInt8},), p)
    return s
end
```

If I replace it with the function
```julia
function base(n::fmpz, b::Integer)
    2 <= b <= 62 || error("invalid base: $b")
    p = ccall((:fmpz_get_str,:libflint), Ptr{UInt8}, 
              (Ptr{UInt8}, Cint, Ptr{fmpz}), C_NULL, b, &n)
    len = Int(ccall(:strlen, Csize_t, (Ptr{UInt8},), p))
    s = ASCIIString{}{}((pointer_to_array(p, len, true)))
    return s
end
```
it works.

**Comment by wbhart** [comment]
The thing is, flint_free is the only thing that is allowed to clean up p.

The problem here is that it is making a string out of p without making a
copy of it first. It's just wrapping the actually string returned by Flint
I would guess.

So both solutions are incorrect I think.
