### ISSUE TITLE
Iterate over finite field

### ISSUE THREAD

**Issue by kirtsar** [Nemocas/Nemo.jl#601]
My problem is the following. Suppose i want to run through all of the polynomials of the type
```
f(X) = X^n + aX^2 + bX
```
where a, b are from some finite field F.
I want to find the number of polynomials which have only one root X = 0 of degree 1.

1. Is there any function which gives roots of polynomial? I've ended up with something like:
```
function roots(f)
    return collect(factor(f))
end
```

2. Is there any way to iterate through the field F? I understand that I can simply take primitive element t and iterate using t^k, but i realise that i could not do something like:
```
for t1 in F
    for t2 in F
        g = X^n + t1 * X^2 + t2 * X
        ....
    end
end
```

**Comment by thofma** [comment]
The answer to 1) and 2) is no.

Both is provided by Hecke though. For 1) we do basically the same as you. For 2) you can copy https://github.com/thofma/Hecke.jl/blob/master/src/Misc/FiniteField.jl#L54-L136

We should probably move it over to Nemo sooner or later.

**Comment by fingolfin** [comment]
All resolved
