### ISSUE TITLE
Iterative creation of Finite fields

### ISSUE THREAD

**Issue by kirtsar** [Nemocas/Nemo.jl#602]
Is there any way to create finite fields from irreducible polynomials over other finite fields?
For example:
```
using Nemo
F = GF(2)
R, x = F["X"]
f = x^2 + x + 1                   # irreducible modulo 2
FF = FiniteField(f, "t")       # create F_4
# now i want to iterate with FF as basic field
RR, y = FF["Y"]
g = y^2 + t*y + t                # irreducible over FF
FiniteField(g, "s")             # does not work
```

Sorry i've tried to find chat to discuss Nemo and friends, but didn't find anything, so there will be a lot of "issues" which are basically just questions...

**Comment by thofma** [comment]
Unfortunately not, but it is on our list.

I think @joschmitt made it work somewhere in Hecke, but I cannot find it.

**Comment by joschmitt** [comment]
In Hecke you could do Hecke.field_extension(g) which returns F_16 (in the example) and a map from RR to F_16 with kernel (g).
But this is more or less a workaround. F_16 is constructed as FiniteField(2, 4) and does not "know" that it is a field extension of F_4. This information is only given by the map.

**Comment by fingolfin** [comment]
Seems to be resolved:
```
julia> F = GF(2)
Prime field of characteristic 2

julia> R, x = F["X"]
(Univariate polynomial ring in X over F, X)

julia> f = x^2 + x + 1                   # irreducible modulo 2
X^2 + X + 1

julia> FF, t = finite_field(f, "t")       # create F_4
(Finite field of degree 2 and characteristic 2, t)

julia> RR, y = FF["Y"]
(Univariate polynomial ring in Y over FF, Y)

julia> g = y^2 + t*y + t                # irreducible over FF
Y^2 + t*Y + t

julia> K, s = finite_field(g, "s")
(Finite field of degree 2 over FF, s)

julia> order(K)
16
```
