### ISSUE TITLE
Hashing for multivariate polynomials

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#623]
It is missing :(. We can either implement them in flint, or make a slow version based on the coefficient and exponent vector iterators.

**Comment by wbhart** [comment]
Why would this be slow? We have to iterate over all the data for a hash anyway.

**Comment by thofma** [comment]
I think it has a bad memory footprint. Because it has to construct the exponent vectors one by one, every time allocating an array. Probably I am mistaken.

**Comment by wbhart** [comment]
That could be true. I don't recall either.
