### ISSUE TITLE
calling GF can make a GFField or GaloisField depending on the argument

### ISSUE THREAD

**Issue by rfourquet** [Nemocas/Nemo.jl#650]
```julia
julia> GF(3)
Galois field with characteristic 3

julia> typeof(ans)
Nemo.GaloisField

julia> GF(0x3)
Finite field F_3

julia> typeof(ans)
AbstractAlgebra.GFField{UInt8}
```

This is not necessarily a problem, but I think this should at least be documented, as this can be surprising. It's true that the docs mention only a `GF` constructor for `Int/UInt`, but it's easy to forget that and to end up creating a different type of object by using anothing integer type. 

Another possibility would be to have `Nemo.GF != AbstractAlgebra.GF`. If these functions remain unified, we can consider using `Nemo.GaloisField` for any integer types smaller than `Int/UInt`.

In any case, it would be great to document the difference in performance/behavior between AA's and Nemo's Galois fields.

Also, is it an option to consider depending the Primes package in `AbstractAlgebra` to check for primality for the argument of `GF`?

**Comment by wbhart** [comment]
I think this is not intended. It should always return a Nemo finite field or always an AbstractAlgebra one.

I don't think GF is even intended to return a Conway polynomial finite field. Both should probably return something based on Flint's nmod.

How long does the Primes package take to determine primality for say a 60 bit prime? Has it been tested exhaustively for all 2-pseudoprimes up to 2^64-1 and tested rigorously otherwise?

**Comment by thofma** [comment]
Depending on Primes.jl is not an option.

**Comment by wbhart** [comment]
@thofma What would be the argument against, for primality testing? It doesn't seem too slow. It seems to take about 2.6 ms to check a number around 2^63 for primality (probably a little longer if it is actually prime, but not a lot). It's also pure Julia as far as I can see.

Obviously we don't want to use it for Nemo, but is there a reason to not use it for AbstractAlgebra?

**Comment by thofma** [comment]
1) Yes, it is an external dependency.
2) It will also be a dependency for Nemo/Hecke, although they don't need it.

**Comment by rfourquet** [comment]
> It seems to take about 2.6 ms to check a number around 2^63 for primality

I'm surprised, on my machine it seems to take on average roughly 0.03 ms to check a prime number, and way faster for a non-prime.

> Has it been tested exhaustively for all 2-pseudoprimes up to 2^64-1 and tested rigorously otherwise?

I wouldn't say it's rigorously tested, and I don't think someone tested it exhaustively for all 2-pseudoprimes up to 2^64-1...
Hey, but I realize, it uses `mpz_probab_prime_p` for `BigInt`, from "libgmp", which is distributed with Julia, so we don't even need the package (at least as long as Julia uses GMP for `BigInt`).

> It is an external dependency.

So the bar is very high for external depency?

**Comment by wbhart** [comment]
mpz_probab_prime_p isn't a primality test as far as I'm aware. It's only a probable prime test.

**Comment by wbhart** [comment]
Sorry, you are right, it's 0.026ms. I screwed up the timing.

But for some reason it is now just raising an exception. 

```
julia> function time_primes(n::Int)
          s = 0; for i = 1:n
             if isprime(2^62 - 2*i + 1); s += 1; end
          end; return s
       end
time_primes (generic function with 2 methods)

julia> @time time_primes(1000)
ERROR: InexactError: check_top_bit(UInt64, 9223372038815818933)
Stacktrace:
 [1] throw_inexacterror(::Symbol, ::Any, ::UInt64) at ./boot.jl:567
 [2] check_top_bit at ./boot.jl:581 [inlined]
 [3] toInt64 at ./boot.jl:642 [inlined]
 [4] Type at ./boot.jl:717 [inlined]
 [5] gc_total_bytes at ./util.jl:37 [inlined]
 [6] Base.GC_Diff(::Base.GC_Num, ::Base.GC_Num) at ./util.jl:43
 [7] top-level scope at util.jl:158
```

Not sure what I did wrong there.

**Comment by rfourquet** [comment]
> mpz_probab_prime_p isn't a primality test as far as I'm aware. It's only a probable prime test.

It's definitely a probably prime test, but with a big enough second argument to the function ("reps"), the probability of a wrong answer vanishes, I assumed this would be good enough (and this can be documented).

> But for some reason it is now just raising an exception.

I can't seem to be able to reproduce that...

**Comment by wbhart** [comment]
> > mpz_probab_prime_p isn't a primality test as far as I'm aware. It's only a probable prime test.
> 
> It's definitely a probably prime test, but with a big enough second argument to the function ("reps"), the probability of a wrong answer vanishes, I assumed this would be good enough (and this can be documented).

Absolutely not! There are some pretty serious primality testing folk out there who will absolutely massacre us if we do something like that. A function called isprime MUST guarantee the result is prime.

Opinions vary, but you will quickly discover (because people will loudly tell you) that answers that are highly likely to be correct, but not guaranteed to be correct are only accepted when it is impractical to do anything else!

**Comment by rfourquet** [comment]
> A function called isprime MUST guarantee the result is prime.

I must be missing something, as `Nemo.isprime` calls out to `fmpz_is_probabprime` from "libflint", which doesn't guarantee primality (AFAIU). The docstring of `Nemo.isprime` says 

>  isprime(x::fmpz)
>
>  │  Return true if x is a prime number, otherwise return false.

The compromise I proposed here (but by no means want to impose):
* in the `GF` constructor, use by default a probabilistic primality test to check that the argument is a (probable) prime
* document that even if it works, it's not proven (as we don't have a practical alternative)
* have the option to opt-out, e,g. `GF(4, check=false)`
* use `mpz_probab_prime_p` only internally for the `GF` constructor (no wrapping into an `isprime` exported function).

**Comment by wbhart** [comment]
> > A function called isprime MUST guarantee the result is prime.
> 
> I must be missing something, as `Nemo.isprime` calls out to `fmpz_is_probabprime` from "libflint", which doesn't guarantee primality (AFAIU). The docstring of `Nemo.isprime` says
> 
> > isprime(x::fmpz)
> > │  Return true if x is a prime number, otherwise return false.

That's because there was originally no working isprime in Flint. Now there is, so we should definitely change this. I will open a ticket to make sure it gets done.

**Comment by wbhart** [comment]
> The compromise I proposed here (but by no means want to impose):
> 
> * in the `GF` constructor, use by default a probabilistic primality test to check that the argument is a (probable) prime
> * document that even if it works, it's not proven (as we don't have a practical alternative)
> * have the option to opt-out, e,g. `GF(4, check=false)`
> * use `mpz_probab_prime_p` only internally for the `GF` constructor (no wrapping into an `isprime` exported function).

I don't mind that compromise here, so long as it is clearly documented. After all, it is only used to tell the user they did something stupid. Assuming valid input, the output will still be valid.

**Comment by thofma** [comment]
The `GF` function in Nemo can just call the (to be wrapped) `fmpz_is_prime` function with the option to opt-out. How about that?

**Comment by rfourquet** [comment]
> After all, it is only used to tell the user they did something stupid

Yes I find this is useful, it's easy to be stupid when playing with example at the REPL.

> The GF function in Nemo can just call the (to be wrapped) fmpz_is_prime function with the option to opt-out. 

Sounds good. Currently, `Nemo.GF` already checks for primality, with `n_is_prime` which should never give wrong answers.

**Comment by wbhart** [comment]
Wait, 0x3 is a UInt8? How do I get a UInt with value 3? This is braindead.

I'm going to close the issue anyway, as it seems to only come from faulty Julia behaviour. I thought the problem was that it created the wrong type when using a UInt64. I couldn't care less what it does with a UInt8.

**Comment by rfourquet** [comment]
To create `UInt64(3)`, you can write `0x0000000000000003`, see https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#Integers-1.
This issue is not specifically about `UInt8`, it's about any integer type which is not `Int`, `UInt` or `fmpz`. 
If you don't like the fix at #654, I would still consider there is a small documentation issue that I would like to fix.

**Comment by wbhart** [comment]
Does the doc actually say the wrong thing, i.e. that you can supply any integer type here? We don't generally spend effort on supporting integer types other than the three you named (and the equivalents in Singular, Gap and Polymake. So unless the documentation says something wrong or contradictory, this is a waste of time.

Why on earth does 3 generate an Int64 and 0x3 generate a UInt8 in the first place. This is absolutely braindead. I'm not going to go around documenting stuff like that.

**Comment by rfourquet** [comment]
> Does the doc actually say the wrong thing 

No, which I said in the OP.

>  this is a waste of time

I disagree: @fieker just said earlier today that AA's finite fields are mostly not to be used except basically for testing purposes or playing around, and that `Nemo`'s ones should be used for work. Now I load `Nemo`, I type `F = GF(n)` where `n` has the bad luck to not be one of `Int`, `UInt`, `fmpz`, and voilà, I end up working with `AA`'s finite field by accident. So adding something like "If the integer is not `Int`, `UInt` or `fmpz`, you will get an AA's field" in the docs doesn't look like a waste of time, when considering the possible benefit for the user. This takes a couple of minutes to update the docs. Arguing for such a trivial change takes far more...

> Why on earth does 3 generate an Int64 and 0x3 generate a UInt8 in the first place. This is absolutely braindead. I'm not going to go around documenting stuff like that.

I don't understand why you think someone should go around documenting stuff like that, it's already documented where it should be, in the Julia docs.

**Comment by fieker** [comment]
On Tue, Oct 08, 2019 at 04:48:52AM -0700, Rafael Fourquet wrote:
> > Does the doc actually say the wrong thing 
> 
> No, which I said in the OP.
> 
> >  this is a waste of time
> 
> I disagree: @fieker just said earlier today that AA's finite fields are mostly not to be used except basically for testing purposes or playing around, and that `Nemo`'s ones should be used for work. Now I load `Nemo`, I type `F = GF(n)` where `n` has the bad luck to not be one of `Int`, `UInt`, `fmpz`, and voilà, I end up working with `AA`'s finite field by accident. So adding something like "If the integer is not `Int`, `UInt` or `fmpz`, you will get an AA's field" in the docs doesn't look like a waste of time, when considering the possible benefit for the user. This takes a couple of minutes to update the docs. Arguing for such a trivial change takes far more...
> 
In Nemo you should never get the AA GF. If the int input is the wrong
type, you should get an error.
Maybe we need to not import GF from AA when doing Nemo.

The AA-GFs have no non-trivial support and will (from our side, for the
forseeable future) not get it.
I argued with Bill about this when he implemented them. I understand his
arguments, but to me their existence is a mistake.
What happens was predictable: the existence of GF in AA implies
functionality and behaviour. Which is missing/ wrong.

The only finite fields we can currently support are the ones in Nemo. We
will be forced to deal with Polymake, Gap and Singular, but in AA we can
avoid this.

**Comment by rfourquet** [comment]
> In Nemo you should never get the AA GF. If the int input is the wrong type, you should get an error. Maybe we need to not import GF from AA when doing Nemo.

I agree and this is #654.

**Comment by wbhart** [comment]
In AbstractAlgebra GF(p) is a synonym for ResidueField(ZZ, p), NOT for FiniteField(p, 1, "a"). Note that it does not use a Conway polynomial and it does not return a field and a generator, but just the field.

If this is not the desired behaviour for GF in Flint (@fieker is the one who makes that decision), then it should be removed from AbstractAlgebra, as we want to ensure that people who use AbstractAlgebra don't have to modify their code (much) to "upgrade" to Nemo.

Now that ResidueField exists in AbstractAlgebra, there is no need for GF to exist. I personally like the synonym GF(p) for ResidueField(ZZ, p), but I am not the one who makes the decision here.

**Comment by rfourquet** [comment]
> In AbstractAlgebra GF(p) is a synonym for ResidueField(ZZ, p),

It doesn't seem to be the case:
```julia
julia> GF(3)
Finite field F_3

julia> typeof(ans)
AbstractAlgebra.GFField{Int64}

julia> ResidueField(ZZ, 3)
Residue field of Integers modulo 3

julia> typeof(ans)
AbstractAlgebra.Generic.ResField{BigInt}
```

**Comment by wbhart** [comment]
@rfourquet You are correct that it isn't a synonym in the formal sense. I meant only that it behaves essentially the same way and that one could simply be a synonym for the other (especially since it really only exists for the purposes of having a exact field which is not characteristic 0 in our test code).

Originally there was only GF(p) for this purpose, but we subsequently added ResidueField. So at least the substance of what I said is still correct.

Of course GP(p) is slightly nicer than a formal alias, as it prints the parent nicely and the type is a little easier to grok. But that is neither here nor there, really.
