### ISSUE TITLE
Bug in cyclotomics

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#657]
```
using Nemo
K,zeta6 = CyclotomicField(6,"zeta6");
a = QQ(1,2);
b = 1 - zeta6;
a - b == K(a) - b
```

Reported on my repo ages ago.

**Comment by thofma** [comment]
Weird, I thougt we fixed this this problem in the quadratic case.

**Comment by thofma** [comment]
See https://github.com/wbhart/antic/pull/37

**Comment by wbhart** [comment]
I thought so too. But it still seemed to be there when I checked.
