### ISSUE TITLE
UndefVarError: ZZ not defined

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#662]
Please consider the function below:

    using Nemo
    function P(m, n)
        R, x = PolynomialRing(ZZ, "x")
        function recP(m, n, x)
            haskey(CachePoly, (m, n)) && return CachePoly[(m, n)]
            n == 0 && return R(1)
            p = sum(binomial(m*n, m*k)*recP(m, n-k, x)*x for k in 1:n)
            CachePoly[(m, n)] = p
        end
        n == 0 ? R(1) : recP(m, n, x)
    end
    const CachePoly = Dict{Tuple{Int,Int}, Nemo.fmpz_poly}()
    CoeffLeading(p) = coeff(p, degree(p))
    for m in 0:4
        [CoeffLeading(P(m, n)) for n in 0:6] |> println
    end

This works as expected. However, changing two lines to:

    using Nemo, AbstractAlgebra
    CoeffLeading(p) = AbstractAlgebra.lc(p) 

results in the 
    LoadError: UndefVarError: ZZ not defined

It's not clear to me how to proceed. I thought that the assertion "All univariate polynomial types in Nemo follow the AbstractAlgebra.jl univariate polynomial interface" implies that "AbstractAlgebra.lc()" is compatible with Nemo.

**Comment by wbhart** [comment]
You can't do using Nemo and using AbstractAlgebra. You just do:

using Nemo
import AbstractAlgebra

**Comment by wbhart** [comment]
The other problem is that lc is only defined for multivariate polynomials, not univariates.

At present the function for the leading coefficient of a univariate is lead(p). Thus, the following will make your code work.

```
CoeffLeading(p) = lead(p)
```

And yes, this is something we know about and intend to fix. @fieker just mentioned this one the other day. I'll check and make sure we have a ticket for it.

**Comment by thofma** [comment]
Did this work before with the `ZZ`?

**Comment by PeterLuschny** [comment]
> Did this work before with the `ZZ`?

I dont know. So far I have explicitly called only Nemo functions. By chance I saw the 'lc' function in AbstractAlgebra and tried to use it. Obviously, I do not understand the connection between these two libraries enough.
However, I also found no indication in the Nemo documentation that AbstractAlgebra may only be accessed via import.  I have now decided to call in the future Nemo functions only. In this sense, the above message is of no further relevance to me.

Thank you for the notice!

**Comment by wbhart** [comment]
There isn't much reason to call AbstractAlgebra functions directly if you have Nemo. The one exception would be if you specifically want to call generic functions instead of the Nemo ones, e.g. to do a comparison. Another case would be if you for example wanted a generic matrix over say ZZ rather than a Flint fmpz_mat. This can be useful in some contexts, but it of limited use.

Other than that, almost everything in AbstractAlgebra is already imported into Nemo and made available there. So you certainly don't lose very much by just using Nemo.

**Comment by PeterLuschny** [comment]
>
>  So you certainly don't lose very much by just using Nemo.
>
Yeah, that's actually how I saw it, so I got a little confused about this
happening.
Many thanks to all the developers of these great libraries!

**Comment by wbhart** [comment]
Closing as the issue seems as if it was resolved.
