### ISSUE TITLE
Apply functions from Nemo on vectors

### ISSUE THREAD

**Issue by WT215** [Nemocas/Nemo.jl#675]
Hello,

I would like to do the following:
 `CC = Nemo.ComplexField(64)` and `X=CC([1,2,3])`, then `Nemo.gamma.(X)`. Similar to `SpecialFunctions.gamma.([1,2,3])`.

In short, apply function from Nemo on a vector rather than just a scalar?

PS: I found a solution which is using `broadcast`, but not sure if it is applicable on all functions from Nemo.

Thanks a lot!

**Comment by thofma** [comment]
Yes, we want something like this, but could you tell us what `X` is? I am getting
```julia
julia> X=CC([1,2,3])
ERROR: MethodError: no method matching (::AcbField)(::Array{Int64,1})
```
But the following is working for me:
```julia
julia> X=CC.([1,2,3])
3-element Array{acb,1}:
 1.0000000000000000000 + i*0
 2.0000000000000000000 + i*0
 3.0000000000000000000 + i*0

julia> Nemo.gamma.(X)
3-element Array{acb,1}:
 1.0000000000000000000 + i*0
 1.0000000000000000000 + i*0
 2.0000000000000000000 + i*0
```

**Comment by WT215** [comment]
> Yes, we want something like this, but could you tell us what `X` is? I am getting
> 
> ```julia
> julia> X=CC([1,2,3])
> ERROR: MethodError: no method matching (::AcbField)(::Array{Int64,1})
> ```
> 
> But the following is working for me:
> 
> ```julia
> julia> X=CC.([1,2,3])
> 3-element Array{acb,1}:
>  1.0000000000000000000 + i*0
>  2.0000000000000000000 + i*0
>  3.0000000000000000000 + i*0
> 
> julia> Nemo.gamma.(X)
> 3-element Array{acb,1}:
>  1.0000000000000000000 + i*0
>  1.0000000000000000000 + i*0
>  2.0000000000000000000 + i*0
> ```

`X=CC([1,2,3])` is just a toy example to show what I wanted to achieve but failed. `X=CC.([1,2,3])` works! So there is no need to use `broadcast`. 

Just out of curiosity, `X=CC.([1,2,3])` or `X=broadcast(CC,[1,2,3])` which do you prefer? Or are they the same in terms of efficiency?

Thank you for your quick reply!

**Comment by thofma** [comment]
I think they are all the same in terms of efficiency. The `.` syntax is lowered to broadcasting:
```julia
julia> Meta.@lower gamma.(X)
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.broadcasted(gamma, X)
│   %2 = Base.materialize(%1)
└──      return %2
))))
```
PS: As a third option, there is also `map(CC, [1, 2, 3])`.

**Comment by WT215** [comment]
@thofma Cool! Thanks a lot!
