### ISSUE TITLE
Implement next_prime

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#706]
This is probably the most annoying outstanding issue with our integers

**Comment by wbhart** [comment]
This is normally done by sieving with some small primes and then checking primality of the remaining integers in order, then increasing the size of the sieve if no primes were found. Alternatively one can pick the next possible candidate mod 6 then compute its value mod some small primes. This data is then used to "sieve" for further candidates, one at a time, thus saving one from having to do a lot of reductions of large candidates by those small primes.

**Comment by rfourquet** [comment]
I just needed it today! So, according to your previous comment, I guess you are saying that the algorithn you describe would be better than `fmpz_nextprime`? Would you mind if we expose `fmpz_nextprime` in the meantime?

**Comment by wbhart** [comment]
That function is broken I think. It was written by someone who didn't understand how Flint integers work internally, so it returns wrong answers over some range.
