### ISSUE TITLE
Number theoretic function names

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#708]
The following look like they should all be renamed:

fib -> fibonacci
binom -> binomial
moebiusmu -> moebius_mu
jacobi -> jacobi_symbol
eulerphi -> euler_phi
numpart -> number_of_partitions
fac -> factorial
risingfac -> rising_factorial (see below)
sigma -> divisor_sigma

Questions, complaints, suggestions? Should I just go ahead with these?

**Comment by wbhart** [comment]
There's also fac, but Julia already uses fac for this, so we are probably stuck with that for now.

**Comment by rfourquet** [comment]
For `fac`: it currently accepts an `Int` and outputs an `fmpz`. So if it's renamed `factorial`, it should accept an `fmpz`, as `Base.factorial` already accepts an `Int`.
For `binom`, you might want to rename it to `binomial`, which is the name in `Base`. (But same remark as above, `Nemo`'s version could be used only if at least one of the argument is an `fmpz`).

**Comment by wbhart** [comment]
It's really irritating that Julia defines these in Base. At least those are probably defined using GMP and so are likely efficient.

**Comment by wbhart** [comment]
I think we will have to define Nemo.factorial and just not export it, since I can't think of another reasonable name for it.

**Comment by rfourquet** [comment]
Yes Julia uses GMP when the input is `BigInt`. But otherwise its output type is equal to its input type, which means `factorial(30)` overflows with an error. It looks fine to me, I remember you pretty much prefer this kind of type preservation, rather than a behavior like Julia's `/` which returns a `Float64` even on `Int` input. So I would suggest just extending the `Base` function.

**Comment by wbhart** [comment]
Our factorial function takes an Int and returns an fmpz. I simply made it Nemo.factorial in case anyone wants to use that version instead of the default provided by Base.

A factorial function which takes an Int and returns an Int is not very useful though, I have to say. I think you can do about factorial(20) or so before it overflows.

**Comment by wbhart** [comment]
Actually a number of our functions have this property. They take an Int or pair of Ints and return an fmpz. This seems like the only useful functionality to have in Oscar, so I just left it that way.

**Comment by rfourquet** [comment]
> A factorial function which takes an Int and returns an Int is not very useful though, I have to say.

Yes I was thinking silently the same. Having `Nemo.factorial` makes sense to expose a functionality which exists anyway. I'm just a little worried then by the discrepancy between e.g. `factorial(::int) -> Int` but `fibonacci(::Int) -> fmpz` (when `factorial` is called unqualifed, i.e. it's `Base` version). But this discussion would belong to another issue.

**Comment by wbhart** [comment]
Yep, an issue on the Julia GitHub. :-)
