### ISSUE TITLE
Access violation at fmpz_poly_get_str_pretty

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#716]
I reported similar errors previously. But this time it might be easier to track the error down.
I am on Windows 64. The setup are two files.

####################### FILE 1

    (@__DIR__) ∉ LOAD_PATH && push!(LOAD_PATH, (@__DIR__))
    module NemoBugMain
    using Nemo
    export OSPolynomials
    const CacheP = Dict{Tuple{Int,Int}, Nemo.fmpz_poly}()
    function OSPolynomials(m::Int, n::Int)
        R, x = PolynomialRing(ZZ, "x")
        function recP(m, n)
            n == 0 && return R(1)
            haskey(CacheP, (m, n)) && return CacheP[(m, n)]
            p = sum(binom(m * n, m * k) * recP(m, n - k) * x for k ∈ 1:n)
            CacheP[(m, n)] = p
        end
        recP(m, n)
    end
    OSPolynomials(2, 5) |> println
    end

####################### FILE 2

    (@__DIR__) ∉ LOAD_PATH && push!(LOAD_PATH, (@__DIR__))
    module NemoBug
    using NemoBugMain
    OSPolynomials(2, 5) |> println
    end

############################ RESULT
Starting Julia...
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.0-rc4.1 (2019-10-15)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

### --- Executing file 1
Welcome to Nemo version 0.15.1
Nemo comes with absolutely no warranty whatsoever
113400*x^5+75600*x^4+13230*x^3+510*x^2+x
#### --- Executing file 2
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x3017b97e -- _fmpz_poly_get_str_pretty at /workspace/srcdir/flint2/fmpz_poly\get_str_pretty.c:44
in expression starting at C:\Users\Home\JuliaProjects\IntegerSequences.jl\src\nemobug2.jl:5
_fmpz_poly_get_str_pretty at /workspace/srcdir/flint2/fmpz_poly\get_str_pretty.c:43
show at C:\Users\Home\.julia\packages\Nemo\qzx0m\src\flint\fmpz_poly.jl:76
print at .\strings\io.jl:35
print at .\strings\io.jl:46
println at .\strings\io.jl:73
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2130 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
println at .\coreio.jl:4
|> at .\operators.jl:854
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2130 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
do_call at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:328
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:417
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:368 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:764
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:888
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000002630CA0F)
unknown function (ip: 0000000000000000)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:814
jl_eval_module_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:181
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:640
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\ast.c:873
include_string at .\loading.jl:1075
#139 at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:138
withpath at C:\Users\Home\.julia\packages\CodeTools\xGemk\src\utils.jl:30
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2130 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
withpath at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:47
#138 at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:135 [inlined]
with_logstate at .\logging.jl:395
with_logger at .\logging.jl:491 [inlined]
#137 at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:134 [inlined]
hideprompt at C:\Users\Home\.julia\packages\Atom\lBERI\src\repl.jl:85
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2136 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
macro expansion at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:133 [inlined]
macro expansion at C:\Users\Home\.julia\packages\Media\ItEPc\src\dynamic.jl:24 [inlined]
#136 at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:122
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2130 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
handlemsg at C:\Users\Home\.julia\packages\Atom\lBERI\src\comm.jl:164
unknown function (ip: 0000000017B13BD2)
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2130 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
jl_f__apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:627
#19 at .\task.jl:333
unknown function (ip: 0000000017B1044E)
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2130 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\task.c:659
Allocations: 23420235 (Pool: 23414275; Big: 5960); GC: 23

Julia has exited. Press Enter to start a new session.

**Comment by wbhart** [comment]
Thanks for the report. I can't find a problem in the code. It seems that it is segfaulting on the function that is checking to see if a coefficient in the polynomial is zero, which simply dereferences a value (in fact, it is essentially just reading a value from the coefficient array).

It's pretty hard to believe that array is not allocated correctly, so I don't immediately see where the problem could be.

This sort of thing can happen for other reasons, e.g. a missing FLINT_DLL in a .h file somewhere. But again, you are only using basic, well-tested stuff here (just addition and scalar multiplication if I am not mistaken). It's hard to imagine something wrong in any of that.

So it remains a mystery for now. But we'll see if we can replicate it and track it down. Probably we'll need to attach a debugger.

**Comment by wbhart** [comment]
The other possibility is the polynomial is being cleaned up before it should.

Could you try running the code with a semicolon to supress printing and just call some other functions on the polynomial, such as length and accessing each of the coefficients.

**Comment by wbhart** [comment]
Also, do you get the same problem if you do println(OSPolynomials(2, 5)) instead, or

p = OSPolynomials(2, 5)
println(p)

Just checking it's not some kind of bizarre Julia bug.

**Comment by wbhart** [comment]
Another possibility: are you using a source build or binaries for Nemo? If you are using a source build, try doing a make clean; make install in the flint2 directory.

**Comment by PeterLuschny** [comment]
The same with all versions of println.
I use the binaries of Nemo.

> The other possibility is the polynomial is being cleaned up before it should.

The following version seems to point in this direction. File 1 as above. File 2 is:

    (@__DIR__) ∉ LOAD_PATH && push!(LOAD_PATH, (@__DIR__))
    module NemoBug
    using Nemo, NemoBugMain
    p = OSPolynomials(2, 5)
    println([div(coeff(p, k), fac(k)) for k ∈ 0:5])
    end

[ Info: Precompiling NemoBugMain [top-level]

Welcome to Nemo version 0.15.1

Nemo comes with absolutely no warranty whatsoever

113400*x^5+75600*x^4+13230*x^3+510*x^2+x

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x3096f08d -- fmpz_set at /workspace/srcdir/flint2/fmpz\set.c:23
in expression starting at C:\Users\Home\JuliaProjects\IntegerSequences.jl\local\nemobug2.jl:6
fmpz_set at /workspace/srcdir/flint2/fmpz\set.c:20
coeff at C:\Users\Home\.julia\packages\Nemo\qzx0m\src\flint\fmpz_poly.jl:38
unknown function (ip: 00000000182BADFD)
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2136 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
#1 at .\none:0
iterate at .\generator.jl:47 [inlined]
collect at .\array.jl:620
unknown function (ip: 00000000182BA71E)
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2136 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
do_call at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:328
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:417
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:368 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:764
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:888unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 0000000010617A8F)
unknown function (ip: 0000000000000008)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:814
jl_eval_module_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:181
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:640
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\ast.c:873
include_string at .\loading.jl:1075
#139 at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:138
withpath at C:\Users\Home\.julia\packages\CodeTools\xGemk\src\utils.jl:30
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2136 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
withpath at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:47
#138 at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:135 [inlined]
with_logstate at .\logging.jl:395
with_logger at .\logging.jl:491 [inlined]
#137 at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:134 [inlined]
hideprompt at C:\Users\Home\.julia\packages\Atom\lBERI\src\repl.jl:85
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2136 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
macro expansion at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:133 [inlined]   
macro expansion at C:\Users\Home\.julia\packages\Media\ItEPc\src\dynamic.jl:24 [inlined]#136 at C:\Users\Home\.julia\packages\Atom\lBERI\src\eval.jl:122
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2136 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
handlemsg at C:\Users\Home\.julia\packages\Atom\lBERI\src\comm.jl:164
unknown function (ip: 0000000018293BD2)
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2130 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
jl_f__apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:627
#19 at .\task.jl:333
unknown function (ip: 000000001829044E)
_jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2130 [inlined]
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2300
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\task.c:659
Allocations: 18255588 (Pool: 18250301; Big: 5287); GC: 17

Julia has exited. Press Enter to start a new session.

**Comment by wbhart** [comment]
Yes, thanks. I think that narrows it down to three possibilities:

* faulty windows binaries (on our side)
* polynomial is not allocated correctly
* polynomial is being cleaned up early (could be our bug or a Julia bug)

To narrow it down to just 2 possibilities, could you instead have a loop which prints each coefficient of the polynomial in turn, starting with coeff 0 (if that won't be too much printing), to see if only one of the coefficient accesses causes an EAV.

**Comment by wbhart** [comment]
And if any of the coefficients actually prints, could you insert a GC.gc() before the print loop to see if it still happens.

**Comment by PeterLuschny** [comment]
So the setup now is:

    module NemoBug
    using Nemo, NemoBugMain
    p = OSPolynomials(2, 5)
    #GC.gc()  # does not seem to make any difference
    for k in 0:5
        c = coeff(p, k)
        println(c)
    end
    end

Executing this several times I got the first two times
Exception: EXCEPTION_ACCESS_VIOLATION at 0x3297f08d 
-- fmpz_set at /workspace/srcdir/flint2/fmpz\set.c:23
Thereafter things worked as expected several times.

Then I completely shut down the computing environment and
restarted. Again only exceptions, in whatever minor variant
(GC or not). So things are not deterministic.

Did I actually make it clear enough (the trace also shows it) 
that things seems to work in the main file, NemoBugMain? It 
only doesn't work when called from the second file. Here are
the steps:

[ Info: Precompiling NemoBugMain [top-level]
Welcome to Nemo version 0.15.1
Nemo comes with absolutely no warranty whatsoever
113400*x^5+75600*x^4+13230*x^3+510*x^2+x <-- this output is from NemoBugMain
Please submit a bug report ... <-- this output from the second file

**Comment by wbhart** [comment]
So, just to clarify, you either get zero coefficients printed or all of them, never just some of them before the exception?

**Comment by PeterLuschny** [comment]
Yes, in the two, irreducible cases when it worked, it showed all coefficients.

**Comment by PeterLuschny** [comment]
I meant 'irreproducible cases' ...

**Comment by PeterLuschny** [comment]
I think I found the cause: If I eliminate the cache for the 
OSPolynomials then everything works. So it's probably just a 
programming mistake of mine to think it works the way I did it. 
If so, how do I do it right?

**Comment by PeterLuschny** [comment]
I've now checked with the well-known competitor to see how 
that works there. I did not experience any difficulties. 
For what it's worth the timing on an old laptop: 

    def OSPolynomials(m, n):
        R = PolynomialRing(ZZ, "x")
        @cached_function
        def recP(m, n):
            if n == 0: return R(1) 
            s = sum(binomial(m*n, m*k)*recP(m, n-k)*x for k in (1..n))
            return expand(s)
        return recP(m, n)

timeit('OSPolynomials(2, 100)')
5 loops, best of 3: 2.99 s per loop

**Comment by wbhart** [comment]
Very interesting. I wonder what was wrong with your original version. I'll try to look into it this week and see if I can figure out the exact problem you were having.

**Comment by PeterLuschny** [comment]
Maybe you misunderstood. Nemo's behavior is still defective, nothing 
changed here. And caching is absolutely necessary for larger input values. 
I was just curious to see how *SageMath* performs in this situation.

**Comment by wbhart** [comment]
One thing I thought of to try is passing the polynomial ring in, rather than create it in the function.

The caching code looks fine to me, and I don't see why it would trigger this problem.

**Comment by PeterLuschny** [comment]
> One thing I thought of to try is passing the polynomial ring in, rather than create it in the function.

I tried several variants of this idea but no difference.

> The caching code looks fine to me, and I don't see why it would trigger this problem.

To check I installed Memoize.jl and used the macro: 
@memoize function OSPolynomials(m::Int, n::Int)
The result was the same access violation. But it produced a warning:

[ Info: Precompiling NemoBugMain [top-level]
Welcome to Nemo version 0.15.1
Nemo comes with absolutely no warranty whatsoever
WARNING: eval into closed module Memoize:
Expr(:const, Symbol("##OSPolynomials_memoized_cache") = Expr(:call, :IdDict)) ** incremental compilation may be fatally broken for this module **        

I don't understand this warning but found a post on discourse that this might be related to some initialization of the PackageCompiler. Anyway, it might only apply if Memoize's macro is used.

**Comment by PeterLuschny** [comment]
It seems that the solution is simpler than I thought:

    function OSPolynomials(m::Int, n::Int):: Nemo.fmpz_poly
        CacheP = Dict{Tuple{Int,Int}, Nemo.fmpz_poly}()
        R, x = PolynomialRing(ZZ, "x")
        function recP(m, n)
            n == 0 && return R(1)
            haskey(CacheP, (m, n)) && return CacheP[(m, n)]
            CacheP[(m, n)] = sum(binom(m * n, m * k) * recP(m, n - k) * x for k ∈ 1:n)
        end
        recP(m, n)
    end

Thank you for your attention and help! I appreciate it!

**Comment by wbhart** [comment]
I haven't even got a guess why that is helping. This seems like a rare corner case Julia bug at this point.

**Comment by wbhart** [comment]
Looking back on this now, I think this has to do with the module declaration. We see this from time-to-time as things are referred to that were created in a module instead of in the __init__ function for the module. Julia creates them as requested when the module is created, but then precomputation causes them to segfault when referred to later, as they are then just dead pointers. Only things created in the __init__ function are actually valid for use from other modules.

As this is a standard Julia issue and nothing to do with Nemo, I'm going to close this issue.
