### ISSUE TITLE
Empty sum not defined for Nemo.fmpz

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#742]
Hello, please consider:

    using Nemo
    A(dim, T) = Array{Array{T,1},1}(undef, dim)

Using BigInt:

    B = A(2, BigInt)
    B[1] = BigInt[]
    B[2] = BigInt[1,2,3,4]
    [sum(b) for b in B]

    2-element Array{BigInt,1}:
      0
      10
 
Using Nemo:
 
    N = A(2, fmpz)
    N[1] = fmpz[]
    N[2] = fmpz[1,2,3,4]
    [sum(b) for b in N]

    MethodError: no method matching zero(::Type{fmpz})

Possible solution:

    import Base.zero
    Base.zero(::Type{fmpz}) = ZZ(0)

Now it works:

    N = A(2, fmpz)
    N[1] = fmpz[]
    N[2] = fmpz[1,2,3,4]
    [sum(b) for b in N]

    2-element Array{fmpz,1}:
     0 
     10
 
Is it possible to relieve the user of this burden?

**Comment by wbhart** [comment]
We can only do this for fmpz and fmpq. It's not possible for any other Nemo types.

I'm actually a little surprised this isn't defined. I thought we had defined it already. But perhaps it caused problems and we had to remove it.

I'll see if anyone else comments on this before adding it.

**Comment by wbhart** [comment]
No comments from anyone. So I'll add this now. But please note it cannot be made to work anywhere except fmpz and fmpq.

**Comment by PeterLuschny** [comment]
I admit that it is not mandatory that Nemo.fmpz behaves like 
BigInt in Julia, but I think it is very desirable that fmpz is 
as interchangeable with BigInt as possible.

At any rate, I am very grateful for this addition and I will 
keep it for myself. Conversely, in the past I have had to point
out the difference in some docs (and on my blog), that here 
fmpz must be supplemented, which only led to disbelief.

Thanks again!
