### ISSUE TITLE
*Massive* regression in nf_elem adhoc binary tests

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#743]
The tests are taking waaaaay longer than they were. Either there has been a massive regression in the AbstractAlgebra/Nemo library code or the tests have been modified in a way that makes them take forever.

If anyone knows what it is, could you please make a PR to fix it. I don't see anything obvious, except for the fact that it does 100 tests for each of a pile of explicit primes. I don't know if this is how it used to be or if it has been changed recently.

Just lowering the number of iterations here is not enough. We need to track down the actual source of the regression and once it is understood, fix it.

**Comment by rfourquet** [comment]
The tests which take a long time were added in #661, it's probably not a problem with library code.
