### ISSUE TITLE
Version in welcome message

### ISSUE THREAD

**Issue by ulthiel** [Nemocas/Nemo.jl#757]
I installed the most recent Nemo v0.16.0 but the welcome message after "using Nemo" reads

```
Welcome to Nemo version 0.15.2-dev

Nemo comes with absolutely no warranty whatsoever
```

**Comment by wbhart** [comment]
We've noticed this and @thofma is working on fixing it

**Comment by thofma** [comment]
Fixed in https://github.com/Nemocas/Nemo.jl/pull/758
