### ISSUE TITLE
Setting flint memory functions interacts with other packages using Flint

### ISSUE THREAD

**Issue by Joel-Dahne** [Nemocas/Nemo.jl#759]
Nemo sets the memory functions of Flint to Julia versions
```julia
ccall((:__flint_set_memory_functions, libflint), Nothing,
    (Ptr{Nothing},Ptr{Nothing},Ptr{Nothing},Ptr{Nothing}),
    cglobal(:jl_malloc),
    cglobal(:jl_calloc),
    cglobal(:jl_realloc),
    cglobal(:jl_free))
```
This interacts with other Julia packages that make use of Flint. I noticed this while using both Nemo and [ArbNumerics](https://github.com/JeffreySarnoff/ArbNumerics.jl) at the same time. The one which is loaded the first works and the one loaded later crashes.
```julia
using ArbNumerics
using Nemo
x = ArbReal(5) # Works
y = RealField()(5) # Crashes
```
```julia
using Nemo
using ArbNumerics
x = RealField()(5) # Works
y = ArbReal(5) # Crashes
```

It does work if the code which sets the Flint memory functions is commented out or if Julia is started with `NEMO_THREADED=1` (in which case the memory functions are not changed). 

I'm not sure how to handle this, changing the memory functions seems reasonable to me, but that the very least this could be documented. In have only tried with Flint but since the memory functions for GMP are also changed it's possible that any library using GMP directly might be affected.

Tested using both Nemo 0.16.1 and 0.16.2-dev.

**Comment by wbhart** [comment]
The best way to handle this would be to make a single package Flint.jl which just wraps Flint and then have other packages depend on it. But for whatever reason, we didn't do this.

It's not going to happen now anyway. I agree the best we can do now is to write something somewhere in the docs. Not that anyone will actually read it.

The other solution might be to have ArbNumerics also set the memory functions to the Julia ones.

**Comment by Joel-Dahne** [comment]
Most likely no user would read it if it was in the docs but maybe some developer of another package which is trying to figure out why their package crashes when run together with Nemo.

Having ArbNumerics switch would only partially solve the problem. Then you would run into the reversed problem if NEMO_THREADED is used since then Nemo would not do this anymore. You would need both of the packages to have the exact same behavior, probably not realistic. I don't really understand why Nemo switches depending on if it is run threaded or not.

In practice this is probably not a problem most people would encounter. Most of the time you would use either ArbNumerics or Nemo, not both. In my case I'm trying to switch from ArbNumerics to Nemo so then I need to run the at the same time.

**Comment by wbhart** [comment]
It switches due to a bug in Julia. It's been open for a very long time, but will eventually be resolved and we will be able to remove the distinction.

**Comment by thofma** [comment]
We can ignore NEMO_THREADED. It is experimental.

Does the issue persists if ArbNumerics.jl also sets the memory functions? At the moment it does not (although it really should).

**Comment by Joel-Dahne** [comment]
Adding the code
```julia
ccall(@libflint(__flint_set_memory_functions), Nothing,
      (Ptr{Nothing},Ptr{Nothing},Ptr{Nothing},Ptr{Nothing}),
      cglobal(:jl_malloc),
      cglobal(:jl_calloc),
      cglobal(:jl_realloc),
      cglobal(:jl_free))
```
to the init function of ArbNumerics does indeed make them work together. With NEMO_THREADED=1 they go back to crashing.

But if we ignore NEMO_THREADED then I guess the most reasonable thing would be get  ArbNumerics to do the same initialization. I can create an issue/pull request for it. Do you know where I can find some documentation about why this should be done? To have some argument of implementing the change other than "Nemo is doing it like that".

**Comment by thofma** [comment]
I have not found it in the docs, but the simple reason is to make the julia garbage collector aware of the memory allocated by external libraries. Base itself does it for example here for GMP: https://github.com/JuliaLang/julia/blob/51e29d0a3cdb2a532055007755076c53a23ec520/base/gmp.jl#L100-L104
