### ISSUE TITLE
sign changes the type

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#765]
In Julia, 

```
typeof(sign(BigInt(12))) == BigInt
```

In Nemo currently:

```
typeof(sign(fmpz(12))) == Int
```

I just made a PR to do sign for rational and without checking made the sign the same type as the rational, i.e.. fmpq, in line with Julia.

Now we need to figure out which one to change.

What is everyone's opinion?

**Comment by wbhart** [comment]
Note that checking if something is bigger than or smaller than zero can use > 0 or < 0. So sign is likely used in a different context where one presumably wants the type to stay the same. I personally think Julia might have it right here. Though I am not strongly persuaded either way.

**Comment by rfourquet** [comment]
I agree with your last comment, I don't see a strong use case for returning an `Int` (besides of course saving memory allocation) and breaking the expectation set by Julia (although this is not explicitly documented (in the docstring at least) that it should return the same type as the input).

**Comment by wbhart** [comment]
I'm inclined to change the type returned by sign(::fmpz) to fmpz unless someone has a reason why they don't want this change.

(This issue came up when documenting and testing Oscar, and it would be nice to have consistency there.)
