### ISSUE TITLE
div of fractions inconsistent with Julia and gcd

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#767]
```
julia> div(QQ(2, 3), QQ(1, 5))
10//3

julia> div(2//3, 1//5)
3
```

Julia takes Euclid's definition for division, just as it does for gcd. We take Euclid's definition for gcd but use exact division for fractions, which is inconsistent as div is the operation for "Euclidean division", not exact division.

**Comment by albinahlback** [comment]
Sorry if I'm totally wrong here, but isn't Julia's definition wrong? I mean, I think that the rational numbers are an Euclidean domain, and therefore `div` should act on the rationals -- thus return `10//3`.

https://en.wikipedia.org/wiki/Euclidean_division#In_Euclidean_domain.

**Comment by wbhart** [comment]
Julia is not wrong, just differently defined. They think the div function should return an integer (instead of a floating point number as per /), i.e. it is not Euclidean division for them. Their docstring doesn't say that it is, so no problem there.

**Comment by wbhart** [comment]
Apparently we are no longer in conflict with Julia's definition because our function is no longer called.

I'm unsure if we removed it or if julia just requires div(::fmpq, ::fmpq, ::RoundingMode{:ToZero}) to be defined now.

Either way, the problem has gone away by accident, so I'm closing the ticket.
