### ISSUE TITLE
Include source code with binary build of Nemo.jl

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#773]
A source build of Singular fails if flint.h is not found. The source code should in any case be distributed if git is install.

We could check git --version returns something and if so, check out the Flint source code. If that fails, we could print a warning stating that source is not needed for a binary build, but source builds of downstream packages may not be possible.

**Comment by thofma** [comment]
Maybe I am misunderstanding, but after a binary build, flint.h is in deps/usr/include/flint/flint.h.

Do you mean that we should download the source even if we just download the binaries?

**Comment by wbhart** [comment]
Oh right, I completely forgot about this ticket. The issue is actually a bug in autotools in Singular. Hans and I have completely run out of ideas for how to fix it. We are going to try to find another way in the new year.

Basically automake is not putting the correct Nemo directories in, even though Hans has specified them explicitly in the Singular build system, and we pass them to Singular's configure.

Technically we legally need to include the source code, but it is documented that the user gets this if they do a source build, so I'm not so worried about this just now. I'll leave this ticket open until we get around to sorting all that out.

**Comment by fingolfin** [comment]
Obsolete since we use BinaryBuilder these days.
