### ISSUE TITLE
(0//1)^-1 happily returns a result

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#774]
```
julia> QQ(0)^-1
1//0

julia> QQ(0)^-2
1//0
```

This is consistent with Julia, but I personally think this is just incorrect. An exception should be raised here.

```
(0//1)^0 == 1
```

is defensible. I don't see how (0//1)^-1 == 1 is defensible.

**Comment by wbhart** [comment]
Naturally for

```
0^-1
```

Julia returns Inf and for

```
2^-2
```

Julia returns 0.25. Another frustration for any sensible algebraic system.

**Comment by rfourquet** [comment]
> Another frustration for any sensible algebraic system.

But remember though that literal exponents are special cased (`literal_pow`), many people don't like that, but this is a particular case. Otherwise, exponentiation is input/output-type-stable: 
```julia
julia> 0^Int(-1)
ERROR: DomainError with -1:
Cannot raise an integer x to a negative power -1.
Make x or -1 a float by adding a zero decimal (e.g., 2.0^-1 or 2^-1.0 instead of 2^-1), or write 1/x^1, float(x)^-1, x^float(-1) or (x//1)^-1
```

**Comment by wbhart** [comment]
It still happily divides by zero:

```
(0//1)^Int(-1)
```

**Comment by rfourquet** [comment]
> It still happily divides by zero:

Yeah I discovered that recently, you can even directly do `1//0` without error :-/

**Comment by wbhart** [comment]
My mistake. It is returning 1//0 in both cases, which is fine, except for the fact that possibly some of our rational functions assume the denominator can't be zero.

I'll check this and open a ticket for those if necessary.
