### ISSUE TITLE
How to parse expression from string?

### ISSUE THREAD

**Issue by zhaoli-IHEP** [Nemocas/Nemo.jl#781]
I was wondering if it is possible to parse an expression string. 

For example,
```julia
R, x = PolynomialRing(ZZ, "x")
f = R.parse("1+x") # something like this?

```

**Comment by wbhart** [comment]
Not at the moment. The best you can do is to just use Julia's eval.

f = eval(:(1 + x))

Of course you can build up expressions like a string.

I believe there is code in Flint for parsing multivariate expressions, but not for univariates. And it's not hooked up to Nemo at present.

**Comment by thofma** [comment]
You can also work directly with strings:
```julia
eval(Meta.parse("x + 1"))
```

**Comment by thofma** [comment]
Note that this will have some scoping issues, so it is not really equivalent to something like `R("x+1")`.

**Comment by zhaoli-IHEP** [comment]
> Note that this will have some scoping issues, so it is not really equivalent to something like `R("x+1")`.

Can you show more detail about this scoping issue? I do not fully understand it.
Thank you.

**Comment by wbhart** [comment]
As far as I understand it, eval happens at the top level of the current module, whatever that is. It doesn't happen inside the current function, for example. It's fine if you do this in the REPL, but if you do it inside a function or a package, it might not evaluate where you want it to.

**Comment by thofma** [comment]
Yes. For example:
```julia
julia> x = 2
2

julia> function f()
         Qx, x = PolynomialRing(QQ, "x")
         return eval(Meta.parse("x + 1"))
       end
f (generic function with 1 method)

julia> f()
3
```

Or in a new session:
```julia
julia> function f()
         Qx, x = PolynomialRing(QQ, "x")
         return eval(Meta.parse("x + 1"))
       end
f (generic function with 1 method)

julia> f()
ERROR: UndefVarError: x not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] eval at ./boot.jl:328 [inlined]
 [3] eval(::Expr) at ./client.jl:404
 [4] f() at ./REPL[2]:3
 [5] top-level scope at none:0
 
```

**Comment by zhaoli-IHEP** [comment]
> Yes. For example:
> 
> ```julia
> julia> x = 2
> 2
> 
> julia> function f()
>          Qx, x = PolynomialRing(QQ, "x")
>          return eval(Meta.parse("x + 1"))
>        end
> f (generic function with 1 method)
> 
> julia> f()
> 3
> ```
> 
> Or in a new session:
> 
> ```julia
> julia> function f()
>          Qx, x = PolynomialRing(QQ, "x")
>          return eval(Meta.parse("x + 1"))
>        end
> f (generic function with 1 method)
> 
> julia> f()
> ERROR: UndefVarError: x not defined
> Stacktrace:
>  [1] top-level scope at none:0
>  [2] eval at ./boot.jl:328 [inlined]
>  [3] eval(::Expr) at ./client.jl:404
>  [4] f() at ./REPL[2]:3
>  [5] top-level scope at none:0
>  
> ```

Thank you!
