### ISSUE TITLE
Not all FlintRationalField() are born equal

### ISSUE THREAD

**Issue by johannes-hoffmann** [Nemocas/Nemo.jl#783]
Probably due to caching, the following holds:
```
julia> PolynomialRing(FlintRationalField(), "x") == PolynomialRing(FlintRationalField(), "x")
true
```
But the same cannot be said for the underlying field of rational numbers:
```
julia> FlintRationalField() == FlintRationalField()
false
```
In particular:
```
julia> QQ == FlintRationalField()
false
```
Similar for `ZZ` and friends. Is this intentional, and if so, why?

**Comment by thofma** [comment]
I don't think this is intentional. Looks like a bug in the caching.
