### ISSUE TITLE
Cannot divide field elements

### ISSUE THREAD

**Issue by kirtsar** [Nemocas/Nemo.jl#785]
```
using Nemo
R, x = PolynomialRing(QQ, "X")
K, a = NumberField(x^2 + 1, "a")
a/1                    # does not work
a/(a + 1)           # does not work
a * inv(a + 1)    # works
```
the question is why there are no fallback behaviour like:
```
Base./(a, b) = a * inv(b)
```

Although I do not understand how to check whether the element is prime or not:
```
factor(K(2))     # not working
isprime(K(2))  # not working
```

**Comment by thofma** [comment]
You want

**Comment by wbhart** [comment]
/ is floating point division. Please use div or divexact.

**Comment by thofma** [comment]
Also `//` sould work.

**Comment by wbhart** [comment]
What would be the definition of prime for an element of a field?

Perhaps you want to look at Hecke if you want to factor over some number ring.

Yes, @thofma is correct. If you want to construct a fraction, the way to do that in Julia is //

**Comment by kirtsar** [comment]
`div` does not work also:
```
div(a, 1)   # ERROR: MethodError: no method matching div(::nf_elem, ::Int64)
div(a, K(1)) ERROR: MethodError: no method matching div(::nf_elem, ::nf_elem)
```

**Comment by kirtsar** [comment]
@wbhart 
Sorry, what I was trying is to factor 2 in Z[i], and I didn't succeded

**Comment by wbhart** [comment]
The div function will probably be added for nf_elem in the future. It is currently missing.

However, Z[i] is a ring of integers so you need Hecke.jl to factor this, Nemo can't do it.

**Comment by wbhart** [comment]
Of course divexact works, so use that for now.
