### ISSUE TITLE
Exponentiation of gfp_fmpz_elem

### ISSUE THREAD

**Issue by defeo** [Nemocas/Nemo.jl#793]
I'm confused by `gfp_fmpz_elem`, I can't seem to raise to a `BigInt` or `ZZ` power. Wasn't the type of `y` in:

https://github.com/Nemocas/Nemo.jl/blob/d738d5602644cb0e65c0838379d319ce17888a03/src/flint/gfp_fmpz_elem.jl#L197

meant to be `Interger`?

**Comment by defeo** [comment]
Reading the code more in detail, I think there's simply a definition missing:

```julia
function ^(x::gfp_fmpz_elem, y::fmpz)
   R = parent(x)
   if y < 0
      x = inv(x)
      y = -y
   end
   d = fmpz()
   ccall((:fmpz_mod_pow_fmpz, :libflint), Nothing,
	 (Ref{fmpz}, Ref{fmpz}, Ref{fmpz}, Ref{fmpz_mod_ctx_struct}),
						 d, x.data, y, R.ninv)
   return gfp_fmpz_elem(d, R)
end
```

**Comment by thofma** [comment]
Yes, we should just add this.

**Comment by wbhart** [comment]
Agreed.
