### ISSUE TITLE
Make `matrix(...)` more discoverable

### ISSUE THREAD

**Issue by thchr** [Nemocas/Nemo.jl#797]
I was testing for equivalence of two bases `A` and `B`, using `cansolve(A, B)` and ran into this oddity, illustrated by this example:

```julia
using Nemo 

Am = [0 -1 0 0 0 0 0 1 1; 0 1 0 0 0 0 0 0 0; 0 0 0 0 0 -1 0 1 1; 0 0 0 0 0 1 0 0 0; 0 0 0 -1 0 0 0 1 1; 0 0 0 1 0 0 0 0 0; -1 0 0 0 0 0 0 1 1; 1 0 0 0 0 0 0 0 0; 0 0 -1 0 0 0 0 1 1; 0 0 1 0 0 0 0 0 0; 0 0 0 0 -1 0 0 1 1; 0 0 0 0 1 0 0 0 0; 0 0 0 0 0 0 -1 1 1; 0 0 0 0 0 0 1 0 0; 0 0 0 0 0 0 0 1 0; 0 0 0 0 0 0 0 0 1]
Bm = [0 0 0 0 0 0 0 0 1; 0 0 0 0 0 0 0 1 0; 0 0 0 0 0 0 1 0 0; 0 0 0 0 0 0 -1 1 1; 0 0 0 0 0 1 0 0 0; 0 0 0 0 0 -1 0 1 1; 0 0 0 0 1 0 0 0 0; 0 0 0 0 -1 0 0 1 1; 0 0 0 1 0 0 0 0 0; 0 0 0 -1 0 0 0 1 1; 0 0 1 0 0 0 0 0 0; 0 0 -1 0 0 0 0 1 1; 0 1 0 0 0 0 0 0 0; 0 -1 0 0 0 0 0 1 1; 1 0 0 0 0 0 0 0 0; -1 0 0 0 0 0 0 1 1]

sizeAm = size(Am); sizeBm = size(Bm)

A′ = MatrixSpace(ZZ, sizeAm...)(Am)
B′ = MatrixSpace(ZZ, sizeBm...)(Bm)

A = fmpz_mat(sizeAm..., Am)
B = fmpz_mat(sizeBm..., Bm)

size(A)                                # (16,9)
size(A) == size(B) == sizeAm == sizeBm # true 
A == A′                                # true
B == B′                                # true

Nemo.cansolve(A′, B′)                  # Succeeds
Nemo.cansolve(A, B)                    # Fails with ERROR: UndefRefError: access to undefined reference

```

I had imagined it would be allowable to use the `fmpz_mat` constructor directly instead of going through `MatrixSpace(ZZ, ...)`?

**Comment by thofma** [comment]
Yes, you can just do `matrix(ZZ, sizeAm..., Am)`. It also supports `matrix(ZZ, m)`, where `m` is a 2-dimensional array.

**Comment by thofma** [comment]
Sorry, I mean no, don't use the `fmpz_mat` constructors directly. Instead use `matrix(...)`.

**Comment by thchr** [comment]
I see, OK. If this is expected, feel free to close straight away.

**Comment by thofma** [comment]
Yeah, this function is not discoverable enough (see https://github.com/Nemocas/Nemo.jl/issues/614). On the other `fmpz_mat` is also not a very obious name.

**Comment by thchr** [comment]
It might be nice if this constructor was mentioned somewhere in this section http://nemocas.github.io/Nemo.jl/latest/matrix.html.

**Comment by thofma** [comment]
Thanks for the hint. I will hijack your issue for this cause.
