### ISSUE TITLE
Confusion on real balls arithmetics

### ISSUE THREAD

**Issue by zhaoli-IHEP** [Nemocas/Nemo.jl#798]
We were curious about how the real balls is calculated since we found some strange behavior
```julia
using Nemo
RR = RealField(512)

x1 = RR("-0.0009022835966031153974841313418366039773090841472924254342139874926539351960934304906411273180250141 +/- 3.01e-101")
y1 = RR(" 0.001022588076150197450482015520748151174283628700264748825442519158341126555572554556059944293761683 +/- 9.73e-100")
println(x1+y1)
# gives [0.00012030447954708205299788417891154719697454455297232339122853166568719135947912406541881697573667 +/- 2.11e-99]


x2 = RR("-0.000902283596603115397484131341836603977309084147292425434213987492653935196093430490641127318025014 +/- 3.01e-101")
y2 = RR(" 0.001022588076150197450482015520748151174283628700264748825442519158341126555572554556059944293761683 +/- 9.73e-100")
println(x2+y2)
# gives [0.00012030447954708205299788417891154719697454455297232339122853166568719135947912406541881697573667 +/- 2.01e-99]

x3 = RR("-0.00090228359660311539748413134183660397730908414729242543421398749265393519609343049064112731802501 +/- 3.01e-101")
y3 = RR(" 0.00102258807615019745048201552074815117428362870026474882544251915834112655557255455605994429376168 +/- 9.73e-100")
println(x3+y3)
# gives [0.00012030447954708205299788417891154719697454455297232339122853166568719135947912406541881697573667 +/- 1.01e-99]
```
The tiny change on the midpoint leads to big difference in the error of the summation result. And it is pretty bigger than we expected. So we were wondering how the arithmetics for the error there.

**Comment by thofma** [comment]
There so many similar looking numbers. Could you elaborate what you mean by "big difference"? I see a factor of two for the error but is there something else?

**Comment by zhaoli-IHEP** [comment]
> There are so many similar looking numbers. Could you elaborate what you mean by "big difference"? I see a factor of two for the error but is there something else?

Yes, the difference between x1, x2 and x3 is only the last digit. Same case for y1, y2 and y3. But the error changed by factor two. This does not seem reasonable. Or how should we understand this?

**Comment by thofma** [comment]
Not sure, maybe @fredrik-johansson can help.

**Comment by albinahlback** [comment]
In the example given, we can see that
```
julia> radius(x1 + y1)
[1.00310...e-99 +/- 2.10e-254]
```
which is the same radius as printed for `x3 + y3`. It looks like it prints a truncated midpoint (matching the radius) and prints (non-displayed midpoint + radius), in order to not print (in my opinion) too much. If we look at
```
julia> a = RR("0.1011 +/- 0.0010")
[0.10 +/- 2.11e-3]
```
I personally think this printing looks better than printing `[0.1011 +/- 1.01e-3]`, since you are not certain about the last digits. But that's just my opinion.

**Comment by albinahlback** [comment]
This issue could be closed, right? @thofma
