### ISSUE TITLE
Possible bug in pseudo_inv?

### ISSUE THREAD

**Issue by zhaoli-IHEP** [Nemocas/Nemo.jl#804]
Hi, we were using pseudo_inv function to play around the inverse of matrix, but as the code shown in the following, the pseudo_inv generates a very large number in one of the element. And the zz/dd is finally not the inverse of  matrix mm by checking their multiplication.
```julia
using Nemo

const prec = 64::Int64
RR = RealField(prec)
CC = ComplexField(prec)

const ep_len = 5::Int64
LSF, ep = LaurentSeriesField(CC, ep_len, "ep")
const lsfe = Generic.LaurentSeriesFieldElem{acb}
const ms = Generic.MatSpace{lsfe}

mm = zero( ms( LSF, 3, 3 ) )
mm[1,1] = LSF( CC( 0, 28697814 ) )
mm[2,2] = LSF( CC( 0, 28697814 ) )
mm[3,3] = LSF( CC( 0, 14348907 ) )*(1+ep)

println("mm = ", mm)
println()

zz, dd = pseudo_inv( mm )

println("zz = ", zz )
println()

println("dd = ", dd )
println()

the_inv = zz*inv(dd)
println("zz*inv(dd) = ", the_inv )
println()

println( "zz*inv(dd)*mm = ", the_inv*mm )
println()

println( "mm*zz*inv(dd) = ", mm*the_inv )
println()
```
Could it be some bug or something?

**Comment by wbhart** [comment]
I wouldn't expect it to work too well over CC.

**Comment by zhaoli-IHEP** [comment]
> I wouldn't expect it to work too well over CC.

It has same problem for RR
```julia
using Nemo

const prec = 64::Int64
RR = RealField(prec)

const ep_len = 5::Int64
LSF, ep = LaurentSeriesField(RR, ep_len, "ep")
const lsfe = Generic.LaurentSeriesFieldElem{arb}
const ms = Generic.MatSpace{lsfe}

mm = zero( ms( LSF, 3, 3 ) )
mm[1,1] = LSF( RR( 28697814 ) )
mm[2,2] = LSF( RR( 28697814 ) )
mm[3,3] = LSF( RR( 14348907 ) )*(1+ep)

println("mm = ", mm)
println()

zz, dd = pseudo_inv( mm )

println("zz = ", zz )
println()

println("dd = ", dd )
println()

the_inv = zz*inv(dd)
println("zz*inv(dd) = ", the_inv )
println()

println( "zz*inv(dd)*mm = ", the_inv*mm )
println()

println( "mm*zz*inv(dd) = ", mm*the_inv )
println()
```

**Comment by wbhart** [comment]
Sure. Basically I wouldn't expect too much over any inexact ring. We don't have any kind of deliberate numerical stability in the algorithms we are using.

If you demonstrated a problem over an exact ring, we would be much more concerned about a bug.

**Comment by wbhart** [comment]
Anyhow, I think pseudo_inv is for integral domains that are not fields isn't it?

**Comment by zhaoli-IHEP** [comment]
> Sure. Basically I wouldn't expect too much over any inexact ring. We don't have any kind of deliberate numerical stability in the algorithms we are using.
> 
> If you demonstrated a problem over an exact ring, we would be much more concerned about a bug.

Thank you for the information.
But how about the direct inverse function inv()?

**Comment by zhaoli-IHEP** [comment]
> Anyhow, I think pseudo_inv is for integral domains that are not fields isn't it?

Thank you for the information. I did not know the algorithm used in pseudo_inv().
Then how about the direct inverse function inv()? Can we assume that inv() should work for generic cases?
BTW, we were wondering if there is some function can calculation adjoint matrix?

**Comment by wbhart** [comment]
No, I don't think we have anything special for matrices of Laurent series over an inexact field. Generally if you want to use numerics you need special algorithms.

Perhaps @fredrik-johansson  has a suggestion of which algorithm might be useful here.

**Comment by wbhart** [comment]
Regarding adjoint, I don't think we have that implemented specially.

**Comment by zhaoli-IHEP** [comment]
> No, I don't think we have anything special for matrices of Laurent series over an inexact field. Generally if you want to use numerics you need special algorithms.
> 
> Perhaps @fredrik-johansson has a suggestion of which algorithm might be useful here.

So do you mean that even inv() may have used LU decomposition, so it may lead problem for float numbers?

**Comment by wbhart** [comment]
Sure. That's very likely.

**Comment by thofma** [comment]
The `pseudo_inv` seems to do the correct thing. `zz * mm` looks very much like `dd * LSF[1 0 0; 0 1 0; 0 0 1]`. Can you confirm?

Also `inv(dd) * d` looks like `1`.

But for some reason the entry at position `(2, 2)` of the product `inv(dd) * zz * mm` looks odd.

**Comment by zhaoli-IHEP** [comment]
> The `pseudo_inv` seems to do the correct thing. `zz * mm` looks very much like `dd * LSF[1 0 0; 0 1 0; 0 0 1]`. Can you confirm?
> 
> Also `inv(dd) * dd` looks like `1`.
> 
> But for some reason the entry at position `(2, 2)` of the product `inv(dd) * zz * mm` looks odd.

No the 3x3 or bigger matrix will also lead to incorrect results. You can check on the code I have pasted.

**Comment by thofma** [comment]
Ah, I see it now. Thanks.

As @wbhart said, all the generic algorithms were not designed to take inexact rings into account. There are plenty of `iszero` calls, which will make everything fall apart :(

**Comment by wbhart** [comment]
I'm closing this issue as it is not something we can fix directly. We first need to find a way to handle inexact entries in matrices. There is a separate ticket for that.
