### ISSUE TITLE
Constructing gfp_mats with "negative" entries gives random results

### ISSUE THREAD

**Issue by joschmitt** [Nemocas/Nemo.jl#813]
Constructing matrices over finite fields from an fmpz array with negative entries gives random results. For example:
```
julia> using Nemo
Welcome to Nemo version 0.17.0
Nemo comes with absolutely no warranty whatsoever
julia> F = GF(5)
Galois field with characteristic 5
julia> for i = 1:10
           @show matrix(F, 1, 1, [ fmpz(-1) ])
       end
matrix(F, 1, 1, [fmpz(-1)]) = [1]
matrix(F, 1, 1, [fmpz(-1)]) = [1]
matrix(F, 1, 1, [fmpz(-1)]) = [0]
matrix(F, 1, 1, [fmpz(-1)]) = [4]
matrix(F, 1, 1, [fmpz(-1)]) = [3]
matrix(F, 1, 1, [fmpz(-1)]) = [2]
matrix(F, 1, 1, [fmpz(-1)]) = [1]
matrix(F, 1, 1, [fmpz(-1)]) = [0]
matrix(F, 1, 1, [fmpz(-1)]) = [4]
matrix(F, 1, 1, [fmpz(-1)]) = [1]
```
This only happens for `GaloisFields` and not `GaloisFmpzFields`, as far as I can see, and `F(-1)` seems to be fine too.

**Comment by wbhart** [comment]
I confirm the bug, but I cannot figure out what is causing it.

The call to fmpz_mod_ui results in the wrong value. But I checked the code for fmpz_mod_ui and it just calls fmpz_fdiv_ui and fmpz_set, and neither of these is doing anything unusual.

This is a pretty weird bug. But it occurs for me with Julia-1.0.4.

**Comment by wbhart** [comment]
Got it. Patch incoming.
