### ISSUE TITLE
sqrtrem not defined?  

### ISSUE THREAD

**Issue by OpenLibMathSeq** [Nemocas/Nemo.jl#816]
Executing the examples in  
http://nemocas.github.io/Nemo.jl/release-0.17/integer.html#Base.isqrt-Tuple{fmpz}
Welcome to Nemo version 0.16.3
ERROR: LoadError: UndefVarError: sqrtrem not defined

**Comment by thofma** [comment]
Thanks for catching this. It must be `isqrtrem` in the example. We will fix this.
