### ISSUE TITLE
mul! is not doing what we claim it does for some flint matrices

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#829]
We are happily turning `mul!(x::nmod_mat, y::nmod_mat, z::nmod_mat)` into a call `ccall((:nmod_mat_mul, [...]), (x, y, z,...))`, but `nmod_mat_mul` does not allow arbitrary aliasing. I just realized this after:
```julia
julia> R = ResidueRing(FlintZZ, 5)
Integers modulo 5

julia> Gi = matrix(R, 6, 6, [4, 4, 0, 3, 2, 2, 3, 0, 0, 1, 3, 1, 3, 4, 1, 3, 2, 2, 3, 0, 0, 3, 3, 3, 4, 0, 0, 2, 4, 4, 2, 4, 0, 4, 2, 3])
[4  4  0  3  2  2]
[3  0  0  1  3  1]
[3  4  1  3  2  2]
[3  0  0  3  3  3]
[4  0  0  2  4  4]
[2  4  0  4  2  3]

julia> ne = matrix(R, 1, 6, [1, 2, 0, 0, 0, 0])
[1  2  0  0  0  0]

julia> ne * Gi
[0  4  0  0  3  4]

julia> mul!(ne, ne, Gi)
[0  0  0  0  0  0]
```
As far as I understand for `mul!(x, y, z)` the rules are

| type | aliasing |
--------|------------|
| nmod_mat | no aliasing between x and y or z allowed |
| fmpz_mat | aliasing allowed |
| fq_mat/fq_nmod_mat | no aliasing between x and y or z allowed |
| fmpq_mat | ?? |
| arb_mat | ?? | 
| acb_mat | ?? |

Is this something we should fix on the flint side @wbhart? I will prepare I PR to Nemo to fix the wrong result by sprinkling deepcopy's around, but this will make everything considerably slower.

**Comment by wbhart** [comment]
For matrices, Flint should always assume you are writing into a new matrix, I think. This is why we don't allow resizing on the fly. It makes sense too: for an mxn by nxk matrix, the result is mxk, which doesn't match the input matrices at all.

So I'd say mul! has to do the same as mul, i.e. create a new object.

As to whether we could allow aliasing for nxn matrices in Flint, we'll certainly have to think about that. But this will only work for matrix algebras, which possibly aren't so important.

**Comment by thofma** [comment]
It is not only for square matrics, but also for the frequent vector * square matrix operation, where one has `mul!(x, x, y)`.

It is much more memory friendly (faster) to do the temporary allocation on the flint side, as it is done already for `fmpz_mat` and `fmpq_mat` to allow arbitrary aliasing. Can't we just add the same for other types too? I am working on a patch for it right now.

**Comment by fredrik-johansson** [comment]
Yes, we should fix flint to allow aliasing here.

**Comment by thofma** [comment]
OK, I will prepare a PR.

**Comment by wbhart** [comment]
No objections from me.
