### ISSUE TITLE
Wrong error bounds on complex ball arithmetic

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#850]
I came over an answer I did not expect:

``CC = ComplexField(64)``
``a = CC(1, 2) + CC("+/- .5", "+/- 1.5")``
``b = CC(1, 2) + CC("+/- .5", "+/- 0.5")``

which yields:
``[1e+0 +/- 0.501] + i*[+/- 3.51]``
``[1e+0 +/- 0.501] + i*[2e+0 +/- 0.501]``

Is `a`'s imaginary part supposed to be displayed/calculated that way?

**Comment by wbhart** [comment]
That actually does seem strange, as 0.5 is an exact value in binary.

Perhaps @fredrik-johansson can comment on this (sorry, I know this has come up before, but I forgot the answer).

**Comment by thofma** [comment]
It is just the printing:
```
julia> imag(a)
[+/- 3.51]

julia> midpoint(imag(a))
2.0000000000000000000

julia> radius(imag(a))
[1.5000000018626451492 +/- 3.10e-20]
```
