### ISSUE TITLE
`show` method for `nf_elem`

### ISSUE THREAD

**Issue by ThomasBreuer** [Nemocas/Nemo.jl#872]
Is the following output intended?
```
julia> F, z = CyclotomicField(5);  z^3 + z^2 + z + 1
z_5^3 + 1*z_5^2 + 1*z_5 + 1
```
(Note the unnecessary coefficients `1` for `z_5^2` and `z_5`.)

**Comment by thofma** [comment]
Ah, forgot about that. Thanks for the reminder :)

Now that https://github.com/Nemocas/Nemo.jl/issues/859 is fixed we can do this properly.

**Comment by wbhart** [comment]
I notice we get similar 1's printed for other rings as well after the switch to the new printer. Unfortunately I forgot which ring I saw this in last.
