### ISSUE TITLE
Random sampler missing for matrices over GF(p)

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#892]
The following code does not work in Nemo (I have pulled the latest master):

```
using Nemo
R = GF(7)
S = MatrixSpace(R, 30, 30)
M = rand(S)
```

The same code does work in AbstractAlgebra.

**Comment by rfourquet** [comment]
> (I have pulled the latest master)

:D

I will look into this now.

**Comment by rfourquet** [comment]
@wbhart @thofma : I would like to write tests for this, and similarly in Singular.jl, but this depends on AbstractAlgebra master: would you be fine that I realease AbstractAlgebra v0.11.1, and that I make Nemo and Singular.jl depend on it? Or is it too premature?

**Comment by thofma** [comment]
Fine with me :)

**Comment by wbhart** [comment]
No objections.
