### ISSUE TITLE
A surprising warning

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#893]
┌ Warning: Integration did converge
    └ @ Nemo C:\Users\User\.julia\packages\Nemo\NVxdo\src\arb\acb_calc.jl:74
    [0.200000000000000000000000 +/- 3.73e-25]   ==>   nan

**Comment by thofma** [comment]
Do you prefer an error?

**Comment by wbhart** [comment]
Is the error correct? Is it a problem if the integration DOES converge?

**Comment by PeterLuschny** [comment]
> Do you prefer an error?

Well, the confusion was easy to solve. I looked up the indicated line

    .julia\packages\Nemo\NVxdo\src\arb\acb_calc.jl:74

and saw

    if status == ARB_CALC_SUCCESS
          nothing
    elseif status == ARB_CALC_NO_CONVERGENCE
          @warn("Integration did converge")
    end

So I am still not happy about my result, but I am no longer surprised.

**Comment by thofma** [comment]
I think there is not much we can do about it. I can imagine that Fredrik might be interested in the example.

**Comment by PeterLuschny** [comment]
> Is the error correct? Is it a problem if the integration DOES converge?

Yes, it is. But is it not unusual to warn about it with the shout out

    @warn("Integration did converge")  ??

**Comment by thofma** [comment]
I am not integrating much myself, so any hint on how to improve this is appreciated.

**Comment by PeterLuschny** [comment]
> I am not integrating much myself, so any hint on how to improve this is appreciated.

In my understanding the word 'not' is missing here.
Please look again at the source code quoted above.

**Comment by thofma** [comment]
Sorry! Will be fixed by https://github.com/Nemocas/Nemo.jl/pull/897.

**Comment by PeterLuschny** [comment]
_Obviously, It’s Not Obvious._
It was my mistake to assume this.
Sorry!

**Comment by thofma** [comment]
Fixed by #897.
