### ISSUE TITLE
Tag 0.5.1

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#91]
@wbhart @fieker 

I would like to tag 0.5.1. Working around the deepcopy bug in Hecke is kind of annoying.

Any objections? If not, then once #90 is merged and travis is running I will do the tagging and the METADATA stuff.

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your patch. The merge button does nothing. This has happened once before. It eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia 0.5?

**Comment by wbhart** [comment]
Ok with me. Note GitHub seems to be broken for me. I can't merge your
patch. The merge button does nothing. This has happened once before. It
eventually came good.

Do you think now is a good time to get rid of all the warnings with Julia
0.5?

**Comment by thofma** [comment]
Yeah, looks like you are having some problems. You just posted ~30 times the same comment. I deleted the copies.

Fixing the warnings for 0.5 would mean dropping support for 0.4. While I think this is a good idea, I am not sure if we want to do this in a point release.

Your are probably quite busy at the moment, but do you know when http://nemocas.org/binaries/ will populated again? Installing Nemo is at the moment painful on Linux and impossible on Windows.

**Comment by wbhart** [comment]
I'll put it across shortly. I just forgot about it. They won't be new ones
though.

Bill.

**Comment by wbhart** [comment]
Done, I think.

**Comment by thofma** [comment]
Thanks.
