### ISSUE TITLE
Library libflint not found 

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#913]
Any advice on this issue?
Thanks!

 Julia 1.5.3 on Windows

Status `C:\Users\User\CodeRepository\Int.jl\Project.toml`
  [c3fe647b] AbstractAlgebra v0.8.1
  [6e4b80f9] BenchmarkTools v0.4.3
  [b99e7846] BinaryProvider v0.5.91
  [ffbed154] DocStringExtensions v0.8.3
  [cd3eb016] HTTP v0.8.19
  [2edaba10] Nemo v0.16.4
  [8dfed614] Test
  
ERROR: LoadError: InitError: could not load library 
"C:\Users\User\.julia\packages\Nemo\xJHVO\deps\usr\bin\libflint"     
The specified module could not be found.
Stacktrace:
 [1] __init__() at C:\Users\User\.julia\packages\Nemo\xJHVO\src\Nemo.jl:258
 [2] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:697
 [3] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:782
 [4] _require(::Base.PkgId) at .\loading.jl:1007
 [5] require(::Base.PkgId) at .\loading.jl:928
 [6] require(::Module, ::Symbol) at .\loading.jl:923
 [7] include(::Function, ::Module, ::String) at .\Base.jl:380
 [8] include(::Module, ::String) at .\Base.jl:368
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:331 [inlined]
 [11] eval(::Expr) at .\client.jl:467
 [12] top-level scope at .\none:3
during initialization of module Nemo

**Comment by thofma** [comment]
Can you try updating Nemo? The most recent version is 0.18 4.

**Comment by PeterLuschny** [comment]
>
> Can you try updating Nemo? The most recent version is 0.18 4.
>

There are two different things:

(1) It is a fresh clone of a project published and versioned
on GitHub. So I assumed it would (more, that it has to) run
unchanged. But it leads to the error described in the first
post. Why does it break?

(2) Following your suggestion I get:

(Int.jl) pkg> add Nemo
  Resolving package versions...
  Installed Antic_jll ─ v0.2.2+1
  Installed Arb_jll ─── v2.18.1+1
  Installed MPFR_jll ── v4.1.0+1
  Installed LoadFlint ─ v0.3.4
  Installed Nemo ────── v0.18.4
Updating `C:\Users\User\CodeRepository\Int.jl\Project.toml`
 Revise [2edaba10] .+ Nemo v0.18.4LogRecord
(UpdatingError, evaluation error starting at
C:\Users\User\.julia\packages\JLLWrappers\C3ISx\src\toplevel_generators.jl:79,
lowered, Revise_e943ed8b,
"C:\Users\User\.julia\packages\Revise\BqeJF\src\lowered.jl", 106, (
`C:\Users\User\CodeRepository\Int.jl\Manifest.toml`
  [e21ec000] mod+ Antic_jll v0.2.2+1=MPFR_jll ,  [d9960996] ex+ Arb_jll
v2.18.1+1=
begin
 [e134572f]     + FLINT_jll v2.6.3+1#=
C:\Users\User\.julia\packages\MPFR_jll\735jI\src\MPFR_jll.jl : [781609d7]
8+ GMP_jll v6.1.2+6 =#
      [472f376f] #= + LoadFlint
v0.3.4C:\Users\User\.julia\packages\MPFR_jll\735jI\src\MPFR_jll.jl
: 8 [3a97d323]  =#+ MPFR_jll v4.1.0+1
JLLWrappers . [2edaba10] @+ Nemo v0.18.4generate_main_file
    Building"MPFR" UUID("3a97d323-0669-5f0c-9066-3539efd106a3")
end) UndefVarError: Base_Docs_4352b6d8 not definedLoadFlint →
`C:\Users\User\.julia\packages\LoadFlint\o1S6V\deps\build.log`
Stacktrace:
 [1] collect_args(::JuliaInterpreter.Frame, ::Expr; isfc::Bool) at
C:\Users\User\.julia\packages\JuliaInterpreter\RmxVj\src\interpret.jl:60)
 Building Nemo ─────→
`C:\Users\User\.julia\packages\Nemo\QMPxi\deps\build.log`

**Comment by thofma** [comment]
1) Can you try a `]build Nemo`? I just triggered a new Windows test with julia 1.5.3 and Nemo 0.16.4 [here](https://ci.appveyor.com/project/thofma/nemo-jl-n5gdb/builds/36337454/job/o4433o19wnf80k0e) and it seems to work fine.

(There is actually an error, but it is different from yours. Packages are not necessarily compatible with new julia 1.* versions, because they can start exporting new methods which will break your package if you already exported that name. In our case, julia started exporting `contains` a few months ago, be we were using this since a few years. But this is a problem with the julia developers interpretation of "backwards compatibility".)

2) This looks like a Revise error. I don't think Revise works properly if one updates a package in a session.

**Comment by PeterLuschny** [comment]
> Can you try a ]build Nemo? I just triggered a new Windows 
test with julia 1.5.3 and Nemo 0.16.4 here and it seems to work fine.

I can confirm that.

Moreover, I went through the cloning process a second time, 
this time with a fresh install of JuliaPro_v1.5.2-1, and this 
time it went as expected.

> This looks like a Revise error. I don't think Revise works 
properly if one updates a package in a session.

Yes, I see that too. Revise doesn't always work as I would 
expect.

I therefore propose to let this matter rest.

Thanks!

**Comment by thofma** [comment]
Glad that it worked.
