### ISSUE TITLE
Provide a "native" version of gcdx

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/Nemo.jl#921]
Currently it converts to BigInt then computes then computes back:
```julia
function gcdx(a::fmpz, b::fmpz)
   g, s, t = gcdx(BigInt(a), BigInt(b))
   return fmpz(g), fmpz(s), fmpz(t)
end
```

**Comment by thofma** [comment]
This is on purpose: https://github.com/Nemocas/Nemo.jl/pull/730

**Comment by fingolfin** [comment]
Then I suggest a code comment should explain that.

**Comment by fingolfin** [comment]
I also note that PR #730 does not actually explain *why* this is needed, nor what the difference really is/was and why it matters?

**Comment by thofma** [comment]
@wbhart Do you remember the rational for having gcdx consistent with julia?

**Comment by wbhart** [comment]
Sure. We want the same answers at the console from Julia (and therefore AbstractAlgebra) as from Nemo.

What Oscar does I don't care. But this is clearly how Nemo should behave.

**Comment by tthsqe12** [comment]
@albinahlback does your new xgcd fit the bill here?

**Comment by albinahlback** [comment]
Yes indeed!
