### ISSUE TITLE
possible bug in power series exponential

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/Nemo.jl#927]
x^5+O(x^5) looks like a wrong answer to me.
```
julia> using Nemo

julia> R = ResidueRing(ZZ, 101)
Integers modulo 101

julia> S, x = PowerSeriesRing(R, 30, "x")
(Univariate power series ring in x over Integers modulo 101, x + O(x^31))

julia> exp(O(x^5))
x^5 + O(x^5)

```

**Comment by wbhart** [comment]
Yes, that's clearly a bug. I wonder how that happened.

**Comment by albinahlback** [comment]
I think the problem is that `Nemo` does not define `exp` for `fmpz_mod_abs_series` -- compare the files `flint/fmpz_mod_abs_series.jl` and `flint/fmpz_mod_rel_series.jl`, for which the latter actually defines `exp`.
