### ISSUE TITLE
Not possible to call acb(x, y) where x and y are not the same type

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#933]
Let `CC = ComplexField(100)`. Then we can call `CC(1.0, 1.0)` and `CC(1, 1)`, but not `CC(1.0, 1)` since `1.0` is a float and `1` an integer.

This is not possible since both arguments must be of the same type, but is there a reason for this?

**Comment by thofma** [comment]
No specific reason, just an oversight.
