### ISSUE TITLE
Nemo not working on 0.4

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#95]
Since https://github.com/Nemocas/Nemo.jl/commit/b9ab1abc39ff4f406e052fff84a4662cfac6d398 Nemo is not working on 0.4 properly. Tests did not catch this regression, since we do not test print functions (we should change this).

Do we want to drop 0.4 support? @wbhart @fieker

**Comment by wbhart** [comment]
The performance of the multivariate poly stuff I did depends critically on
Julia-0.5. It's as slow as a wet week under 0.4. That's one argument for
dropping 0.4. On the other hand supporting it with Compat.jl doesn't seem
too much trouble. But we may as well stop recommending it.

Fairly soon I'll actually need 0.5 (for Singular), so it's going to be a
very short-lived support if we do continue to support 0.4.

Bill.

**Comment by thofma** [comment]
I am in favor of dropping support for 0.4 and just switching to 0.5. Then we could also get rid of all the deprecation warnings. Do we switch now or do we wait for some other changes?

**Comment by wbhart** [comment]
I'm ok with a switch now. I'm using 0.5 exclusively anyway I think.

Bill.

**Comment by thofma** [comment]
OK. I will prepare a PR.
