### ISSUE TITLE
padic log

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#950]
@fieker once reported:

julia> log(coeff(c[1].data, 0))
ERROR: Unable to compute logarithm

the doc or the implementation is faulty.
t seems to work only if input x satisties
  val(x) = 0
AND
  val(1-x) > 0

The corresponding Flint-Doc seems to be wrong as well...

-----

I am moving the report here from my email so it gets dealt with.

**Comment by wbhart** [comment]
@fieker Can you give an example of a case you were expecting to work which didn't work?

**Comment by fieker** [comment]
its still possibly "broken" in flint, but we worked around this and fixed it in the interface. So for Nemo: closed, for flint: don't know
