### ISSUE TITLE
fmpz_poly_factor

### ISSUE THREAD

**Issue by fieker** [Nemocas/Nemo.jl#952]
Trying
julia> h = swinnerton_dyer(7, x)*swinnerton_dyer(8, x);
julia> @time factor(h);
265.500565 seconds (34.70 M allocations: 6.088 GiB, 0.01% gc time)

while, in pari:
? factor(f);
time = 4,190 ms.

Do not know if this reflects strategy or lll....

**Comment by fieker** [comment]
Trying 
julia> h = swinnerton_dyer(7, x)*swinnerton_dyer(8, x);
julia> @time factor(h);
265.500565 seconds (34.70 M allocations: 6.088 GiB, 0.01% gc time)

while, in pari:
? factor(f);
time = 4,190 ms.

Do not know if this reflects strategy or lll....

**Comment by wbhart** [comment]
I don't know. S-D polys are the ones with lots of local factors, right? So it's using LLL.

But this polynomial is huge. How does Pari/GP factor it in 4s?

The use a Hensel lifting bound of 47^184. After Zassenhaus it says there is one factor left with 96 potential factors.

Then it uses L^2, using blocks of traces. That fails, so it tries a different prime and retries, many times.

But all that happens in 4s. Very cool. No idea why Flint is taking so long, but I recall these are hard to prove irreducible because there's not much you can do but lift to the bound. Maybe their bound is much better. It seems they have four different bounds they use, all of which are wildly different in this case.

**Comment by fieker** [comment]
On Wed, Jan 13, 2021 at 01:01:41AM -0800, wbhart wrote:
> I don't know. S-D polys are the ones with lots of local factors, right? So it's using LLL.
> 
> But this polynomial is huge. How does Pari/GP factor it in 4s?
> 
> The use a Hensel lifting bound of 47^184. After Zassenhaus it says there is one factor left with 96 potential factors.
> 
> Then it uses L^2, using blocks of traces. That fails, so it tries a different prime and retries, many times.
> 
> But all that happens in 4s. Very cool. No idea why Flint is taking so long, but I recall these are hard to prove irreducible because there's not much you can do but lift to the bound. Maybe their bound is much better. It seems they have four different bounds they use, all of which are wildly different in this case.
> 
I have no idea as well, but I thought to record this ....
We're definitely using LLL here.

As a side, I can factor this in < 30sec over a number field of degree 5,
the structure of the LLL matrix is different then.

**Comment by wbhart** [comment]
For reference, our original van Hoeij-Novocin implementation in Flint 1 took 64s to prove S7 irreducible and 128s to prove S8 irreducible, and I recall Andy working really exceptionally hard on this, so I wouldn't rule out an issue in the other implementation here, or a completely new idea not known to me, Mark or Andy in 2011.

**Comment by wbhart** [comment]
They do use LLL-parameters (0.750,0.510) then switch to (0.999,0.510) for each L^2 run. They do seem to cut down the number of potential factors with each run of L^2. But perhaps it also helps them that they pass some info from Zassenhaus into L^2 at the beginning of each run.

I'm sure Bill Allombert or Karim Belabas would explain what they've done if we asked them.

**Comment by wbhart** [comment]
No, wait, I misread the table. It's 0.5s and 6s respectively.

So yeah, it looks like the strategy on our side could be improved a lot!

**Comment by wbhart** [comment]
Yeah, we can still factor S7 and S8 in those times (well within, actually), so it's the product where Pari has the edge. I suspect they are just keeping track of possible factorisations much more carefully.

**Comment by wbhart** [comment]
Yeah, Pari/GP takes exactly the same amount of time to factor S7 and S8 individually as Flint does. So it's definitely strategy. I wonder if they actually have the factors before they even run LLL.

**Comment by wbhart** [comment]
Yes, they find the two factors very quickly, which is what we are not doing. Once they have the two factors, they factor them each individually.

But they are using L^2 to find the two factors, not Zassenhaus. They only use that to check for combinations of 1, 2 and 3 local factors which are true factors, of which there are none

**Comment by wbhart** [comment]
I could be wrong, but it looks to me like they check if the number of potential factors did not go down after each L^2 run. If it did not go down, they try the factors out to see if any of them are true factors. If it did go down, it looks like they do another L^2 run. 

When they reach 2 factors they find they have two true factors, so all that remains is to prove them irreducible in this case.

**Comment by wbhart** [comment]
It looks like the factorisation of the individual factors is completely restarted, even down to picking the best prime to use.

**Comment by fieker** [comment]
Its not the pari lll, calling pari on the same matrices as we do (well, the amtrices I create in julia for factoring), is frequently slower than the entire factorisation in pari, so its related to using more lll friendly lattices.
The work in pari is done using fplll (versio 1.3 Stehle)

**Comment by wbhart** [comment]
Yes, it's not the LLL. As I said, it is in tracking which factors travel together and using this information to split the factorisation into smaller factorisations and restarting. I don't think we are doing that.

**Comment by fieker** [comment]
pari uses LLL on matrices having < 50bit entries as far as I can see. We use > 200 bit entries...

**Comment by tthsqe12** [comment]
@wbhart have you considered deflation? the input and both factors have all even exponents

**Comment by wbhart** [comment]
I don't think that's what's going on here. But I also thought I was doing that.

**Comment by tthsqe12** [comment]
deflation is a dirty trick - which is currently not being used - and you should make the code as best as possible without using it. My decomposition pr is for this. I will work it into the factor code _after_ you revise the current strategy.

**Comment by wbhart** [comment]
Deflation actually slows some factorisations down. I can check the paper to see if this is such a case.

**Comment by tthsqe12** [comment]
Isn't this what nemo is for?
```
julia> R,x=PolynomialRing(ZZ,"x");
julia> S,y=PolynomialRing(R,"y");
julia> h = swinnerton_dyer(7, x)*swinnerton_dyer(8, x);
julia> h2 = sqrt(resultant(h(y), y^2-x));
julia> @time factor(h2);
  1.475211 seconds (972.12 k allocations: 116.861 MiB, 3.85% gc time)
```

**Comment by tthsqe12** [comment]
btw, do know to what extent the implemented precision strategy for Z[x] resembles that of Fp[y][x]?
https://github.com/wbhart/flint2/blob/trunk/nmod_mpoly_factor/n_bpoly_mod_factor_smprime.c#L1334

**Comment by wbhart** [comment]
Oh yeah, that's embarrassing. Well there's your answer @fieker . It was just the "power hack" all along.

As for fp[y][x], didn't you implement that? I'm not sure I can shed much light on it.

**Comment by fieker** [comment]
On Thu, Jan 14, 2021 at 10:50:14AM -0800, wbhart wrote:
> Oh yeah, that's embarrassing. Well there's your answer @fieker . It was just the "power hack" all along.
What is the "power hack"?
Will this be
 - implemented
 - universally useful
 - dangerous and bad
 - difficult
 - easy
> 
> As for fp[y][x], didn't you implement that? I'm not sure I can shed much light on it.
I did s.th. on the bivariate - but so far, did not finish

**Comment by wbhart** [comment]
Power hack is what we call deflation/inflation. It's already implemented, it's just not being used because it only sometimes speeds up the factorisation.

**Comment by tthsqe12** [comment]
The power hack is writing the input as f(g(x)), factoring f, then composing the factors with g, then factoring again, and is not even implemented. I stayed away from it because of the "factoring again" step: we need a version of Andy's code that is able to make use of the known possible degrees of factors for this "factoring again" step (The zassenhaus factorer can do this, but the lll factorer cannot). Unfortunately, he has not responded to my latest email.

**Comment by wbhart** [comment]
I was referring to what Victor Shoup calls the "power hack":

https://libntl.org/doc/ZZXFactoring.txt

It's a version of inflation/deflation.

**Comment by wbhart** [comment]
It's kinda given away in the name that it is to do with powers, not general composition.
