### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by switzel** [Nemocas/Nemo.jl#955]
A while ago, I wrote some acbs into a jld archive (using JLD 0.10.0 and Julia 1.5.1). When I try to reload them now I get a segmentation fault produced by GMP:

signal (11): Segmentation fault
in expression starting at REPL[4]:0
__gmpn_mul_basecase at /usr/bin/../lib/x86_64-linux-gnu/julia/libgmp.so (unknown line)
arf_mul_rnd_down at /workspace/srcdir/arb-2.18.1/arf/mul_rnd_down.c:210
unknown function (ip: (nil))
Allocations: 25099792 (Pool: 25094429; Big: 5363); GC: 26
Segmentation fault (core dumped)

At first I thought this might be because I had used a different version of Nemo at the time and the internal representation had changed. But I tried the same version I had used (0.18.1) and the outcome is the same.

Has anyone experienced a similar problem? Does anyone have a suggestion? (I am using Ubuntu's GMP version 2:6.2.0+dfsg-4).

**Comment by thofma** [comment]
I don't think `acb` are archivable per default with JLD. Did you write your own function for serialization?

**Comment by switzel** [comment]
No, I just tried to save and it did something without complaining. When I load without "using Nemo" what I get looks like these:

    JLD.var"##Nemo.arb#253"(2, 0x0000000000000004, 0x09a8ab811a0f57f0, 0xcaa5907b77349589, -96, 0x000000003491d65a, JLD.var"##Nemo.ArbField#261"(2048))
    JLD.var"##Nemo.arb#253"(2, 0x0000000000000080, 0x0000000000000040, 0x000000000181e310, -4016, 0x0000000029179992, JLD.var"##Nemo.ArbField#261"(2048))

(You notice that it's `arb`s rather than `acb`s, sorry.) The first one is "complicated" enough to plausibly contain the necessary data, the second one is rather not.

But when I tried (or try) it seems to work:

    julia> using Nemo
    julia> using JLD
    julia> RR = ArbField(64)
    Real Field with 64 bits of precision and error bounds
    julia> r = RR(1/3)
    [0.33333333333333331483 +/- 3.84e-22]
    julia> save("test.jld","r",r)
    julia> r = load("test.jld","r")
    [0.33333333333333331483 +/- 3.84e-22]

**Comment by wbhart** [comment]
The problem is when you do it in a single session, those pointers are still valid. Once you restart your session, the pointers are no longer valid and it segfaults. As far as I know, there is no serialisation of C objects in Nemo at the moment. It can be added, it just isn't there yet, so far as I know.

**Comment by switzel** [comment]
Ok, but the example above works even if starting a new session for loading. It does *not* work with 2048 bits of precision, however. So my impression is that there is some (possibly implicit) serialization related to machine precision (it's not quite machine precision, though, because 65 bits work as well).

In any case it would be nice if it said that it won't work when trying to save, not when trying to load (so all data is gone).

**Comment by fingolfin** [comment]
That's a problem with JLD, though, isn't it? The only way we I can think of we could get it to warn would be to depend on JLD, just to add methods for it that print an error... Now all our users need to install JLD, just so that we can tell them that they can't use it? And there are other serialization libraries, which may require the same, should we depend on them all?

**Comment by wbhart** [comment]
I can't really explain 65 bits. I could explain 64 bits (62 bits stored in the mangled pointer + sign + implicit leading bit).

**Comment by switzel** [comment]
@fingolfin: You are right, I suppose, but neither of this was clear a priori: with serialization working up to 1024 bits (i.e. all the time during testing) it was reasonable to assume that Nemo *did* attempt to be serializable. Also for me as a newcomer to Julia it is entirely plausible, that a class would provide a generic serialization method (returning some binary representation) that could be used as a fallback by all serialization libraries.
If you want something that's definitely in the realm of Nemo, it's in the subject of the issue: whatever JLD does or does not, there is a call to a Nemo function that produces a segmentation fault. So some assumption on data is violated. Possibly this is an assumption made on the data provided by the user to Nemo which one could find in the documentation (in which case everthing is "fine"). But possibly it is an assumption that Nemo should check before handing the data to the arb library, in which case there would be something to do.

@wbhart: Actually what needs explaining is 1024 bits (see the edit in my last post). It still puzzles me that it should accidentally work up to that size but no further. Although I admit that this is not clearly a Nemo problem, it seems the explanation for the 1024 bits should lie in Nemos internal representation (or arb lib's, or gmp's...).

**Comment by thofma** [comment]
I am sorry to hear that your data lost. Unfortunately there is not much we can do about it here. Nor can we prevent such things in the future. JLD is just one of many binary formats for 'persistent' storage with its own mechanism for serializing objects. They will all be broken by default for objects like `arb`, which are "coming from" some C library. Looking at the documentation of JLD, it is not clear to me what to implement to support serialization of `arb`. If they fully support all julia Base types, your best bet is to go via `BigFloat`, but I would test it first.

Edit: It is easy to produce segmentation faults with any type by not using the proper interface provided by the library. If `x` is an `arb`, JLD can and will happily modify internal fields like `x.mid_d1` or `x.mid_rad_exp`. Of course this produces inconsistent states leading to segmentation faults. Because it is not using the documented functions to manipulate objects of type `arb`. JLD should not try to write/save things which it has no clue about.

**Comment by fredrik-johansson** [comment]
Note that arb_dump_str and arb_load_str can be used for serialization. Can we wrap them in such a way that JLD will use them?

**Comment by fredrik-johansson** [comment]
I expect that the automatic serialization will work up to 128 bits since Arb stores data inline in the struct up to that point.

**Comment by fingolfin** [comment]
@switzel I understand that this wasn't clear to you apriori, and I am sorry for your data loss. I am also really surprised about the "1024 bit" boundary, that indeed should be investigated. Perhaps if you could provide a short code snippet that reproduces the issue (as we don't know JLD, reproducing this from scratch is non-trivial for us), then we can have a look.

But note that you can in fact even produce segfaults with builting Julia types, like e.g. BigInt, which is just a wrapper around a pointer to an `mpz_t` pointer; this pointer then is passed to fast C code (provided by GMP). If one pokes into the innards of such a `BigInt` (and that's really what JLD and other serializers are doing when they recreated such objects, then it is trivial to produce garbage data, which then will lead to a crash. There is no way to guard against this, as we'd need to be able to determine whether something is a valid pointer or not. And even if there was: that would introduce a major performance hit in every operation that is implemented via a `ccall`, negating much of the benefit we get from calling into optimized C code in the first place.

**Comment by fredrik-johansson** [comment]
By the way, if you do r = RR(1/3), the value will be assigned from a machine-precision float, so it will actually fit in 128 bits regardless of the precision of RR. This might be why you are seeing strange cutoffs in behavior.

**Comment by switzel** [comment]
@thofma: Sure, never mind the data. I'll let it run again once I know how to save the outcome. So this is a Julia design decision, I suppose: data is not protected in the interest of efficiency? You realize I have no profound understanding of Julia, I just used it because it allowed me to make the computation with the least code.

@fredrik-johannson: as a workaround one could use ``readas`` and ``writeas`` but it's not clear to me from the JLD doc how to implement proper serialization; and in the actual testing I used RR(1)/RR(3) so this is not the reason.

**Comment by fingolfin** [comment]
Data *is* protected. You could get the same kind of crash in Python: just take any python code wrapping a C library (of which there is a ton), then take one of the objects wrapping a C pointer, and poke garbage into it, then pass it to a function - poof. In fact that only way to protect against such things is to completely prevent arbitrary "poking", but then you have a substantially crippled language.

**Comment by switzel** [comment]
@fingolfin Here's the sinppet:

    using Nemo
    using JLD
    RR = ArbField(1025)
    r = RR(1)/RR(3)
    save("test.jld","r",r)

New session

    using Nemo
    using JLD
    r = load("test.jld","r")

**Comment by switzel** [comment]
@fingolfin: Ok, I get it. So what JLD serializes could be 128 bytes of stack plus a pointer to heap. And the pointer is not exactly useful any more after recovery.

**Comment by switzel** [comment]
In any case there seems to be no "issue" left, so I'll close it. Fingolfin suggested to move the discussion to slack.

**Comment by wbhart** [comment]
@switzel My apologies I did misunderstand that everything works up to 1024 bits. I see that @fingolfin has provided a more likely explanation.
