### ISSUE TITLE
Use Conda.jl ?

### ISSUE THREAD

**Issue by isuruf** [Nemocas/Nemo.jl#96]
You can use Conda.jl for installing binary dependencies. Released versions of GMP, MPFR, FLINT and ARB are already available as conda packages. This will help reduce the build time.

**Comment by wbhart** [comment]
Sounds great. Thanks for letting us know about this!

It's still our policy to provide source code with the build, but saving the
build time will be great. Of course we still need to provide the option to
build from source, as some people won't use binary blobs. But it doesn't
have to be the default.

Bill.
