### ISSUE TITLE
Suboptimal printing of matrices over 

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/Nemo.jl#976]
The new printing code (which is quite elegant of course) lead to a minor regression in the GAP.jl test suite (see https://github.com/oscar-system/GAP.jl/pull/594); we fixed that for now, but we also feel that the new printing is perhaps a bit confusing in parts. @ThomasBreuer condensed this down to a brief example, which I reproduce with a minor modification below:distinguish:
```julia
julia> using Nemo
[...]

julia> R, x = Nemo.PolynomialRing( Nemo.QQ, "x" );

julia> f = x^5-x-1;

julia> F, a = Nemo.NumberField( f, "a" );

julia> Nemo.matrix( F, 1, 2, [ a^3+2*a^2, -a-1 ] )
[a^3 + 2*a^2  -a - 1]

julia> Nemo.matrix( F, 1, 2, [ a^3+2*a^2-a, -1 ] )
[a^3 + 2*a^2 - a  -1]
```

Note how the two final commands print two different matrices which are however very difficult to distinguish visually. If one sees the printed output in isolation, it is also very easy to get confused about the two.

Note how for the multiplication, it is better, because there are no spaces around the `*`. So one way to deal with this would be to print the expressions in a more compact form. Of course it's up to debate whether that looks better or worse, but IMHO it *is* easier to distinguish the two matrices this way.
```
julia> Nemo.matrix( F, 1, 2, [ a^3+2*a^2, -a-1 ] )
[a^3+2*a^2 -a-1]

julia> Nemo.matrix( F, 1, 2, [ a^3+2*a^2-a, -1 ] )
[a^3+2*a^2-a  -1]
```

Perhaps there are better ideas to tackle this; or perhaps we just decide that we can't do (resp. don't want to do) anything about it; also fine by me, but I thought we should at least briefly consider it (or perhaps folks already did consider it (I'd not be surprised), then perhaps you can briefly recap / point me to the relevant issue, and we can close it later on).

**Comment by tthsqe12** [comment]
In general I cannot read sums unless there are spaces around the + and -. It is unfortunate that we have to print rows of matrices with spaces to delimit the columns. We can either
- increase the column spacing to 3, or
- add some compact flag to the io context to tell AA that the plus token is "+" instead of " + "

**Comment by tthsqe12** [comment]
In any case, the printing still needs some design decisions.

**Comment by rfourquet** [comment]
> In general I cannot read sums unless there are spaces around the + and -.

In this case, what about keeping the spaces but wrapping the whole expression in parenthesis `(...)` ? (just an idea, not sure whether a good one; it might overload the printing too much)

**Comment by thofma** [comment]
I am not too big of a fan of parenthesis.

> * add some compact flag to the io context to tell AA that the plus token is "+" instead of " + "

I would prefer this. Should be relatively easy by printing the entries of a matrix with `:compact => true`.  This requires the our printing to better interact with the `IO` objects, which we wanted to do anyway.

**Comment by thofma** [comment]
@tthsqe12 cleaned up the printer so that we now could easily do
```julia
julia> Nemo.matrix( F, 1, 2, [ a^3+2*a^2, -a-1 ] )
[a^3+2*a^2 -a-1]

julia> Nemo.matrix( F, 1, 2, [ a^3+2*a^2-a, -1 ] )
[a^3+2*a^2-a  -1]
```
The only question is, if we want this. On a related not, neither Magma nor Sage do this. They both do not squeeze the elements.
But both Magma and Sage use 4 spaces as column separators.
```
> Matrix(K, 3, 3, [1 + a, 1, -a , -1, a, a, a, a, -a]);
[a + 1     1    -a]
[   -1     a     a]
[    a     a    -a]
```
So we just need a decision here. Since this basically effects all matrix printing in Oscar, ping @fingolfin @fieker.

**Comment by fieker** [comment]
On Fri, Feb 26, 2021 at 12:56:27AM -0800, thofma wrote:
> @tthsqe12 cleaned up the printer so that we now could easily do
> ```julia
> julia> Nemo.matrix( F, 1, 2, [ a^3+2*a^2, -a-1 ] )
> [a^3+2*a^2 -a-1]
> 
> julia> Nemo.matrix( F, 1, 2, [ a^3+2*a^2-a, -1 ] )
> [a^3+2*a^2-a  -1]
> ```
> The only question is, if we want this. On a related not, neither Magma nor Sage do this. They both do not squeeze the elements.
> But both Magma and Sage use 4 spaces as column separators.
> ```
> > Matrix(K, 3, 3, [1 + a, 1, -a , -1, a, a, a, a, -a]);
> [a + 1     1    -a]
> [   -1     a     a]
> [    a     a    -a]
> ```
> So we just need a decision here. Since this basically effects all matrix printing in Oscar, ping @fingolfin @fieker.
> 
No strong opinion: large matrices can never be readable, for small ones,
the 4 spaces might be better...

**Comment by tthsqe12** [comment]
close?
