### ISSUE TITLE
nmod_abs_series missing....

### ISSUE THREAD

**Issue by fieker** [Nemocas/Nemo.jl#979]
Even worse: the RelSeries{Nemo.gfp_elem} is also missing.

**Comment by wbhart** [comment]
RelSeries(Nemo.gfp_elem} is not missing:

```
julia> using Nemo

julia> R = GF(3)
Galois field with characteristic 3

julia> S, x = PowerSeriesRing(R, 10, "x")
(Univariate power series ring in x over Galois field with characteristic 3, x + O(x^11))

julia> typeof(x)
AbstractAlgebra.Generic.RelSeries{Nemo.gfp_elem}
```

However nmod_abs_series is indeed missing. We have fmpz_mod_abs_series, so it shouldn't be hard to add.

What you probably meant with your comment was that gfp_elem_rel_series and gfp_elem_abs_series don't exist yet.

**Comment by wbhart** [comment]
See also #473

**Comment by fieker** [comment]
On Fri, Feb 26, 2021 at 11:08:58PM -0800, wbhart wrote:
> RelSeries(Nemo.gfp_elem} is not missing:
> 
> ```
> julia> using Nemo
> 
> julia> R = GF(3)
> Galois field with characteristic 3
> 
> julia> S, x = PowerSeriesRing(R, 10, "x")
> (Univariate power series ring in x over Galois field with characteristic 3, x + O(x^11))
> 
> julia> typeof(x)
> AbstractAlgebra.Generic.RelSeries{Nemo.gfp_elem}
> ```
> 
> However nmod_abs_series is indeed missing. We have fmpz_mod_abs_series, so it shouldn't be hard to add.
> 
> What you probably meant with your comment was that gfp_elem_rel_series and gfp_elem_abs_series don't exist yet.
> 
This is generic code you're getting here - which is not the fastests, in
particular not in comparison to nmod_rel_series over ResidueRing(ZZ, 3).
Technically I should probably argue that the nmod_*series* code should
just be renamed into gfp_...
