### ISSUE TITLE
conversion of Padic to Rational?

### ISSUE THREAD

**Issue by wherrera10** [Nemocas/Nemo.jl#991]
When doing Padic arithmetic, is there a Nemo way to get back a rational number close to what would be the result in rational arithmetic? I realize that given precision the rational may not be unique. IE:

julia> set_printing_mode(FlintPadicField, :terse)
:terse
julia> Qp = PadicField(7, 22)
Field of 7-adic numbers
julia> a = Qp(QQ(4 // 11))
2843506217151264036 + O(7^22)
julia> b = Qp(QQ(2 // 7))
2/7 + O(7^21)
julia> c = a + b
355438277143908009/7 + O(7^21)
julia> 4//11 + 2//7
50//77

Is there a conversion of 355438277143908009/7 + O(7^21) that is approximately 50//77?

**Comment by thofma** [comment]
Yes, what you want to do is find x and y with 7*x/y = 355438277143908009 mod 7^21. So we first do x'/y' = 355438277143908009 mod 7^21 and then divide by 7. Finding this x and y goes under the name rational reconstruction and here is how to do it in Nemo:
```
julia> clift = lift(QQ, c)
355438277143908009//7

julia> q = reconstruct(numerator(clift), prime(Qp)^precision(Qp))
50//11

julia> q = reconstruct(numerator(clift), prime(Qp)^precision(Qp))//denominator(clift)
50//77
```

**Comment by wherrera10** [comment]
Aha. I missed the reconstruct function when I read the docs.  Perfect for my purpose. Thank you.
