### ISSUE TITLE
Add a `coeffs` method for `fq_nmod`

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/Nemo.jl#999]
For somewhat efficient conversion between `fq_nmod` and GAP finite fields of larger degree, it would be useful to have a method `coeffs` for `fq_nmod` which returns a `Vector{UInt}` with all coefficient in one go, instead of having to get each coefficient on its own (which is substantially slower).

Going the other way around, of course a constructor for `fq_nmod` taking such a vector would also be useful.

In the end, I mostly care about matrices, though; I guess there an in-place way to set the coefficients of an entry of a  `fq_nmod_mat` would be useful (say by having a `setindex!(a::fq_nmod_mat, u::Vector{UInt}, i::Int, j::Int)` method -- though of course it could also have a different, more internal sounding name like `_setindex!`.

I guess this requires either new APIs in FLINT, or we must be willing to directly poke into the `coeffs` field of `nmod_poly_struct` (since it is the first one, no annoying alignment issues crop up, so it wouldn't be too hard, and I guess more efficient than a `ccall`, too)

**Comment by wbhart** [comment]
This should be ok I think as the dense univariate format relies on being able to random access coefficients, which pretty much means it must be implemented by some underlying array. Therefore even a funky dense univariate polynomial format should always have a cheap way to extract an array of coeffs.

On the other hand what you are after is something lower level than just an array of coefficients/entries, as you want a different type than the type of basering elements.

As for Flint, there are interfaces for getting/setting an individual coeff/entry as a UInt, but you currently have to poke around internals to get a pointer to the internal array. Technically that is an implementation detail anyway though, so you may as well just poke around in internals to get it I think.

**Comment by thofma** [comment]
This would be in line with the other `*raw` functions we have for `nmod_poly` etc.

I prefer the `_setindex!` version. With the `setindex!` it is user-facing (since it is automatically exposed) and we would have to discuss if the input is supposed to be reduced or not. But surely in your application you are assuming that the input is reduced.

So it would be `coeffs_raw(a::fq_nmod)` yielding a `Vector{UInt}`. It can poke around in the internals as much as it want. Then `_setindex!(...)`, which assumes that the input is reduced. Or maybe `unsafe_setindex!`?

Not sure how to do the constructor. What about `(F::FqNmodFiniteField)(v::Vector{UInt}; reduce = true)`? Or `fq_nmod(v::Vector{UInt})` since those are not supposed to be by users anyway.

**Comment by wbhart** [comment]
It's always impossible to know what other users have already put an underscore on the name in their code, so I would go with at least a double underscore, unless you want to avoid people who were thinking the same way, in which case a triple or quadruple underscore is safer.

I knew there was something I forgot to put in the developer docs.

**Comment by fingolfin** [comment]
@wbhart  I wouldn't want to export the method, so I don't think the number of underscores matters? (Not that I mind either way -- tell me the name you want, I'll use it :-) )

@thofma Yeah it's for internal user, and it'll be already reduced data. But of course also having a version that reduces and/or checks isfine, too

BTW, working through a `Vector{UInt}` is in the end also a crutch; if Julia manages to optimize it away, fine; but if not, then for optimal performance, accessing a raw `Ptr{UInt}` for peeking/poking might be necessary (then I could directly poke the immediate integer coefficients I get from GAP there, with zero allocations, for the case were I write into an existing `fq_nmod`... But I'd rather worry about this once I can get around to implementing this; then I'd first write some microbenchmarks to determine the relative performance of the various approaches. I just wanted to make sure I don't waste time on writing code if everybody is up against the idea of poking at the low-level bits (in a controlled fashion, that is)

**Comment by wbhart** [comment]
I was joking anyway, call it what you want.

Flint will require the coeffs to be reduced if poking directly (unless you call nmod_poly_reduce,, which may still be cheaper than what we are doing, I'm not sure; probably depends on gc considerations). I guess that is all obvious already though.

**Comment by wbhart** [comment]
@thofma We have a lot of functions called setindex_raw! in Nemo. Perhaps we should just call it that?

@fingolfin Let us know whether you expect the function to reduce mod p for you. If so it will be a *much* more expensive operation.

**Comment by thofma** [comment]
Yes, of course! That sounds like a good name.

**Comment by wbhart** [comment]
I implemented:

* Nemo.setindex_raw!(a::fq, c::UInt, i::Int)
* fq_nmod(R::FqNmodFiniteField, V::Vector{UInt})
* coeffs_raw(a::fq)
